vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

In our environment, we use the annotation field to store additional information about the virtual machine. I added the ability to use this field when creating a virtual machine.

virtual machine - add annotation argument

---

tf-vsphere-devrc.mk.example

Correct a spelling mistake and consolidate variables. Some of these vars
are shared between tests and annotating them to a single resource did
not make sense. On the other hand, added annotations to reflect what the
variables represent so that there is as little ambiguity as possible.

Cleanup devrc

---

vsphere/resource_vsphere_virtual_disk.go

Migrated from [hashicorp/terraform#12734](https://github.com/hashicorp/terraform/pull/12734).
It's a very small, but very important change in my opinion.
There is no logical reason for setting up "ide" as the default adapter_type. This controller type is useless in the VMware world - disk cannot be resized, has less performance etc. Most of the OSes have drivers for vSCSI controllers and VMware recommends to convert every IDE disk to SCSI. Only for old Operating Systems (like virtualized Windows XP) there is a sense in using IDE. Of course after converting P2V, VM has IDE controller, but VMware recommends to convert IDE to SCSI too.
I have changed default adapter_type in the resource_vsphere_virtual_disk.go to "lsiLogic". Most of the operating systems have LSI Logic SCSI drivers. LSI …

Change default adapter_type to lsiLogic

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

Migrated from the old [hashicorp/terraform#14769](https://github.com/hashicorp/terraform/pull/14769)
Acceptance tests:
```
$ make testacc TEST=./vsphere/ TESTARGS='-run=TestAccVSphereVirtualMachine_basic'
TF_ACC=1 go test ./vsphere/ -v -run=TestAccVSphereVirtualMachine_basic -timeout 120m
=== RUN   TestAccVSphereVirtualMachine_basic
--- PASS: TestAccVSphereVirtualMachine_basic (751.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-vsphere/vsphere       751.427s
$ make testacc TEST=./vsphere/ TESTARGS='-run=TestAccVSphereVirtualMachine_hostname'
TF_ACC=1 go test ./vsphere/ -v -run=TestAccVSphereVirtualMachine_hostname -timeout 120m
=== RUN …
```

Set different hostname of a VM than name

---

vsphere/data_source_vsphere_datacenter.go
vsphere/data_source_vsphere_datacenter_test.go
vsphere/datacenter_helper.go
vsphere/provider.go
vsphere/resource_vsphere_folder.go
website/docs/d/datacenter.html.markdown
website/vsphere.erb

This data source fetches the managed object ID for a vSphere datacenter, and is
intended for use in other up-and-coming resources that will use a
managed object reference to a datacenter to fetch other resources (like
host systems), or tell resources where they need to be deployed to (may
eventually be used in `vsphere_virtual_machine`, for example).

New data source: vsphere_datacenter

---

vsphere/data_source_vsphere_datacenter.go
website/docs/d/datacenter.html.markdown

The "default" datacenter is actually for the most part a gvmomi thing, a
consequence of using the `DefaultDatacenter` calls in the find package.
This function simulates default datacenter fetching behaviour by
returning a single datacenter object from inventory if, and only if, a
singular datacenter object exists in inventory. This is always the case
on ESXi, but not on vCenter, and if there are multiple datacenters found
the call will fail. Docs have been updated to reflect this.

d/datacenter: Re-word "default" datacenter doc references

---

vsphere/data_source_vsphere_host.go
vsphere/data_source_vsphere_host_test.go
vsphere/datacenter_helper.go
vsphere/helper_test.go
vsphere/host_system_helper.go
vsphere/provider.go
vsphere/resource_vsphere_license_test.go
website/docs/d/host.html.markdown
website/vsphere.erb

This resource can be used to discover the managed object ID of a
specific host. Like `vsphere_datacenter`, this has been written to
facilitate the use of a managed object reference ID to fetch the host
system object to work with various resources, such as host networking
resources or datastores.

New data source: vsphere_host

---

tf-vsphere-devrc.mk.example
vsphere/helper_test.go
vsphere/host_network_policy_structure.go
vsphere/host_network_system_helper.go
vsphere/host_system_helper.go
vsphere/host_virtual_switch_structure.go
vsphere/provider.go
vsphere/resource_vsphere_host_virtual_switch.go
vsphere/resource_vsphere_host_virtual_switch_test.go
vsphere/structure_helper.go
website/docs/r/host_virtual_switch.html.markdown
website/vsphere.erb

This commit adds a new resource, `vsphere_host_virtual_switch`, which can be used to manage a virtual switch on an ESXi host.
Docs included, and tests have been run against both ESXi and vCenter.

New resource: vsphere_host_virtual_switch

---

website/docs/r/host_virtual_switch.html.markdown

The ID attribute is now a composite attribute that we assemble in code,
and not just the name of the resource, because that is not a unique
value or very telling of where the resource is actually located.
The ID change went in with #138, but I forgot to update the docs.

r/host_virtual_switch: Doc update for ID attribute

---

vsphere/helper_test.go
vsphere/host_network_system_helper.go
vsphere/host_port_group_structure.go
vsphere/provider.go
vsphere/resource_vsphere_host_port_group.go
vsphere/resource_vsphere_host_port_group_test.go
website/docs/r/host_port_group.html.markdown
website/vsphere.erb

This commit adds a new resource, `vsphere_host_port_group`, which can be used to manage a virtual switch on an ESXi host.
Docs included, and tests have been run against both ESXi and vCenter.

New resource: vsphere_host_port_group

---

tf-vsphere-devrc.mk.example
vsphere/data_source_vsphere_vmfs_disks.go
vsphere/data_source_vsphere_vmfs_disks_test.go
vsphere/host_storage_system_helper.go
vsphere/provider.go
website/docs/d/vmfs_disks.html.markdown
website/vsphere.erb

This adds the `vsphere_vmfs_disks` data source, which allows someone to discover the storage devices that can be used for VMFS datastores on a given ESXi host.
This is the first part of a 3-part push to add datastore support to the vSphere provider - specifically, the output of this is intended to be fed into a `vsphere_vmfs_datastore`, for which a PR will be put in after I finish working on that (will be starting work now that this is done).
This is WIP because I want to make sure that #138 and #139 are merged first, in addition to hashicorp/terraform#15931 so that I can use `ValidateRegexp` out of there, although the latter item might be moot as I have already picked out the commit in question with `govendor fetch`.

New data source: vsphere_vmfs_disks

---

tf-vsphere-devrc.mk.example
vsphere/datastore_helper.go
vsphere/datastore_summary_structure.go
vsphere/folder_helper.go
vsphere/helper_test.go
vsphere/host_data_store_system_helper.go
vsphere/provider.go
vsphere/resource_vsphere_vmfs_datastore.go
vsphere/resource_vsphere_vmfs_datastore_test.go
vsphere/structure_helper.go
vsphere/vim_helper.go
website/docs/r/vmfs_datastore.html.markdown
website/vsphere.erb

This is the next part of the push to add storage features to the provider.
This PR introduces the `vsphere_vmfs_datastore` resource, which can be
used to manage VMFS-based datastores.
Currently only whole disk support is included, however import
functionality is planned so that one can import existing datastores that
don't have full-disk extents, although whole disks will only be allowed
to be added from there.
Support for disk expansion may also be planned, depending on business
case.

New resource: vsphere_vmfs_datastore

---

vsphere/helper_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_helper.go
website/docs/r/virtual_machine.html.markdown

This commit adds something that we generally assume is correct in
Terraform - that an instance's power state is either one of two states:
on, or gone.
`vsphere_virtual_machine` has had a couple of issues that have been
attributed to power state in the last few months that have been fixed,
but the issue of ensuring that VMs are always powered on has not been
touched on yet.
In this commit, we add the `power_state` pseudo-computed variable,
working around the fact that the provider can't manipulate the diff
directly by using an immutable default to always indicate that a VM that
is powered off or suspended will be turned back on during the next
Terraform run. If a VM is powered off, this turns the VM back on during
the configuration modification phase at the end of the update.
Fixes #134. …

r/virtual_machine: Enforce powered on state

---

website/docs/r/datacenter.html.markdown
website/docs/r/file.html.markdown
website/docs/r/folder.html.markdown
website/docs/r/host_port_group.html.markdown
website/docs/r/host_virtual_switch.html.markdown
website/docs/r/license.html.markdown
website/docs/r/nas_datastore.html.markdown
website/docs/r/virtual_disk.html.markdown
website/docs/r/virtual_machine.html.markdown
website/docs/r/virtual_machine_snapshot.html.markdown
website/docs/r/vmfs_datastore.html.markdown
website/vsphere.erb

We are getting more resources now, and it will be worthwhile to start
departing them into categories now.
I am breaking down the categories mainly into their specific resource
classes as they are generally seen in vCenter:
* Hosts and Clusters
* VMs and Templates
* Storage
* Networking
There are other classes as well that will have resources that are not
necessarily related to be above that make logical sense:
* Administration - For vCenter and vSphere SSO related admin resources.
Licenses are in this category currently and items like tags and what not
will probably fall here as well.
* Inventory - For inventory management resources, such as datacenters
(which is a fancy top-level resource grouping) and folders (which can be
used across all four of the major resource classes).

website: Add resource categories

---

vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_helper.go

Maintaining this file has become increasingly difficult. As such, 
I have re-factored the tests in the style as we are doing most
of the new tests - highly functional, static configs with a tolerable
level of repetition, and all tests set up as subtests, so every test is
easy to locate as part of the larger test case list.
I have also removed a few tests that currently do not function, for one
reason or another. A couple of these are due to present bugs in the
resource, but as pending work may deprecate the resource in its current
form, I think maintenance effort is better spent elsewhere as they are
not currently reported business critical bugs that are rendering the
resource unusable.
The tests were:
* A test with a CDROM virtual device - this test was panicking. As it's
hard to imagine …

r/virtual_machine: Refactor tests

---

tf-vsphere-devrc.mk.example
vsphere/event_helper.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_helper.go
website/docs/r/virtual_machine.html.markdown

This is a two-part change that ultimately changes/Fixes customization
workflow, but has some other implications:
* First off, we are now waiting for customization to complete by
watching VM events. This is the correct way to wait for customization to
complete as the actual customization task returns very quickly, while
the actual customization process can actually take a few minutes and
fail out-of-band of the initial task.
* Second off, we are now no longer waiting for all interfaces to have IP
addresses during Read, rather we are now waiting for a **routeable**
network. This fixes situations where a template may be configured for
DHCP and gets an auto-configuration address before actually getting an
IP. This seems to come up during Windows customization especially,
which is what we are …

r/virtual_machine: Updated customization and net waiter behaviour

---

vsphere/data_source_vsphere_tag_category.go
vsphere/data_source_vsphere_tag_category_test.go
vsphere/provider.go
vsphere/resource_vsphere_tag_category.go
vsphere/tags_helper.go
website/docs/d/tag_category.html.markdown
website/docs/r/tag_category.html.markdown
website/vsphere.erb

This is the data source counterpart to the new `vsphere_tag_category`
resource. It allows one to pull in an external tag category by name,
using most of the same search call stack as importing.

New data source: vsphere_tag_category

---

vsphere/event_helper.go
vsphere/provider.go

Users have been reporting that 5 minutes is probably too short. Indeed,
in our lab it takes about 3 mins to complete (using nested ESXi and
datastores that are on SSDs), so this is definitely reasonable.
Adjusting this to 10 minutes which should hopefully be good for the vast
majority of cases. If need be, we can make this configurable, but then
we are wading into provider timeout territory as well.
-----
Also included in this is the adjustment of `defaultAPITimeout` to a const, since `time.Duration` is an int64 and can accommodate this.
Fixes #160

r/virtual_machine: Increase customization timeout to 10 mins

---

vsphere/tags_helper.go
vsphere/vim_helper.go
vsphere/vim_helper_test.go

Got some feedback from early adopters that the version comparison code
was broken and now using the provider on an unsupported version of
vSphere (ie: pre 6.0) was not working.
Added tests and discovered some issues with the code that was indeed
causing things to break probably:
* Product name was not being populated properly
* Needed to break off version comparison from the rest of the
older/newer logic so a reverse check on the version could be used to
first confirm that a version was not newer/older before moving on to
compare build versions.
Also updated the provider's version check to make sure it is also returning ineligible on if the products don't match. By design, `Older/Newer` return `false` for different products (it's not older or newer, it's different).

provider: Fix version comparison

---

vendor/github.com/vmware/vic/pkg/vsphere/tags/rest_client.go
vendor/github.com/vmware/vic/pkg/vsphere/tags/tags.go
vendor/vendor.json
vsphere/data_source_vsphere_tag.go
vsphere/data_source_vsphere_tag_test.go
vsphere/helper_test.go
vsphere/provider.go
vsphere/resource_vsphere_tag.go
vsphere/resource_vsphere_tag_test.go
vsphere/tags_helper.go
website/docs/d/tag.html.markdown
website/docs/r/tag.html.markdown
website/vsphere.erb

This adds the `vsphere_tag` resource and data source, allowing the ability to manage and pull in tags.
Next step is adding the ability to tag all of the objects in the provider that can be tagged!
PS: This also includes an update to the vic package which was also missing tag update support.

New resource and data source: vsphere_tag

---

vsphere/config.go
vsphere/data_source_vsphere_tag_category_test.go
vsphere/helper_test.go
vsphere/host_network_system_helper.go
vsphere/resource_vsphere_tag_category.go
vsphere/resource_vsphere_tag_category_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/tags_helper.go
website/docs/r/tag.html.markdown
website/docs/r/virtual_machine.html.markdown

This commit contains most of the up-front work necessary to tag objects, in addition to adding tagging capability to `vsphere_virtual_machine`.  With the work done here, adding tagging support to any resource that can support it should be a trivial act.
The one major exception is `vsphere_host_port_group`, which is an odd case as created port groups appear to be aggregated into a single network in vSphere. This commit includes helpers to determine a Network object ID from a specific network name and `HostSystem`, but are not tested at this point in time. We will probably need to support this case via a `vsphere_host_network_tag_association` resource and a `vsphere_standard_network` data source, the latter to derive the correct network MO and the former to associate the tag correctly. …

tags: Support tagging on vsphere_virtual_machine (and up-front work for other objects)

---

vsphere/config.go
vsphere/helper_test.go
vsphere/resource_vsphere_nas_datastore.go
vsphere/resource_vsphere_nas_datastore_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_vmfs_datastore.go
vsphere/resource_vsphere_vmfs_datastore_test.go
vsphere/tags_helper.go
website/docs/r/nas_datastore.html.markdown
website/docs/r/vmfs_datastore.html.markdown

This update supports tagging in the `vsphere_nas_datastore` and
`vsphere_vmfs_datastore` resources. Using the same workflows applied to
the virtual machine resource.
In addition to the tests supplied for the datastore resources, I've
re-enabled the import test for `vsphere_vmfs_datastore` now that we have
`ImportStateIdFunc` to help generate the ID.

tags: Support tagging in datastore resources

---

vsphere/resource_vsphere_datacenter.go
vsphere/resource_vsphere_datacenter_test.go
website/docs/r/datacenter.html.markdown

This update adds in the tagging support for datacenters. Just a few
minor modifications, nothing too serious, although this does now add the
`Read` function as tags on a datacenter (any object for that matter) are
modifiable in a non-destructive way.

tags: Add tagging support for datacenters

---

tf-vsphere-devrc.mk.example
vendor/github.com/hashicorp/terraform/helper/validation/validation.go
vendor/vendor.json
vsphere/folder_helper.go
vsphere/helper_test.go
vsphere/provider_test.go
vsphere/resource_vsphere_folder.go
vsphere/resource_vsphere_folder_migrate.go
vsphere/resource_vsphere_folder_migrate_test.go
vsphere/resource_vsphere_folder_test.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/folder.html.markdown

`vsphere_folder` has now been re-written, with the new version of the resource supporting all 5 major folder types, renaming, moving, and tagging. Documentation has also been fleshed out, and state migration is supported.
This work was undertaken as it was a little tricky to work with tags on the current incarnation of `vsphere_folder` resource, but also takes care of some work that has been pending for a long time to get `vsphere_folder` to support more than just virtual machines.

r/folder: Resource rewrite

---

vsphere/resource_vsphere_folder_migrate.go

My understanding of the `MigrateState` API was off, as it seems that the
return value for `StateMigrateFunc` is not the new state, but merely a
reference to the old state for error reporting purposes.
The folder state migration behaviour here was set to clone the state to
ensure that the old state was preserved in-flight - we are no longer
doing that as it seems like that is the source of the problem. Now the
state is just modified in place, assuming that refresh will drop a
failed migration's state on the floor.
Fixes #186.

r/folder: Fix state migration

---

vsphere/distributed_port_group_helper.go
vsphere/distributed_port_group_structure.go
vsphere/distributed_virtual_port_setting_structure.go
vsphere/helper_test.go
vsphere/provider.go
vsphere/resource_vsphere_distributed_port_group.go
vsphere/resource_vsphere_distributed_port_group_test.go
vsphere/resource_vsphere_distributed_virtual_switch.go
vsphere/tags_helper.go
website/docs/r/distributed_port_group.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown
website/vsphere.erb

This commit adds the `vsphere_distributed_port_group` resource, allowing
port groups to be created on DVS switches, introducing the ability to
manage real networks with Terraform that can be used to set up virtual
machines on.
This update also includes various fixes to #188 to fix spurious diffs
and expected behaviour when both resources are used in tandem.

New resource: vsphere_distributed_port_group

---

website/docs/index.html.markdown

It appears that starting with the 0.3.0 release tagging permissions are required when creating (at least) a folder, whether you set tags or not.

Updated docs to show permissions needed to perform tagging operations.

---

vsphere/resource_vsphere_virtual_machine.go
website/docs/r/virtual_machine.html.markdown

I needed this functionality and noticed that it was already commented with "TODO". It's my first foray into go so the following might be better worked out another way:
adapter_type_string := fmt.Sprintf("%T", device)
if adapter_type_string == "*types.VirtualE1000" {
Otherwise though it seems to work just fine.

created adapter_type variable for network interfaces

---

vsphere/resource_vsphere_virtual_machine.go

default virtual machines get customized with vsphere.local as dns lookup suffix. While most of the time there is a better alternative, being the domain name of the VM. This adds a check for this alternative
This was suggested a while ago and lived as a stash in my git folder.
rebased it, and pushed it.
I can test it tomorrow at work.

WIP: add domain as dns suffix option

---

vsphere/event_helper.go
vsphere/resource_vsphere_virtual_machine.go
website/docs/r/virtual_machine.html.markdown

The current value is hardcoded at 10 minutes, which has been possibly
causing some issues. This allows for the modification of the timeout -
so that it can be change to be a later value if customization takes a
long time (possible on systems with older hardware or non-SSD disk), or
disabled altogether to eliminate it as a source of problems.
Note that disabling the waiter pushes waiting over to the guest
networking waiter, which is currently also hardcoded at 5 minutes.
Modification of this attribute to a different value will require a state
migration (to translate `true` => `5min` and `false` => `<disabled>`) which is a
bit more of an involved change, so I want to take a wait-and-see
approach to see if it is required, especially considering the resource
will be undergoing a larger …

r/virtual_machine: Allow tuning of customization waiter

---

vsphere/helper_test.go
vsphere/resource_vsphere_folder_test.go
vsphere/resource_vsphere_tag_test.go
vsphere/tags_helper.go

`tagsClientIfDefined` was checking to see if the tags client was defined
as a condition to loading up the tags client for `Create` and `Update`
operations. While this generally worked for adding the tags to new
resources and changing tags when necessary, it was not working for
complete tag removal due to its reliance on `GetOk`, which fails if a
field is removed from config completely.
This fixes `tagsClientIfDefined` so that it checks both the old and new
incarnations of the `tags` argument to make sure that both are empty
before passing on loading the tags client.

tags: Ensure complete removal of tags is working

---

vsphere/resource_vsphere_virtual_machine.go

The new gateway discovery code inadvertently caused a regression in the
fixes that were made to prevent TF from crashing when a VM was powered
off. This fixes that by skipping the GW discovery altogether when there
is no guest device information to use for the association.

r/virtual_machine: Don't attempt to discover gateway on power off

---

vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go
vsphere/distributed_virtual_switch_helper.go
vsphere/host_network_system_helper.go
vsphere/network_helper.go
vsphere/provider.go
website/docs/d/network.html.markdown
website/vsphere.erb

This introduces the `vsphere_network` data source, which allows one to
look up a general network in vSphere via a path.
This will be useful in upcoming resources that will require a network
managed object ID, versus a network name or path, effectively moving all
of the "heavy lifting" in translating a network from a human-readable
name to an object over to this data source, versus being handled in the
resource itself (which will ultimately just fetch the network by its
MOID, without worrying about the details underneath).

New data source: vsphere_network

---

vsphere/resource_vsphere_distributed_port_group.go
website/docs/r/distributed_port_group.html.markdown

The additions that are in #201 dictate the basis for how we will be
working with vSphere networks in the future - any resource that requires
a network for a backing (ie: virtual ethernet cards, VMkernel nics, etc)
will require a MOID to some sort of network, versus the name itself,
allowing us to circumvent actually searching for the network in the
downstream resource itself. Searching would be circumvented altogether
in the case of DVS portgroups being managed by TF completely as we would
just pass the MOID to the downstream resource.
The current behaviour of the `vsphere_distributed_port_group` resource is
to use the `key` attribute in the MO as the ID of the resource, which is
documented in the API as the UUID of the DVS port group, although in
reality it actually seems to be the MOID, …

r/distributed_port_group: Use MOID as resource ID

---

vendor/github.com/vmware/govmomi/find/recurser.go
vendor/github.com/vmware/govmomi/object/custom_fields_manager.go
vendor/github.com/vmware/govmomi/object/virtual_device_list.go
vendor/github.com/vmware/govmomi/vim25/soap/client.go
vendor/vendor.json
vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go

This fixes a couple of things:
* Datacenter was not being skipped properly when it was not specified in
config, causing the data source to try to look up an empty string for
the DC. This fix will need to be applied to the
`vsphere_distributed_virtual_switch` data source too.
* govmomi has been updated, this addresses vmware/govmomi#875, which
affects this resource and also indirectly #10 (although the
`vsphere_virtual_machine` resource has its own problems with absolute
paths that are not going to be fixed until the refactor).

d/network: Update govmomi, fix network absolute path searching issues

---

vendor/github.com/vmware/govmomi/find/recurser.go
vendor/github.com/vmware/govmomi/object/custom_fields_manager.go
vendor/github.com/vmware/govmomi/object/virtual_device_list.go
vendor/github.com/vmware/govmomi/vim25/soap/client.go
vendor/vendor.json
vsphere/data_source_vsphere_distributed_virtual_switch.go
vsphere/data_source_vsphere_distributed_virtual_switch_test.go
vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go

As per #203, this fixes the `vsphere_distributed_virtual_switch` data
source so that it allows for an absolute path in lieu of a datacenter,
as per the specification in the docs.
This was intended, but we were missing the use of `GetOk` to ensure that
the datacenter was actually specified.

d/distribtued_virtual_switch: Correctly allow unspecified datacenter

---

README.md
]
vsphere/host_network_policy_structure.go
vsphere/resource_vsphere_virtual_disk.go
website/docs/d/datacenter.html.markdown
website/docs/d/distributed_virtual_switch.html.markdown
website/docs/d/host.html.markdown
website/docs/d/network.html.markdown
website/docs/d/tag.html.markdown
website/docs/d/tag_category.html.markdown
website/docs/d/vmfs_disks.html.markdown
website/docs/index.html.markdown
website/docs/r/distributed_port_group.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown
website/docs/r/file.html.markdown
website/docs/r/folder.html.markdown
website/docs/r/host_port_group.html.markdown
website/docs/r/host_virtual_switch.html.markdown
website/docs/r/nas_datastore.html.markdown
website/docs/r/tag.html.markdown
website/docs/r/tag_category.html.markdown
website/docs/r/virtual_disk.html.markdown
website/docs/r/virtual_machine_snapshot.html.markdown
website/docs/r/vmfs_datastore.html.markdown
website/vsphere.erb

This PR does various documentation cleanup tasks and what not that I wanted to take care of pre-v1.0.0.
Contained herein:
* Normalize parameter documentation style. This is basically a distinction between what is required and what is optional, no parameter type (implied instead by the notes in the parameter docs), and an English sentence at the end of `ForceNew` attributes.
* Updated the doc index page with a new example, removal of "this is a WIP", and a shortening of some of the information, designed to ensure the index ages and scales well. Most contributing information has now been removed with a referral to the provider repo instead.
* Some grammar fixes and extra explanations where they have been warranted.
As part of the documentation efforts is deprecating `adapter_type` in …

docs: pre-1.0.0 documentation cleanup, deprecate adapter_type in vsphere_virtual_disk

---

vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go
website/docs/d/network.html.markdown

This resource has always functioned correctly on ESXi, and will be
required to work with virtual machines going forward, so it's important
it works on both ESXi and vCenter.
Specifically tested this on ESXi to make sure. Also added skips for all
the DVS related tests in this data source so that the host/standard port
group example is the only one that runs when conducting ESXi tests.

d/network: Remove vCenter requirement

---

vsphere/internal/helper/computeresource/compute_resource_helper.go
vsphere/internal/helper/envbrowse/environment_browser_helper.go
vsphere/internal/helper/folder/folder_helper.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

This PR comprises the changes that are in #257 and #258, and a couple of more commits on top of those. Will be closing the other two PRs shortly.
The fixes are:
* Backwards compatibility fixes: EFI secure boot is only available on vSphere >= 6.5, and disk sharing is only available on vSphere >= 6.0.
* Moved `EnvironmentBrowser` helper methods to use `QueryConfigOption` instead of `QueryConfigOptionEx`, ensuring the helpers can be used on vSphere 5.5 as well.
* Looks like a "move to folder" test was missed, and it turns out this was not fully functional yet. Added the support in to make this work.
Smoke tested EFI secure boot and disk sharing options on our lab to make sure they both still took effect on vSphere 6.5. Will be re-running full test suite tonight and will paste the results in …

r/virtual_machine: Post-merge, pre-release changes

---

vendor/github.com/hashicorp/terraform/helper/validation/validation.go
vendor/vendor.json

This fixes the documentation of StringMatch so that it's consistent with
its implementation.
Very minor, but it's just a loose end I'd like to be in 1.0.0. This will
be updated along with all of the TF deps on the next release this is
merged in.

vendor: Update validation to 5da62a44f

---

vsphere/data_source_vsphere_resource_pool.go
vsphere/data_source_vsphere_resource_pool_test.go
vsphere/internal/helper/folder/folder_helper.go
vsphere/internal/helper/resourcepool/resource_pool_helper.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/d/resource_pool.html.markdown

Looks like there are a couple of issues with the release that are currently blocking its use on ESXi:
* The documented `vsphere_resource_pool` data source usage for ESXi was not working - `name` was required and the helper was not auto-locating the standalone ESXi datacenter properly,
* The `vsphere_virtual_machine` resource now uses folder functionality out of our folder helper, which was normally restricted to vCenter-only scenarios before. This loosens those requirements just enough so that the VM resource can get the root folder from the standalone ESXi "inventory" to create the VMs in.

Small post-release ESXi fixes

---

website/docs/index.html.markdown

This is something that has potentially come up, had to do a bit of
looking into it myself as it's been a while since I've used free ESXi
and sure enough API "write" operations are not supported, hence the
provider is not really usable on such environments.

docs: Free ESXi is not supported

---

vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

There was some issues with our device culling/ranging logic in certain
scenarios:
* On templates with no NICs, unitRange was not producing a proper
result. This was the result of these values being pointers because we
work with the unit number value directly in the virtual device, which is
a pointer. This fixes things so that if a zero-length device list is
passed to unit range, we return 0 immediately (as there are no devices
to range over).
* On templates where the NIC count was less than the amount of NICs
needed by configuration, the device cull range expression (which is used
to handle the exact opposite scenario) was running into out-of-range
issues. This has been fixed by asserting that the old device list is
indeed longer than the new device list so that there's no way that …

r/virtual_machine: Device cull range fix, and handle zero-NIC templates

---

vsphere/internal/helper/viapi/vim_helper.go
vsphere/internal/helper/viapi/vim_helper_test.go

Version comparison logic was not sound across minor and patch versions.
The new logic just bit-shifts major and minor so that a nice clean
comparable integer. I'd imagine this will be fine, as I've never seen
VMware put out any sort of release with a version anywhere close to the
8-bit space we give each version particle now.
Fixes #265.

helper/viapi: Fix version comparison logic

---

vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go

While creating a virtual CDROM and attaching it, I was getting a handful of errors that seemed unrelated to the network_interface:
```
* vsphere_virtual_machine.orchestrator-2: 1 error(s) occurred:
* vsphere_virtual_machine.orchestrator-2: Invalid address to set: []string{"network_interface", "0", "path"}
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Digging through the code, I found a schema update that was using the `subresourceTypeNetworkInterface` type instead of `subresourceTypeCdrom`. After using this newly built provider plugin, I'm able to create the instance …

Use subresourceTypeCdrom for cdrom schema update

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
website/docs/r/virtual_machine.html.markdown

A VM that's cloned with `linked_clone` and different disk mode options
that what is set on the source template will end up with inconsistent
settings post-clone, causing a read-update failure that will leave the
VM in a state that is irrecoverable to Terraform - the only way to
rectify the situation is to delete the VM and start over with a new
state.
This adds extra validation to make sure that `thin_provisioned` and
`eagerly_scrub` are set to the same settings as the source template's
counterpart disk, along with validating that the disk is the exact same
size (something that wasn't done yet).
Fixes #275.
-----
PS: There will be a larger-ish PR (mainly because of adjustments to tests) that will follow this one to add `thin_provisioned` and `eagerly_scrub` attributes to the …

r/virtual_machine: Validate exact disk type when using linked_clone

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

This corrects an issue with the way NIC devices were checked to see if
the slots they are supposed to occupy on the PCI bus were already used
or not. An offset that was used to populate the current device range was
not being used when the devices were actually checked, creating invalid
results and out of range errors.
Fixes #279.

r/virtual_machine: Correct present NIC device calculation

---

vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go

When cloning a VM, and specifying a virtual cdrom device, it doesn't boot with it connected. 
I'm not sure if this PR is the appropriate approach -- maybe it should be a config parameter, however as it currently stands the virtual cdrom functionality does not mimic what was previously in 0.4.x, where it would automatically be connected.

Connect virtual cdrom on boot

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

This is another fail-safe - this time, we are blocking virtual machine
rename operations that coincide with the deletion of any disks that bear
the name.
This prevents a scenario where disk names are being controlled by the
same variable that controls the virtual machine name - a very likely
scenario, given that clones require that the disks contain the name of the
virtual machine.
Also, documentation for the virtual machine resource has been updated
with a suggested workaround, using `null_resource` with an `ignore_changes`
to store the original name permanently.

r/virtual_machine: Block VM renames that result in disk deletion

---

website/docs/r/virtual_machine.html.markdown

The optional timeout to wait for a clone to complete appears to be 30 minutes, not 10 minutes. I discovered this through direct observation.

Change documentation of value for default clone timeout to 30 min.

---

vsphere/helper_test.go
vsphere/internal/helper/datastore/datastore_helper.go
vsphere/internal/helper/structure/structure_helper.go
vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
vsphere/internal/helper/virtualdisk/virtual_disk_helper_test.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

This is the re-incarnation of #304.
-----
There are certain situations where the filename on a disk can get lost,
namely associated with snapshots, and storage vMotion on VMs that have
been created from linked clones or when a virtual machine has been
renamed.
In light of this, long-term we are planning on transitioning away from
being able to control the name of virtual disks that are not attached
externally. This stop-gap ensures that the disk is kept in situations
like this - where we actually find a disk recognized at a specific
location that we are tracking, versus just deleting the disk because the
logic does not consider it "orphaned".

r/virtual_machine: Do not delete disks at same address as existing disk

---

vsphere/helper_test.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

This was incorrectly changed from v0.4.2. While failing on read errors
is normal, it's a TF convention to check to see if the read error was
due to a resource being deleted outside of the TF workflow, and if it
has, mark that resource as gone by blanking out its ID.
This update restores that behavior to the VM resource. Other resources
in the provider will need to have this functionality added, although
most of those items are core infrastructure resources and are not as
ephemeral as a virtual machine is, so they are probably lower priority
to update. They will be done on an as needed basis.
Fixes #299.

r/virtual_machine: Remove OOB deleted virtual machines from state

---

vendor/github.com/terraform-providers/terraform-provider-null/CHANGELOG.md
vendor/github.com/terraform-providers/terraform-provider-null/GNUmakefile
vendor/github.com/terraform-providers/terraform-provider-null/LICENSE
vendor/github.com/terraform-providers/terraform-provider-null/README.md
vendor/github.com/terraform-providers/terraform-provider-null/main.go
vendor/github.com/terraform-providers/terraform-provider-null/null/data_source.go
vendor/github.com/terraform-providers/terraform-provider-null/null/provider.go
vendor/github.com/terraform-providers/terraform-provider-null/null/resource.go
vendor/vendor.json
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/provider_test.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

This PR adds restrictions to storage vMotion:
* Externally-attached disks cannot be migrated.
* Disk names must match the standard vSphere naming convention based on
the current name of the virtual machine.
* Linked clones are blocked from being migrated at this time.
The latter two restrictions will be lifted once #295 is fully realized
and we are tracking disks via a label/UUID combination.
---
Disk attachment migration is something I'd like for us to handle as well eventually, but exactly how that will be handled is a bit tricky as VM configuration needs to be updated as well pretty much at the same time. It might not be possible in the long run.

r/virtual_machine: Enforce storage vMotion restrictions

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_virtual_machine.go

These are not default settings so this only comes up if you try to set
them, but they should be restricted anyway. Oddly they are settable on
vCenter 5.5 update 3f, and the settings take, but they do not seem to be
visible in the MOB. The docs say that the settings are not available
until vSphere 6 anyway.
Fixes #286.

r/virtual_machine: Network allocation settings require vSphere >= 6.0

---

website/docs/d/resource_pool.html.markdown
website/docs/r/virtual_machine.html.markdown

There has been some confusion surrounding the fact that the
`vsphere_virtual_machine` resource now only takes a resource pool ID with
users that do not make use of resource pools, opting to just put virtual
machines in the root-level cluster or standalone host. This actually
places those virtual machines in a root resource pool that represents
all of the compute power of a particular host or set of hosts.  This
pool is normally invisible to the user and can only be seen generally by
using a tool that can browse the inventory off the CLI, like `govc`.
There are no plans to complicate the VM resource's implementation by
adding parameters like `compute_resource_id` - there is no point as they
would ultimately be looking up a resource pool anyway. Future plans may
see the development of data …

docs: Clarify the use of cluster/host root resource pool

---

website/docs/r/virtual_machine.html.markdown

Observed in VMware VirtualCenter version=6.5.0, build=5318154
When cloning from a template with an e1000 NIC with no `adapter_type` specified, TF uses vmxnet3 and not e1000 as a default.
```
network_interface.0.adapter_type:                 "" => "vmxnet3"
```

Default value for adapter_type is vmxnet3 not e1000

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource_test.go

Looks like `unitRange`, a virtual device (read: virtual NIC device) helper
that helps calculate the device unit range we need to account for when
refreshing devices, and also running post-clone device modification
operations, was not behaving as intended. We were incorrectly using the
current NIC set as the source of truth for the unit floor, in addition
to correctly using it for the device ceiling). This was creating issues
where the current NIC set started at an offset that was higher than
where NIC devices start on the PCI bus.
This fix corrects that - the NIC PCI device offset constant is now what
defines the device floor, and is immutable. The only thing that gets
modified is the ceiling. Added a few unit tests to back it up.
Also renamed the function `nicUnitRange` to reflect the …

r/virtual_machine: Fix NIC device offset misalignment crashes

---

GNUmakefile
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_migrate.go
vsphere/resource_vsphere_virtual_machine_migrate_test.go
vsphere/resource_vsphere_virtual_machine_snapshot_test.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/index.html.markdown
website/docs/r/virtual_machine.html.markdown

This resource implements the work discussed in #295, which significantly changes the way that we work with virtual disks in the `vsphere_virtual_machine` resource.
The changes are:
* Virtual disks are now addressed via the `label` attribute in configuration, rather than the `name` attribute, which previously dictated both the name of the virtual disk in configuration, and the actual VMDK filename on the virtual machine. This was problematic for several reasons that are discussed in #295.
* The `path` attribute has been implemented as a dual-purpose attribute that, depending on the setting of `attach`, either controls the path of the externally attached disk, or is a read-only computed attribute that gives the current path to the specific virtual disk (in the event of non-attached virtual …

r/virtual_machine: New disk device naming and tracking behaviour

---

website/docs/r/virtual_machine.html.markdown

Had the old, pre-merge default of `lsilogic`, this was changed to `pvscsi`
during the PR review process.

docs: Fix virtual_machine default scsi_type

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

Due to how the DeviceChange struct works in API, it's possible to end up
setting up a list of DeviceChange operations that possibly point to
the same underlying virtual device. In this instance, with our logic,
any subsequent operations that result in a device change will end up
changing all operations before it into the same state as the most
current version of that virtual device, causing an invalid operation.
This can be seen in a scenario that a VM is cloned from template, with
both the SCSI bus type and disk size changing at the same time:
* The SCSI type change will add an operation that changes the controller
the disk is attached to.
* The second operation will change the size of the virtual disk.
Both of these operations will operate on the same VirtualDisk device
instance and if …

r/virtual_machine: Fix multiple change operations to a single device

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go

Historically, the `FindByUuid` method under `SearchIndex` did not support
looking up VMs marked as template. However, at some point in time, this
was changed (possibly vSphere 6.5, based on bug reports), and any
mention of the UUID search not supporting templates was removed from the
API documentation, without a mention of when support for templates was
introduced. Since this is the method that we use to look up both VMs and
templates, this means that templates have not been functional for
vSphere <= 6.0 users since the resource was re-written in 1.0.
There has been a workaround in that the source template is just
converted back to virtual machine, but this update fixes it so that on
versions of vSphere older than 6.5, we fall back to using `ContainerView`
with a filter on the UUID. This …

r/virtual_machine: Fix template UUID lookup for older vSphere versions

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go

There seems like there is possibly a bug in `RetrieveWithFilter` when it
comes to MO's with missing keys and the function returning a false
positive for the object in question. This has caused issues with the VM
search functionality where duplicate UUID errors will be returned for
VMs with UUIDs that are otherwise unique within vSphere inventory if
there are orphaned VMs in inventory that lack a configuration (as in the
whole config data object is missing).
This bug applies to the provider when being used with vSphere 6.0 and
earlier.

r/virtual_machine: Switch ContainerView search to use manual filter

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource_test.go

A couple of issues come up when vCenter is upgraded:
* First off, disk `capacityInBytes` values for virtual machine disk devices are cleared. This is a value we rely on to set the capacity of a disk, so a fallback to capacityInKB is necessary. This is specifically important for templates, as while VMs will be powered on and this value will be populated again, more than likely templates will remain off after the upgrade.
* Also post-upgrade, the VM hardware version of an existing virtual machine will not have been updated (this would need to be changed manually), hence `disk_sharing` will be unset and unusable. However, this value will now be read in by Terraform due to the upgraded vCenter, albeit with a blank value, and will trigger a diff that will ultimately result in an error. Hence, …

r/virtual_machine: Address vCenter upgrade issues

---

tf-vsphere-devrc.mk.example
vsphere/internal/helper/computeresource/compute_resource_helper.go
vsphere/resource_vsphere_virtual_machine_test.go

The virtual machine resource relies on the cluster or standalone host
it's deployed on for information regarding a default hardware set or
guest OS family information. This is obtained via the `EnvironmentBrowser`
MO referenced by the respective cluster or host's `ComputeResource` MO.
There are certain situations where this attribute will be missing, two
of which have been identified so far via bug reports:
* A cluster without hosts will not contain an environment browser.
* vSphere licensing issues may cause a missing environment browser (#409
reported an expired vCenter).
This update wraps our fetching of the environment browser by the two
current compute resource helpers that utilize it in a helper that
validates that we actually have an environment browser before proceeding
to load it …

r/virtual_machine: Handle missing environment browser

---

vsphere/data_source_vsphere_custom_attribute_test.go
vsphere/data_source_vsphere_datacenter_test.go
vsphere/data_source_vsphere_datastore_test.go
vsphere/data_source_vsphere_distributed_virtual_switch_test.go
vsphere/data_source_vsphere_host_test.go
vsphere/data_source_vsphere_network_test.go
vsphere/data_source_vsphere_resource_pool_test.go
vsphere/data_source_vsphere_tag_category_test.go
vsphere/data_source_vsphere_tag_test.go
vsphere/data_source_vsphere_virtual_machine_test.go
vsphere/data_source_vsphere_vmfs_disks_test.go
vsphere/resource_vsphere_custom_attribute_test.go
vsphere/resource_vsphere_datacenter_test.go
vsphere/resource_vsphere_distributed_port_group_test.go
vsphere/resource_vsphere_distributed_virtual_switch_test.go
vsphere/resource_vsphere_file_test.go
vsphere/resource_vsphere_folder_migrate_test.go
vsphere/resource_vsphere_folder_test.go
vsphere/resource_vsphere_host_port_group_test.go
vsphere/resource_vsphere_host_virtual_switch_test.go
vsphere/resource_vsphere_license_test.go
vsphere/resource_vsphere_nas_datastore_test.go
vsphere/resource_vsphere_tag_category_test.go
vsphere/resource_vsphere_tag_test.go
vsphere/resource_vsphere_virtual_machine_snapshot_test.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/resource_vsphere_vmfs_datastore_test.go

This PR is large but hopefully straightforward, and is a refactor to convert acceptance tests from the provider-local subtest pattern to the more widely used single-function-per-test pattern (ie: `TestAccResourceVSphereSomeResource_basic` et al).
The reason this is needed is that our currently acceptance test runner in CI relies heavily on the common convention, for doing things like collating the output of individual tests into their own streams, formatted into a format that TeamCity is aware of. `go test -list` is also made use of, which currently does not support subtests, so this would be a full stop blocker to getting nightly acceptance tests working here.
A couple of minor fixes have been made to tests that were missing `ImportStateVerify` keys, and also a couple of linter fixes …

Convert all acceptance tests to individual tests

---

vsphere/config.go
vsphere/config_test.go
vsphere/provider.go

This should have been tested properly in #422, but the way
`providerConfigure` was returning a fully configured `Client` versus the
configuration made it hard to do so, so it was skipped, and of course I
was burned as a result. :stuck_out_tongue: 
This fixes things so that the actual creation of the `Config` struct is
moved to a separate `NewConfig` function, which allows us to test for the
valid config keys. `providerConfigure` then just calls that.

provider: Fix keys in configuration function, refactor stack

---

vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

This does a few things:
* Looks like some acceptance test were broken - first one was due to
something changing in RancherOS that does not allow for the proper
hot-remove of virtual NICs anymore. I've adjusted this test so it
powers off the VM first, which is not so much an issue as we aren't
testing for a hot-remove anyway, but more to make sure that things are
consistent in state.
* The vApp property tests were missing settings for `thin_provisioned` and
`eagerly_scrub`, which should be coming from the template data sources.
These were failing as a result as the CoreOS OVA does not use thin
provisioned disks.
* Finally, #421 introduced a change where we were actually failing if we
didn't recognize the CD drive type. There are a few we still don't
support, namely passthrough CD drives. …

r/virtual_machine: Fix broken acceptance tests and CD drives

---

vsphere/helper_test.go
vsphere/internal/helper/customattribute/custom_attributes_helper.go
vsphere/internal/helper/folder/folder_helper.go
vsphere/internal/helper/storagepod/storage_pod_helper.go
vsphere/internal/helper/structure/structure_helper.go
vsphere/provider.go
vsphere/resource_vsphere_datastore_cluster.go
vsphere/resource_vsphere_datastore_cluster_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/tags_helper.go
website/docs/r/datastore_cluster.html.markdown
website/vsphere.erb

This is the first part of a new push to add clustering and DRS support in the vSphere provider.
This adds `vsphere_datastore_cluster`, which can be used to create datastore clusters and configure Storage DRS for it respectively. Pretty much everything that's exposed in vSphere is exposed in the resource.
Note that the docs reference functionality that is not implemented yet - this is the `datastore_cluster_id` attribute, which will basically be a "pseudo-folder" attribute and conflict with `folder` in the `vsphere_nas_datastore` and `vsphere_vmfs_datastore` resources, allowing a datastore to be created in or moved to a datastore cluster.
After this support is in and functional we can use it to start writing datastore cluster support into the `vsphere_virtual_machine` resource to address …

New resource: vsphere_datastore_cluster

---

vsphere/data_source_vsphere_datastore_cluster.go
vsphere/data_source_vsphere_datastore_cluster_test.go
vsphere/provider.go
vsphere/resource_vsphere_datastore_cluster.go
vsphere/resource_vsphere_datastore_cluster_test.go
website/docs/d/datastore_cluster.html.markdown
website/vsphere.erb

This is a data source counterpart to the `vsphere_datastore_cluster`
resource, designed to fetch the ID of a datastore cluster only as we
want to be able to provide a data source avenue for this data, to ensure
that people can use existing infrastructure that was not created in
Terraform.

d/datastore_cluster: New data source

---

vsphere/resource_vsphere_datastore_cluster.go
website/docs/r/datastore_cluster.html.markdown

This was mistakenly set to automated - the actual default as per the
vSphere documentation is manual. Changed to be consistent.
Reference: https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-563D504F-DEC3-430A-8294-7135CBBADB83.html
> Manual is the default automation level.

r/datastore_cluster: Change default SDRS automation level to manual

---

website/docs/d/datastore.html.markdown

Fixing example code so that the datacenter_id in vsphere_datastore is retrieved from the previous vsphere_datacenter block

datastore.html sample code fix

---

website/docs/r/folder.html.markdown

Their is a mistake in the documentation. Attribute name does not exist. It should be using path attribute.
**Error :**
* vsphere_folder.folder: Resource 'vsphere_folder.parent' does not have attribute 'name' for variable 'vsphere_folder.parent.name'
**Terraform Version :**
Terraform v0.11.6
+ provider.vsphere v1.3.3

Fix Subfolders Documentation

---

vsphere/resource_vsphere_virtual_machine_test.go

This fixes the vApp ISO tests, which were failing because the Ubuntu
OVAs do not have a way of getting a static network configuration, hence
they wait 5 minutes on DHCP on our static network.
We had an image we hacked to lower this timeout, but the template was
recently re-uploaded, and the hacking process is cumbersome (involving
mounting the VMDK in the OVA to add an override to networking.service),
and is not easily repeatable with our current process.
As the acceptance tests are automated, waiting the extra time for the
DHCP timeout is not a big deal. Hence we've just upped
`wait_for_guest_net_timeout` to 10 minutes on the appropriate fixtures.

r/virtual_machine: Fix vApp ISO tests

---

vsphere/data_source_vsphere_virtual_machine.go

This handles a crash case when there is no configuration for a specified
virtual machine.
This unfortunately is an edge case and hard for us to test for, as cases
like this where the VM lack a `config` attribute are usually due to issues
with importing the VM, or an orphaned virtual machine in vSphere.
Ref: #432

d/virtual_machine: Nil check for empty VM configuration

---

vendor/github.com/hashicorp/terraform/terraform/interpolate.go
vendor/github.com/hashicorp/terraform/version/version.go
vendor/vendor.json

Our copy was mostly up to date already, but this ensures that we are
vendoring at a tag versus a commit.

vendor: Update TF to @v0.11.7

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_migrate.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

This adds the wait_for_guest_net_routable setting, which allows for the
modification of the behavior of the network waiter with relation to
whether or not it compares IP addresses it discovers against the default
gateway.
When false, the waiter will ignore any gateways - it will exit
successfully on discovery of any "real" address - in other words, one
that is not link-local/loopback/multicast, regardless of if the address
does not match a discovered default gateway, or regardless if a gateway
has even been discovered yet.
-----
Related: #462, #446, #337, #231, #207.

r/virtual_machine: Controllable routable network waiter behavior

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

This is something that has been an issue for while but is now even more prominent now that datastores don't necessarily need to be specified at all. Owing in part that `datastore_id` is not populated during the initial TF apply when using the default datastore for disks, changing both the default datastore (or now, possibly, datastore clusters) and a key that forces a new resource at the same time will create a diff mismatch.
A couple of approaches can fix this issue:
* The first one being marking the `datastore_id` attribute of the `disk` sub-resource as `Computed`, but this method opens the resource up to other bugs when a new disk is taking the place of an old disk in state, and Optional/Computed ultimately results in the old datastore ID setting being grafted into the new …

r/virtual_machine: Ensure datastore_id will always have a diff on new disk sub-resources

---

vsphere/resource_vsphere_virtual_machine.go

The ID of the resource is actually necessary for rollback as we send the
VM through full resource deletion during rollback (this is to safely
detach any disks that may have been attached already). This commit moves
the ID step back to where it previously was. However, we clear the ID no
matter what in the rollback function (via a defer at the start of the
rollback function).

r/virtual_machine: Restore ID availability to rollback functionality

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

Cloning on ESXi is not a supported workflow in the vSphere API. This has
been a point of confusion for a bit, hence we are now explicitly
blocking it.

r/virtual_machine: Explicitly block cloning on standalone ESXi

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

Split virtual disk diff function into validation and normalization. Some
normalization tasks should not be performed on new or unmatched virtual
disks, but validation should be performed on all.

r/virtual_machine: Split disk Diff

---

website/docs/d/resource_pool.html.markdown
website/docs/d/virtual_machine.html.markdown

Fixing example code so that the datacenter_id is retrieved from the previous vsphere_datacenter block. Similar to #459 but in two other pages - I think this is them all

Fixing example code (documentation)

---

vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

fix #387 
high LatencySensitivity VM is important when customers trying to reduce VM latency for applications.
now users can configure high LatencySensitivity VM with following terraform parameters:
`latency_sensitivity = "high"
memory_reservation = $memory
`
tested with a vSphere cluster(vCenter and ESX), govc and
Terraform v0.11.3
+ provider.ignition v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
+ provider.vsphere (modified based on v1.4.1)
appreciate your review in advance.

add vm configure latencySensitivity support

---

vsphere/data_source_vsphere_compute_cluster.go
vsphere/data_source_vsphere_compute_cluster_test.go
vsphere/provider.go
website/docs/d/compute_cluster.html.markdown
website/docs/d/resource_pool.html.markdown
website/docs/r/virtual_machine.html.markdown
website/vsphere.erb

This adds the `vsphere_compute_cluster` data source, which allows one to
look up an existing cluster.
It also closes a convenience gap in the provider which has been a point
of confusion since around 1.0, in that people looking to supply the
`resource_pool_id` for a virtual machine were confused in that they didn't
think they had a resource pool. This now allows someone to specify a
cluster directly, and then use the `resource_pool_id` attribute from this
data source as the input to `vsphere_virtual_machine`.

d/compute_cluster: New data source

---

vsphere/helper_test.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/provider.go
vsphere/resource_vsphere_drs_vm_override.go
vsphere/resource_vsphere_drs_vm_override_test.go
website/docs/r/drs_vm_override.html.markdown
website/vsphere.erb

This adds the `vsphere_drs_vm_override` resource, which can be used to control overrides for DRS and automation levels for virtual machines within DRS (compute) clusters.
This is one of three compute-related VM override resources. The other two, which will be following in future PRs, are:
```
vsphere_ha_vm_override
vsphere_dpm_host_override
```
These are separated as they are separate fields in the vSphere API's `ClusterConfigSpecEx`/`ClusterConfigInfoEx`. Having them as separate resources simplifies the implementation, allowing us to look up each set of overrides in as a cluster/VM composite key, returning just the involved structure, versus having to consolidate all three and return them all at once. It also facilitates granularity in that if someone wants to provide a DRS override but …

New resource: vsphere_drs_vm_override

---

vsphere/resource_vsphere_virtual_disk.go
vsphere/resource_vsphere_virtual_disk_test.go
website/docs/r/virtual_disk.html.markdown

This PR introduces the attribute to create the parent directories in the datastore when creating a `resource_vsphere_virtualdisk`. It uses the same logic seen in `resource_vsphere_file.go` with an extra check to ensure the directory is already created before creating the disk since the 'MakeDirectory' call does not return a task we can wait on.

Add attribute to create parent directories when creating a virtual disk

---

vsphere/helper_test.go
vsphere/internal/helper/structure/structure_helper.go
vsphere/provider.go
vsphere/resource_vsphere_compute_cluster_host_group.go
vsphere/resource_vsphere_compute_cluster_host_group_test.go
vsphere/resource_vsphere_compute_cluster_vm_group.go
website/docs/r/compute_cluster.html.markdown
website/docs/r/compute_cluster_host_group.html.markdown
website/docs/r/compute_cluster_vm_group.html.markdown
website/vsphere.erb

This is the other group resource, which manages hosts, and is mainly used in the vm/host affinity rules.
This sets the ground work for the cluster rules to be added now.

New resource: vsphere_compute_cluster_host_group

---

vendor/github.com/hashicorp/terraform/helper/resource/testing.go
vendor/github.com/hashicorp/terraform/helper/resource/testing_config.go
vendor/vendor.json
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

**Current Problem**
When creating a disk resource and attaching it to a VM resource the `terraform apply` operation shows this plan below (**notice the size set to zero**):
```
disk.2.attach:                                      "true"
disk.2.datastore_id:                                "datastore-1160"
disk.2.device_address:                              <computed>
disk.2.disk_mode:                                   "persistent"
disk.2.disk_sharing:                                "sharingNone"
disk.2.eagerly_scrub:                               "false"
disk.2.io_limit:                                    "-1"
disk.2.io_reservation:                              "0"
disk.2.io_share_count:                              "0"
disk.2.io_share_level:                              "normal" …
```

Remove size attribute for attached disks

---

website/docs/r/resource_pool.html.markdown

parent_resource_pool_id should reference to the resource_pool_id output of data.vsphere_compute_cluster and not to the id.

r/resource_pool: Correct docs

---

website/docs/r/virtual_machine.html.markdown

We require that the VM be powered off, but it was not documented.

r/virtual_machine: Document VM clone power req

---

vsphere/provider.go

The name of Go library for the VMware vSphere API is govmomi.

Fix typo in provider.go

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

Do not update the ResourceAllocation field for VirtualEthernetCards when
using < vSphere 6.0
Resolves #571

r/virtual_machine: Restrict ResourceAllocation pre 6.0

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

Only append config specs (cspecs) if they are not empty.

r/virtual_machine: Ignore empty controller specs

---

website/docs/r/distributed_virtual_switch.html.markdown
website/docs/r/virtual_disk.html.markdown
website/docs/r/virtual_machine.html.markdown
website/docs/r/virtual_machine_snapshot.html.markdown

This is causing some confusion with requests coming into certain
stakeholders in support.
"sub-resources" may be correct technically, as nested configuration
blocks within the schema are implemented via `schema.Resource`, and
`vsphere_virtual_machine` device configurations follow a complex,
resource-like lifecycle, in order to ensure the device has a graceful
lifetime within a VM configuration (especially important for disks).
However, externally, these relations are not very visible, and referring
to these constructs as anything else other than configuration blocks
just gets in the way.

docs: Remove "sub-resource" references from related docs

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

Return a slice of device config specs instead of a single spec. This matches what is returned by the ConfigSpec function and makes it unnecessary to check if the cspec is nil since the value returned by setSCSIBusSharing will only be nil if there is an error.

r/virtual_machine: Fix variable shadowing and type

---

vsphere/resource_vsphere_virtual_machine_test.go

Update disk names in virtual_machine tests to match changes in the source templates. This is needed due to changes to the test environment.

r/virtual_machine: Update disk names

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

The host attribute of CreateVM_Task is being ignored in vCenter 6.7.
Adding a host check and reloaction step to ensure that VMs land on
the correct host.

Relocate VMs after create

---

vsphere/virtual_machine_config_structure.go

r/virtual_machine: Handle empty LatencySensitivity

---

vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

Skip OS specific customization checks when `resource_pool_id` is not
set. This usually happens when the `resource_pool_id` comes from a new
resource that has not yet been created.
Resolves #533

r/virtual_machine: Skip OS specific customization check

---

vsphere/data_source_vsphere_vapp_container.go
vsphere/data_source_vsphere_vapp_container_test.go
vsphere/provider.go
website/docs/d/vapp_container.html.markdown

The previous changes were accidentally reverted. This is the same as #610.

d/vapp_container: Add vapp_container data source

---

vsphere/distributed_virtual_switch_structure.go
vsphere/helper_test.go
vsphere/host_network_system_helper.go
vsphere/resource_vsphere_compute_cluster_vm_dependency_rule.go
vsphere/resource_vsphere_compute_cluster_vm_host_rule.go
vsphere/resource_vsphere_host_virtual_switch.go
vsphere/resource_vsphere_host_virtual_switch_test.go
vsphere/resource_vsphere_resource_pool.go
website/docs/r/host_virtual_switch.html.markdown

This update adds import functionality on ```vsphere_host_virtual_switch ``` resource.

Vswitch import

---

vsphere/resource_vsphere_virtual_disk.go

On vSAN, an error is returned when attempting to create a directory that
already exists. If the error is an "already exists" error, it should be
ignored.
Fixes #633

r/virtual_disk: Ignore error when creating dir

---

vsphere/resource_vsphere_compute_cluster_host_group_test.go
vsphere/resource_vsphere_compute_cluster_test.go
vsphere/resource_vsphere_compute_cluster_vm_dependency_rule_test.go
vsphere/resource_vsphere_compute_cluster_vm_host_rule_test.go
vsphere/resource_vsphere_dpm_host_override_test.go
vsphere/resource_vsphere_virtual_machine_test.go

Use dynamic disk names instead of hard coded ones for disk checks, and change host resources to match current testing environment.

r/virtual_machine: Adjust acceptance tests

---

vsphere/virtual_machine_config_structure.go

Keep logging during oldconfig expansion to provide a more complete view
of process for troubleshooting.

r/virtual_machine: Continue logging for oldconfig

---

vsphere/internal/helper/structure/structure_helper.go

Ignore nil interfaces when converting a slice of interfaces into a slice
of strings. This becomes an issue when a list with an empty string is 
passed to SliceInterfacesToStrings.
Fixes #643

helper/structure: Handle nil interface

---

vsphere/virtual_machine_config_structure.go

Unlock the memory reservation from the allocation if the reservation is
lower than the allocation.
Fixes #672

r/virtual_machine: Unlock memory reservation

---

website/docs/r/virtual_machine.html.markdown

References to 'operating system' were spelled 'opearating'

Fix misspelling 'opearating' to 'operating'

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_guest_structure.go
website/docs/r/virtual_machine.html.markdown

There are two parts to this change:
- Add a new waiter that waits for guest.ipAddress to be populated. This waiter is controlled via the `wait_for_guest_ip_timeout` property that is disabled by default. This waiter is intended to be used in place of the `wait_for_guest_net_timeout` waiter.
- Regardless of which waiter is enabled, the code that populates `default_ip_address` and `guest_ip_addresses` will first look at `guest.net` and `guest.ipStack` to find the IP address. Only if no IP address is found via that method will it then fall back to looking at the `guest.ipAddress` property instead.
The VMs I am creating unfortunately have an older version of VM Tools that does not populate the `guest.net` or `guest.ipStack` properties. However, the VMs I am creating do populate the …

Add support for using guest.ipAddress for older versions of VM Tools

---

vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

This updates all vapp-properties examples and docs, getting rid of
deprecated coreos-cloudinit keys:
https://github.com/coreos/coreos-cloudinit/blob/v1.14.0/Documentation/vmware-guestinfo.md
Closes: https://github.com/terraform-providers/terraform-provider-vsphere/issues/725
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>

docs: update vapp-properties examples

---

website/docs/r/virtual_machine.html.markdown

`run_once_command_list` in the `vsphere_virtual_machine` resource has a 260 character limit.
Fixes #738

Document character limit on run_once_command_list

---

vsphere/provider_test.go
vsphere/resource_vsphere_file_test.go
vsphere/resource_vsphere_vapp_entity_test.go

Previously these tests would fail if the ENV variables aren't set, which is presumably not desirable, according to checks in all other test cases.

tests: Add missing ENV variable checks

---

vsphere/virtual_machine_config_structure.go

This PR resolves #394 by ignoring vApp attributes that have `UserConfigurable` set to `False`.

only use vApp properties that are UserConfigurable

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

Resolves #316 by allowing a blank network name. This occurs when cloning a template to another cluster where the distributed port group on the template does not exist.

Allow blank networkID

---

vsphere/internal/helper/structure/structure_helper.go
vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

Use NewValueKnown to check if value is empty because of interpolation not being available at diff time. Specifically to fix issues where CustomizeDiff function returns an error because values that are based on computed values from new resources appear empty during diff.
Fixes #778

r/virtual_machine: Ignore validation when interpolation not available

---

website/docs/r/virtual_machine.html.markdown

Properties section appears incorrect in Terraform v0.12.

Updated properties section of OVA to include an equals sign

---

vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go

In a sysprep file it is fairly common to include passwords as part of the setup.  Our particular use case is during the domain joining step, though specifying an administrator password is another common case.  It seems that Microsoft's [official guidance](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/wsim/hide-sensitive-data-in-an-answer-file) on "hiding" this sensitive data is simply base64 encoding it which obviously is not truly protecting this information.  The PR simply marks the field as sensitive so that any passwords in the file will not be revealed during the plan phase.

Mark windows_sysprep_text as sensitive

---

tf-vsphere-devrc.mk.example
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

The previous way of detecting if a VM belogs to a resource pool that is
inside a vApp would fail if there was an intermediate rp between the
vApp itself and the VM.
We're now checking the `ParentVApp` property of the Virtual Machine
instead of just looking up the Resource Pool it belongs to.

Change the way we detect if a VM is in a vApp

---

vsphere/internal/helper/hostsystem/host_system_helper.go
vsphere/provider.go
vsphere/resource_vsphere_host.go
vsphere/resource_vsphere_host_test.go
website/docs/r/host.html.markdown

This is a first draft of a resource that allows terraform users to add new ESXi hosts to a vsphere cluster and manage things like:
[x] connection status
[x] maintenance status
[x] lockdown mode
Once we settle on what it should look like we can work on adding more features.

Add vSphere host resource

---

vsphere/config.go
vsphere/datacenter_helper.go
vsphere/resource_vsphere_datacenter_test.go
vsphere/resource_vsphere_file.go
vsphere/resource_vsphere_file_test.go
vsphere/resource_vsphere_host.go
vsphere/resource_vsphere_virtual_disk.go
vsphere/resource_vsphere_virtual_disk_test.go

Maintenance mode functions expect timeout in minutes, but it was being passed in milliseconds.

r/host: Convert ApiDefaultTimeout to int

---

website/docs/r/host.html.markdown
website/vsphere.erb

Link to the resource's docs is missing from the index. Unless someone
knows the page exists they are will not be able to access it.

r/host: Fix sidebar links

---

vsphere/host_network_policy_structure.go

Sometimes govmomi will return a PortGroup spec where the failure
criteria property of the nic teaming policy can be nil.
When this happens we crash because the code doesn't check for this case.
Addresses the crash in #869

Check if portgroup failure criteria is nil

---

vsphere/provider.go
vsphere/resource_vsphere_vnic.go
vsphere/resource_vsphere_vnic_test.go
website/docs/r/vnic.html.markdown
website/vsphere.erb

This resource manages `vmk` interfaces on ESXi hosts. Using a
combination of this resource and `vsphere_host` a terraform user can
setup a cluster of esx hosts and configure vmotion on them.

Support for vNic resources

---

vsphere/internal/helper/network/network_helper.go

When trying to clone a machine and then adding/changing the network interface, the result is a `panic: reflect.Value.Addr of unaddressable value` in the govmomi xml decoder. This is partially solved in this provider by only returning a limited scope.
I have not been able to reproduce this with https://github.com/vmware/govmomi/blob/master/examples/networks/main.go. 
It could be that this also solves #822 
```
2019-09-12T12:17:17.630+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: 2019/09/12 12:17:17 DEBUGGING: val=<nil>, pval=&{DvsNetworkRuleQualifier:{DynamicData:{} Key:30_31_ _61305613_12142737_30325633} TypeOfSystemTraffic:0xc000b5dba0}, valtype=types.BaseDvsNetworkRuleQualifier
2019-09-12T12:17:17.672+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: panic: …
```

NetworkHelper: Limit the returned scope as workaround for govmomi reflection issue

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go

ResourceReductionToToleratePercent should be set to ha_admission_control_performance_tolerance
compute cluster delete should set HA to OFF for Admission Control Failover host policy before the delete

fix for compute cluster delete when Admission Policy is set to FailoverHost issue #891

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

When cloning virtual machines it is possible to define additional disks
to be created. If a datastore is not defined either for the disk or for
the virtual machine then the creation of the additional virtual machines
will fail.
This change introduces a fallback where if a datastore is not set we
pick the first datastore found that is associated with the virtual
machine.

Pick default datastore for extra disks

---

vsphere/resource_vsphere_virtual_machine_snapshot.go

Currently, if a snapshot is manually deleted, the following error will happen:
```
Error: Error while finding the Snapshot :no snapshots for this VM
```
The `strings.Contains` being used to compare is case sensitive, so the comparison is never `true`

fix typo on no snapshots error check

---

vsphere/tags_helper.go

Pointers to Go range variables assigned inside a range end up pointing
to the last element iterated to. See
https://medium.com/golangspec/range-clause-and-the-address-of-iteration-variable-b1796885d2b7.
I don't know if the category slice is sorted alphabetically or
otherwise, but if your category is not the last in the list, you will
get an unexpected result.
Fixes #909

Return correct tag or tag category for given name

---

vsphere/resource_vsphere_compute_cluster_test.go

ha_admission_control_performance_tolerance check added to failover host configuration and now the test is failing.
the reason behind that is govmomi library where:
`ResourceReductionToToleratePercent int32 `xml:"resourceReductionToToleratePercent,omitempty"``
that means that resourceReductionToToleratePercent will be dropped from the SOAP payload if it is 0.
I opened the issue and pull request was created https://github.com/vmware/govmomi/pull/1687
the problem is that pull request changes `ResourceReductionToToleratePercent` declaration to:
`ResourceReductionToToleratePercent *int32 xml:"resourceReductionToToleratePercent,omitempty"`
that will affect the code of the provider.

ha_admission_control_performance_tolerance failed to set to 0.

---

vsphere/resource_vsphere_virtual_machine.go

If the guest OS mounts the virtual cdrom device then vsphere expects
someone to confirm that it should be "unlocked" first.
This is done via a VirtualMachineQuestionInfo object that we need to
find and then respond to via the "AnswerVM" method. We start a goroutine
right before we attempt any VM modifications and signal we're done right
after we're done. If a known question appears in the mean time, we will
send the appropriate answer.

Unmount ISO when switching CDROM backends for a VM

---

vsphere/resource_vsphere_virtual_machine.go

If a user updates the resource pool ID and the owner of the destination
resource pool is on a different cluster or a different standalone host
then we should leave the vMotion logic to handle this instead of calling
MoveIntoResourcePool().

Migrate VM instead  if destination is another host

---

.circleci/config.yml
GNUmakefile
scripts/test_runner.sh

- Unfortunately due to the current effect the test have on the lab
we're stuck with having to revert everytime we fail and try again. We
will have to write a script that ingests the test output and reports
actual failures or potential "random" failures.
- Minor change to the Makefile to allow for alternative config file

Test pipeline changes

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go
website/docs/r/virtual_machine.html.markdown

* Correctly parse CIDR networks included in the `ignored_guest_ips` list, allowing entire arbitrary IP ranges to be ignored.
* Compare guest IP addresses to `ignored_guest_ips` using `net.IP.Equal()` rather than raw string comparison, enhancing support for variations in IPv6 representation.

Extend ignored_guest_ips to support CIDR networks

---

vsphere/resource_vsphere_vapp_container.go
vsphere/resource_vsphere_vapp_container_test.go

- Child vApp containers do not need folders
- Child vApp containers do not have parent Folders set either, which unless
checked will cause a panic when importing.
- Add test case for importing child vApp containers.
Fixes #939

Fix handling of child vApp containers

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

If the path to an attached disk is interpolated, then sometimes we may
end up in a situation where the diff for the VM having the disks runs
before the disk itself has been processed. In this case since the path
has no value we throw an error.
This changes the behaviour so we check if the path has been calculated
before we consider it final or not.

Do not throw error when disk path is not known yet

---

go.mod
go.sum
vsphere/resource_vsphere_compute_cluster_test.go

Recreating PR #899 since it was reverted. We will need to wait until govmomi releases a stable version containing https://github.com/vmware/govmomi/pull/1687.

ha_admission_control_performance_tolerance check added to failover host configuration and now test is failing

---

vsphere/resource_vsphere_virtual_disk.go

`vmdk_path` must end with a '.vmdk' suffix or the created disks will not
work properly or be able to be found with the `Read` function. Adding a
validate function to provide a better user experience when the suffix is
left off.
Fixes #926

b/virtual_disk: enforce vmdk suffix

---

vsphere/resource_vsphere_virtual_machine.go

If the datastoreID is set in the RelocateSpec, but no disks are set, vSphere will return an error.

Do not set the datastoreID in RelocateSpec when datastore_cluster is set

---

vsphere/internal/helper/envbrowse/environment_browser_helper.go

Optimize OS family query
Switching from QueryConfigOption to QueryConfigOptionEx to query the specific descriptor,
rather than returning all supported descriptors.
Against vCenter 6.7U3, this reduces the response from ~600K to ~10K
This change will also simplify the vcsim implementation of this query (Issue #940)

Optimize OS family query

---

vsphere/internal/helper/viapi/vim_helper.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go

There is a conflict right now between the way the vsphere provider
builds VMs and how vSphere expects VMs that are part of a vApp to
behave, especially in the way things are powered on.
vApps expect that the VMs will be built but not powered on, because it
handles powering on the VM on its own in a specific order. On the other
hand the provider will build the VM and instantly power it on regardless
of where it belongs.
The result of this conflict is that vsphere will not allow any VM to
power on until all VMs in the vApp are ready to be powered on. So for
example while cloning two VMs in the same vApp, we are only allowed to
power on the first VM once both of them are done cloning. Any attempts
to power on a VM earlier result in a "InvalidState" response.
This commit introduces a …

Add configurable timeout for VM PowerOn operations

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

Fixes this bug: https://github.com/terraform-providers/terraform-provider-vsphere/issues/875
Problem is that if VM had orphaned disk saved in state file and same VM gets _another_ orphaned disk after that, Terraform will add new disk with the same orpahed_disk_0 label. This breaks the run because label names must be unique according to virtual_machine_disk_subresource.go
The fix itself simply detects orphaned disks among already existing resources and skips them, so that they are re-added to state file as orphaned disks again, thus making this provider iterate over _compelte_ list of orphaned disks and not only newly discovered ones.

Fix working with orphaned devices

---

vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go
vsphere/internal/helper/network/network_helper.go

handling cases of reading network port groups with same name by providing an optional param distributed port switch id to differentiate them.
https://github.com/terraform-providers/terraform-provider-vsphere/issues/925

handling cases of network port groups with same name 

---

website/docs/d/network.html.markdown

I have missed the documentation change in the pull request https://github.com/terraform-providers/terraform-provider-vsphere/pull/1001.
Adding the distributed_vistual_switch_uuid argument in the vsphere_netwrork data source in the HTML file

Adding virtual_switch_uuid arguments in the documentation for vsphere_network datasource

---

.github/workflows/labeled_issues.yml

Adds a job to move crash reports to current sprint focus

Add job to move crashes to current work list

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

Fix disk controller sorting

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

#1032 didn't take all cases into account. This change does.

Only compare bus number if different

---

.travis.yml

Switching from Go 1.11.x to 1.13.x

Use Go 1.13.x for Travis

---

website/docs/r/virtual_machine.html.markdown

I think it would be more correct to mention `sysprep.xml` as file name, as this is the default name from Windows Vista onwards:
https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-1330EEEE-12D1-42FE-B647-E731A01B1A7D.html
Using the old `sysprep.inf` could be misleading for some folks IMHO.

Replace sysprep.inf with sysprep.xml in docs

---

vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go

Not sure if you can agree, but I would feel more comfortable having the `product_key` parameter hidden in the plan.
Whether it should be considered sensitive or not could be questionable, but since there are no side-effects I would mark it as such.
Thanks for your review :wink:

Mark product_key as sensitive

---

vsphere/virtual_machine_config_structure.go

vSphere v7.0 has added a new hardware version, so the max version needs to be increased to support it.

Increase max hw version for vSphere 7.0

---

vsphere/virtual_machine_config_structure.go

It seems that the vSphere API will return an error when some older hardware versions are included in the UpdateSpec. The hardware version is only needed in the CreateSpec, but the two share the Flatten function. Rather than splitting that or making the Flatten function determine if it is a Create or Update spec, I am removing the extre version info when updating.

Only include hardware version in CreateSpecs

---

.github/workflows/add_labeled_issues_to_project.yml

Crashes were being moved to the triage board, but should be moved to the working board to be dealt with sooner.

Update column to which crashes are moved

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

There are reports of `nil` entries being included in the NIC list. I have not been able to reproduce the issue, but this should prevent it from being an issue.
Fixes #1059

r/vm: Skip unexpected NIC entries

---

vsphere/config.go

Only store rest session information if `session_persistence` is set.
Fixes #1076

Respect `session_persistence` for rest sessions

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_host.go
website/docs/r/compute_cluster.html.markdown
website/docs/r/host.html.markdown

Adding management arguments to `hosts` and `compute_clusters` so that the two do not conflict when both resources are in use.

Specify cluster membership management

---

vsphere/resource_vsphere_virtual_machine.go

Moving validation out of CustomizeDiff so that OVF deployment is compatible with having computed values at planning.

Move ovf argument validation out of CustomizeDiff

---

vsphere/resource_vsphere_host.go

Changing from putting hosts into maintenance mode and then removing them to disconnecting hosts and then removing them. This allows host resources to be deleted even if they have imported VMs running on them still.

Disconnect on delete instead of maintenance mode

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

Adding VApp properties when deploying a vm from OVF template
No
Yes, https://gist.github.com/sumitAgrawal007/b04d756bb9d916a67a3701af9904238d
https://github.com/terraform-providers/terraform-provider-vsphere/issues/1074

Adding vapp properties while OVF deployment

---

vsphere/resource_vsphere_custom_attribute.go

Fix the error message currently displaying cryptic characters in error messages instead of the actual category id
Currently when the category id can not be found, it displays a error message like this:
This is very confusing and doesnt look like its actually just a problem with a missing resource.
The cause for this lies in %q it leads to a non-human-readable output. Using %d fixes the problem, cause it displays as a literal number.
n/a

Fix id in error message when category cant be load

---

go.mod
go.sum
vsphere/helper_test.go
vsphere/internal/helper/spbm/spbm_helper.go
vsphere/internal/virtualdevice/virtual_machine_tag_rules_subresource.go
vsphere/provider.go
vsphere/resource_vsphere_tag_category.go
vsphere/resource_vsphere_vm_storage_policy.go
vsphere/resource_vsphere_vm_storage_policy_test.go
website/docs/r/vm_storage_policy.html.markdown
website/vsphere.erb

Adding VM_storage_policy_profile resource
CRUD operations for tag based placement policy rules
yes
VM_storage_policy_profile acceptance test: https://gist.github.com/sumitAgrawal007/9db3c782a3a4af268f51ce0f9cdb30d5
tag category acceptance test
https://gist.github.com/sumitAgrawal007/91ff0b3fe9af063de0deca85242f51cd
https://github.com/terraform-providers/terraform-provider-vsphere/issues/993

Adding vm_storage_policy_profile resource for tag based placement policy management

---

vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/r/virtual_machine.html.markdown

Adding feature to deploy a VM from OVA template
https://gist.github.com/sumitAgrawal007/42e1f54fe6ed9a91466b1b14aa81a554

Adding ova deployment feature

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_config_structure.go

Switch `guest_id` to `computed`, and set the default in `CustomizeDiff` in order to support leaving the field empty for Content Library template sources.
Fixes #1119

r/vm: Set guest_id before customization

---

vsphere/data_source_vsphere_host_thumbprint.go
vsphere/data_source_vsphere_host_thumbprint_test.go
vsphere/internal/helper/testhelper/testing.go
vsphere/provider.go
website/docs/d/host_thumbprint.html.markdown
website/vsphere.erb

Needed for adding new hosts when the thumbprint is not known ahead of time.

Add host_thumbprint data source

---

vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
vsphere/resource_vsphere_virtual_disk.go
vsphere/resource_vsphere_virtual_disk_test.go
website/docs/r/virtual_disk.html.markdown

Add function to import a vsphere_virtual_disk resource via `terraform import`.
https://gist.github.com/skevir/1a5df485691d979a2e26b489a393e93f (only ran TestAccResourceVSphereVirtualDisk tests)
https://github.com/hashicorp/terraform-provider-vsphere/issues/1113

Add import for vsphere_virtual_disk

---

vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
website/docs/r/virtual_machine.html.markdown

This PR allows performing a linked clone from a template by using the "moveAllDiskBackingAndAllowSharing" option. When performing a clone, the source virtual machine is checked if it's marked as a template. If so, then it sets the option and proceeds with the clone. If it is not marked as a template, then it will proceed with the original logic which validates that a snapshot exists.
The documentation was updated to remove reference to the snapshot constraint.
There were no tests for the cloning functionality, and so I wasn't sure how to proceed here.
This closes issue #1156.

Allow performing a linked-clone from a template without requiring snapshots

---

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go

When updating a "vsphere_virtual_machine" resource, the logic for `SetHardwareVersion` is not fetching the version correctly. This results in the hardware version always being updated which prevents any updates of the resource until the machine is powered off.
This is done by implementing the `ConfigOptions` function which makes a `QueryConfigOption` request, and then refactoring the implementation of `SetHardwareVersion` to compare with integers instead of having to convert the summary's attribute to a string.
There were no tests for cloning, so I wasn't sure how to proceed.
This closes issue #1149.

Fixed SetHardwareOptions to fetch the hardware version from QueryConfigOption instead of the default properties

---

vsphere/resource_vsphere_vnic.go

After importing a `vsphere_vnic`, I noticed couple of things in the subsequent `terraform plan` indicating some sort of 'incomplete' import:
- the `host` field was showing as being added, even though the value for `host` is technically in the `id` used for importing (note that this causes a replacement of the resource which was kind of a show stopper for trying to import the nic)
- the same behavior was observed for both the `netstack` and `ipv4` fields and I suspect it would be the same for `ipv6`, although in my case, the vnic I was importing didn't have any IPv6 settings configured.
Below is an example of the observed behavior :
The `vsphere_vnic` config:
```hcl
resource "vsphere_vnic" "management" {
host      = "host-4109"
portgroup = "Management Network"
netstack  = …
```

Fix vnic import

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

In some environments the disk provisioning type can change silently when cloning due to vSphere storage policies.  Thin provisioning cannot be managed by Terraform and therefore should not attempt to set these value after cloning.
Error message:
```
ERROR                                              
ERROR Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: cannot change the value of "thin_provisioned" - (old: false new: true) 
ERROR                                              
ERROR   on ../../../../../tmp/openshift-install-068412821/master/main.tf line 1, in resource "vsphere_virtual_machine" "vm": 
ERROR    1: resource "vsphere_virtual_machine" "vm" { 
ERROR                                              
```
Attempting to ignore these changes …

Ignore thin_provisioned and eagerly_scrub during DiskPostCloneOperation

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

Skip SCSI controller check when empty

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

There can be fewer controllers than expected when deploying from content library or ovf. Setting the controller type to unknown will block further use without crashing.

Set SCSI controller type to unknown when nil

---

vsphere/internal/helper/ovfdeploy/ovf_helper.go

Small OVFs result in the status chan being closed before 'finished' signal can be sent.

Keep progress channel open

---

vsphere/host_network_policy_structure.go

Ignore nil objects in host network

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/virtual_machine_config_structure.go

Now that `storage_policy_id` is managed by Terraform, datastores with default storage policies will result in the provider trying to continually change it, even if no policy is specified.
Fixes #995

Make storage_policy_id computed.

---

vsphere/data_source_vsphere_content_library_item.go
website/docs/d/content_library_item.html.markdown
website/vsphere.erb

Adding `type` to `content_library_item` so that different logic can be used based on the `type`.
Based on #1183. Will be size/S when that is merged.
#1126

Add type to content library item data source

---

vsphere/distributed_port_group_structure.go
vsphere/distributed_virtual_port_setting_structure.go
vsphere/distributed_virtual_switch_structure.go

LACP policy setting is allowed only at the virtual switch level and not in the port level.
Fixing the code so that the lacp changes are done only for virtual switch resource.
```release-note
Fixing distributed port group resource so that lacp change are done only for virtual switch and not for port group.
```

Fixing port group resource to enable LACP only in virtual switch, not in port group.

---

README.md
vsphere/resource_vsphere_distributed_port_group.go
website/docs/r/distributed_port_group.html.markdown

Import distributed port group using Managed object ID.
The import function for distributed port groups takes the path as argument, but there could exist
two port groups with same name and same path which creates ambiguity.
This is to fix the import function using Moid which is unique.
```release-note
Changing import function for distributed port group resource using managed object Id instead of path as argument.
...
```

Import ditributed port group using moid

---

vsphere/internal/helper/datacenter/datacenter_helper.go
vsphere/resource_vsphere_datastore_cluster.go

After importing a `vsphere_datastore_cluster`, the subsequent `terraform plan` showed the imported resource marked for 'replacement'. This was because one of the required fields `datacenter_id` was not being set as part of the `import`. Below is an example of this issue:
`vsphere_datastore_cluster` resource config:
```terraform
resource "vsphere_datastore_cluster" "ds_cluster1" {
name                  = "datastore-cluster1"
datacenter_id         = "datacenter-2"
sdrs_enabled          = true
sdrs_automation_level = "manual"
sdrs_space_utilization_threshold       = 85
sdrs_free_space_utilization_difference = 30
sdrs_advanced_options = {
"IgnoreAffinityRulesForMaintenance" = "1"
}
sdrs_io_load_balance_enabled = false
}
```
After `import`ing the resource, the subsequent `plan` showed the …

r/datastore_cluster: Fix missing field in import

---

vsphere/host_port_group_structure.go
vsphere/resource_vsphere_host_port_group.go
website/docs/r/host_port_group.html.markdown
website/docs/r/vnic.html.markdown

Adds support for importing `vsphere_host_port_group`.
**Bonus**: Fix typo in the `vnic` import documentation.
```release-note
`resource/host_port_group`: Add support for importing host port group.
```

r/host_port_group: Add support for importing

---

vsphere/distributed_virtual_port_setting_structure.go
vsphere/distributed_virtual_switch_structure.go
website/docs/r/distributed_virtual_switch.html.markdown

**This is a work in progress**
As set out in #1145, I would like to help improve the functionality of the networking resources in this library. If these are already being worked on or there's a reason why I shouldn't bother with a particular thing, let me know. Equally I'm happy to work with others and would like feedback as this is my first contribution to a Terraform provider.
Specifically:
- PVLAN mappings
- VSPAN (port mirroring) sessions
- Standalone resources so that pvlan mappings and vspan sessions can be configured outside of the main DVS resource. This would be similar to the AWS provider's route_table/route and security_group/security_group_rule. 
Maybes:
- Filter policies
- Support LACP Groups for DVS (might help with #919)
- Network data resources split (as suggested in …

Networking additions [WIP]

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_config_structure.go

Allow more config options to be changed from OVF

---

vsphere/resource_vsphere_virtual_machine.go

Change default OS method on bare VMs

---

vsphere/resource_vsphere_virtual_machine.go

Convert folder path to MOID

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

Alloow `datastore_id` to be computed since it is not required for ovf deployment, and then run VM read at the end of creation.

Fix ova deploy and tests

---

website/docs/d/dynamic.html.markdown

There was a typo, and now there is none.
```release-note
NONE
```

Fixed a typo in the docs

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine.go

When no disks are specified in the config, they should be added after deploying an ova.

Support for no disks in config

---

vsphere/config.go
vsphere/internal/helper/storagepod/storage_pod_helper.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/provider.go
vsphere/resource_vsphere_virtual_machine.go
website/docs/index.html.markdown

Sometimes creating new VMs can take a while, especially when building
bare VMs that have their OS provisioned by an external system. If that
takes more than 5 minutes then the VM creation fails with a timeout.
For this reason we are adding an `api_timeout` parameter in the
provider's configuration schema that will allow users to override that
timeout. The default value remains five (5) minutes.

Make API timeout configurable when building VMs

---

vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go

Ensures a network mask's length will never exceed 32 for IPv4 and 128
for IPv6.
Fixes #1316

Add validation for netmask length

---

vsphere/virtual_machine_config_structure.go

Due to the way maps behave in goland we ended up removing data from the
original map holding the vapp properties. The consequence was that if
expandVAppConfig was called more than once, we'd end up effectively
emptying the vapp properties map.
Fixes #1242.

Fix missing vapp properties

---

vsphere/resource_vsphere_entity_permissions.go
website/docs/r/vsphere_entity_permissions.html.markdown

The permissions objects received from server are not necessarily sorted on username/groupname. We are asking the users to keep it sorted in the TF file and this PR sorts the received objects alphabetically so that terraform doesn't show a diff while refreshing. 
```release-note
- resource/vsphere_entity_permissions: Sorting permission objects on username/groupname before storing. (#1311)
```
Closes #1293

Sorting permissions object on username/group name before storing.

---

vsphere/data_source_vsphere_ovf_vm_template.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
vsphere/provider.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/d/ovf_vm_template.html.markdown
website/docs/r/virtual_machine.html.markdown
website/vsphere.erb

The provider expects to be the only entity altering the settings of a
virtual machine, which is not the case when deploying via OVF.
The easy way out of this would be to make all attributes `Computed`
which would make terraform to blidnly accept all changes into the state.
Unfortunately this would also mean a loss of drift detection.
The middle ground is to create a new datasource that extracts all the
settings from the OVF template and expose it as outputs, so we can then
pass it as attribute values to the `vsphere_virtual_machine` resource.
The ideal solution would be to create a whole new resource to deal
exclusively with OVF-built virtual machines but it would be a breaking
change since users are already using the ovf subresource in
`vsphere_virtual_machine`. This could potentially go …

OVF deployment options support 

---

vsphere/virtual_machine_config_structure.go

Hardware version goes up to 19 since vsphere 7.0.2
(https://kb.vmware.com/s/article/1003746)
Closes #1389.

Update max hardware version

---

CHANGELOG.md
vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
vsphere/internal/helper/hostsystem/host_system_helper.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_host.go

A compilation issue on 32bit architectures uncovered a logic issue.

Change the way we set the timeout for maintenance mode

---

vsphere/internal/helper/ovfdeploy/ovf_helper.go

The provider may crash if a call to `ovfManager.CreateImportSpec` fails
with an error, because we missed the error check.
Fixes #1396

Fix crash when creating an OVF import

---

vsphere/resource_vsphere_vnic.go

Change default value to 'defaultTcpipStack' as the 'default' value does not exist
The test uses the correct value to test, which is why this probably went unnoticed.
The current test already is valid, however it overwrites the default value and as such this has gone unnoticed.
No, tests need a test vsphere cluster which I currently do not have available. However, this makes the code work as specified in the documentation: 
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/vnic
netstack - (Optional) TCP/IP stack setting for this interface. Possible values are 'defaultTcpipStack', 'vmotion', 'vSphereProvisioning'. Changing this will force the creation of a new interface since it's not possible to change the stack once it gets created. (Default: …

Change vnic netstack property default value to 'defaultTcpipStack' as the 'default' value does not exist

---

vsphere/internal/helper/structure/structure_helper.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource_test.go

* Fix the error `Invalid operation for device '0'` when cloning a virtual
machine template with a disk whose size is not an multiple of 1024^3
bytes, by ensuring that the calculated disk capacity is rounded up
rather than down.
The vsphere_virtual_machine data source calculates and stores disk size in integer GiB. Unfortunately, without this patch, the calculation always rounds the size down. As a result, if the vsphere_virtual_machine resource is used to clone a template with a non-integer GiB disk, it tries to shrink the disk to the calculated, rounded-down size, resulting in the opaque error `Invalid operation for device '0'`.
This PR resolves the issue by ensuring that the calculated size is always rounded up rather than down, so that, for example, a Packer-generated template with …

Fix calculation of diskCapacityInGiB by rounding up

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

Virtualization Based Security (VBS) is an option for Windows VMs that enables a security feature that is part of any security baseline for Windows (DoD/DISA, CISecurity, Microsoft). VBS is in turn contingent on another unsupported (by the provider) option, I/O MMU. 
In this PR, VBS and I/O MMU are implemented as 
```hcl
resource "vsphere_virtual_machine" "cloned_virtual_machine" {
...
vvtd_enabled = true
vbs_enabled = true
...
}
```
They target the api-flags _vvtdEnabled_ (I/O MMU) and _vbsEnabled_ (VBS) respectively.
The [VMware vSphere API reference's documentation of the Data Object VirtualMachineFlagInfo(vim.vm.FlagInfo)](https://vdc-download.vmware.com/vmwb-repository/dcr-public/3325c370-b58c-4799-99ff-58ae3baac1bd/45789cc5-aba1-48bc-a320-5e35142b50af/doc/vim.vm.FlagInfo.html) states …

Enabling VBS (vbsEnabled) and I/O MMU (vvtdEnabled)

---

vsphere/virtual_machine_config_structure.go

This PR fixes an issue reported in https://github.com/hashicorp/terraform-provider-vsphere/issues/1266. 
When a Virtual Machine is imported, and then a plan/apply is run without any changes to the template, the VM is started after apply. This started happening in **v1.17.4** and is still present in the latest provider.  This appears to be a side effect from a different fix https://github.com/hashicorp/terraform-provider-vsphere/pull/1055

Fix compare for VM Config spec change

---

vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
vsphere/virtual_machine_config_structure.go

This adds a new option under `ovf_deploy` named `enable_hidden_properties`.  This allows vApp properties that are marked with `userConfigurable=false` to be set. The most obvious use case for this functionality is directly deploying the vCenter Server Appliance OVA without using the installer.  The setting defaults to `false` which preserves the existing behavior.
The name is based off the name for an advanced option to `ovftool`.
```
$ ovftool --help debug | grep -A3 enableHidden 
--X:enableHiddenProperties          : Enable source properties that are 
marked as ovf:userConfigurable=false, 
OVF Tool will set the value to true. 
The default is false
```
* #394 
* https://www.virtuallyghetto.com/2016/10/how-to-deploy-the-vcenter-server-appliance-vcsa-6-5-running-on-vmware-fusion-workstation …

Allow vApp userConfigurable=false properties to be configured

---

.github/labeler-issue-triage.yml
.github/labeler-pull-request-triage.yml
.github/workflows/issue-comment-created.yml
.github/workflows/issue-opened.yml
.github/workflows/lock.yml
.github/workflows/pull-request.yml
.hashibot.hcl

GitHub HashiBot is being deprecated and this replaces behaviors with equivalent workflows in GitHub Actions. The `pull_request_size_labeler` behavior will be handled one an upstream enhancement is merged (or if we decide to use a fork with the change). Migrating the `release_commenter` behavior is to be determined.
N/A (hashibot configuration)
```release-note
NONE
```
Internal.

Migrate most GitHub HashiBot behaviors to GitHub Actions

---

vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

Validation checks in the `CustomizeDiff()` function were causing import issues. Since there was no effect to the actual diff I moved the checks back to the create/update path.

Fix cdrom import issues

---

vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

Adds the ability to get a new option for syncing time which was introduced in vSphere 7 U1. IMO the name of the field is a bit miss leading, so if there any suggestions for a better name, let me know.
This new options `sync_time_with_host_allowed` determines if VMware tools should periodically sync time with the host. Before vSphere 7 U1, there was only one option `sync_time_with_host` which by default turned on periodic syncs. The vSphere 7 U1 and above, this option can be separately set. The following KB article explains it much better https://kb.vmware.com/s/article/1189.
Here is the options in the UI before vSphere 7 U1:
And here is the same options in the UI after vSphere 7 U1:
While testing, I have noticed that on vSphere 7 U1, just setting `sync_time_with_host` isn't enough for any …

Add new option for syncing time on vSphere 7 U1 and above

---

vsphere/resource_vsphere_compute_cluster.go

Change the type of `vsan_disk_group` from `typelist` to `typeset`. When it is a list, the order of it is random every time `terraform plan` is called and causes a change in the vSAN disk groups, resulting in disks being deleted and re-added into the disk group every time you run `terraform apply`. This issue has already been raised here: https://github.com/hashicorp/terraform-provider-vsphere/issues/1205.
```release-note
`resource/compute_cluster` - `vsan_disk_group` is now a set and the order will be preserved between `terraform` runs
```
* https://github.com/hashicorp/terraform-provider-vsphere/issues/1205.

`vsan_disk_group` should be of type `TypeSet`

---

vsphere/data_source_vsphere_ovf_vm_template.go
vsphere/virtual_machine_config_structure.go
website/docs/d/virtual_machine.html.markdown
website/docs/r/virtual_machine.html.markdown

EFI firmware should be lowercase.
See `vendor/github.com/vmware/govmomi/vim25/types/enum.go`
```
const (
GuestOsDescriptorFirmwareTypeBios = GuestOsDescriptorFirmwareType("bios")
GuestOsDescriptorFirmwareTypeEfi  = GuestOsDescriptorFirmwareType("efi")
)
```
N/A
N/A
```release-note
NONE
```

EFI firmware should be lowercase

---

.github/labeler-pull-request-triage.yml
.github/workflows/issue-comment-created.yml
.github/workflows/issue-opened.yml
.github/workflows/lock.yml

This pull request addresses some issues and gaps with the projects use of GitHub Actions:
* `.github/workflows/lock.yml` : 
Updates to `dessant/lock-threads@v3` as also used by `terraform-provider-aws`
* `.github/workflows/issue-comment-created.yml`: 
Updates label from `waiting-reply` to `waiting-response` due to failing GitHub Actions.  `waiting-response` is the correct label used in the project issues.
* `.github/workflows/issue-opened.yml`:
Updates to `github/issue-labeler@v2.4` since the use of `github/issue-labeler@v2` is failing since it does not exist. (Also used by `terraform-provider-aws` project.)
* `.github/labeler-pull-request-triage.yml`
Updates the settings for the pull request labeler to apply the appropriate labels to a pull request based on the files changed.
Release …

Update settings for GitHub Actions

---

vsphere/internal/helper/spbm/spbm_helper.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine.go

This PR will address #1033 issue for ESXi as storage policy related APIs are supported only for vCenter.
This will also address the following error for ESXi related to storage policy for virtual disks:
Error: disk.0: this operation is only supported on vCenter: RESOURCE (1625), ACTION (PolicyIDByVirtualDisk)
This is tested with Terraform 0.13.3 version.
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
local_file.meta-data[0]: Refreshing state... [id=531754ffcbea5c01e45fcf0cc40be37aeaa34rte]
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the …

Address PolicyIDByVirtualMachine and PolicyIDByVirtualDisk errors when deploying VM on ESXi.

---

vsphere/data_source_vsphere_virtual_machine.go
website/docs/d/virtual_machine.html.markdown

This field was failing to set silently, caught in acceptance tests.
```
$ make testacc TESTARGS='-run=TestAccDataSourceVSphereVirtualMachine_'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereVirtualMachine_ -timeout 240m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
=== RUN   TestAccDataSourceVSphereVirtualMachine_basic
--- PASS: TestAccDataSourceVSphereVirtualMachine_basic (30.22s)
=== RUN   TestAccDataSourceVSphereVirtualMachine_noDatacenterAndAbsolutePath
--- PASS: TestAccDataSourceVSphereVirtualMachine_noDatacenterAndAbsolutePath (29.57s)
PASS
```
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/ma …

Fix silent failure on vm datasource

---

vsphere/resource_vsphere_virtual_machine.go

This change removes the conditional logic whereby if the datastore is known, that value is used. In some cases the previously obtained datastore value is incorrect due to an immediate vmotion event that occurs between the initial clone and the post update operations.
This issue was observed in production and has been resistant to reproduction due to the numerous factors involved in inducing an immediate vmotion fast enough.
```release-note
Don't assume the datastore is the same between create and post updates
```

force reconfigure due to race condition

---

.github/workflows/lock.yml

Updates the GHA `dessant/lock-threads@v3` to use the v3.0.0 options for comments and inactive days, thus avoiding GHA warnings and missed locking of threads.
- issue-comment
- issue-inactive-days
- pr-comment
- pr-inactive-days
Reference: https://github.com/marketplace/actions/lock-threads for v3.0.0.
Issue observed in https://github.com/tenthirtyam/terraform-provider-vsphere/actions/runs/1585598160
cc @iBrandyJackson @appilon

Update GHA for issues/pull-request locking

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_ha_vm_override.go
website/docs/r/compute_cluster.html.markdown
website/docs/r/ha_vm_override.html.markdown

- Updates `ha_datastore_apd_response_delay` to the API default for `vmTerminateDelayForAPDSec`.
- Updates the `compute_cluster` resource documentation to seconds versus minutes for `ha_datastore_apd_response_delay`.
- Updates the `compute_cluster` resource documentation to use the same structure for describing time-based arguments .
```release-note
Updates `ha_datastore_apd_response_delay` in the `compute_cluster` resource to the API default (180) for `vmTerminateDelayForAPDSec`.
```
- Closes:  #1438
- Closes:  #1386 
- API: [vmTerminateDelayForAPDSec](https://developer.vmware.com/apis/361/doc/vim.cluster.VmComponentProtectionSettings.html#vmTerminateDelayForAPDSec)

Update `ha_datastore_apd_response_delay` defaults and docs

---

website/docs/d/virtual_machine.html.markdown

- Updates the existing example for the `vsphere_virtual_machine` data source.
- Adds a second example demonstrating the use of the full path in the `name` argument in the `vsphere_virtual_machine` data source.
- Minor context corrections.
```release-note
Updates of the examples for the `vsphere_virtual_machine` data source
```
Closes: #830

Update the examples for the `vsphere_virtual_machine` data source

---

website/docs/r/vapp_container.html.markdown

- Updates examples in the `vsphere_vapp_container` resource documentation to address issues reported in #1436.
- Simplifies examples and removes legacy interpolation syntax (pre-TF 0.12.14).
- Updates link to the latest VMware vSphere product documentation on vSphere vApps.
Closes:  #1436

Update `vsphere_vapp_container` resource documentation

---

vsphere/data_source_vsphere_ovf_vm_template.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_config_structure.go

- Updates the default GOS to `otherGuest64` from **invalid** `other-64`.
- Updates `guest_id` and `alternate_guest_name` to correctly mention `otherGuest` and `otherGuest64` - **not** `other` and `other-64`
- Also updates the descriptions in `virtual_machine_config_structure.go` with more inclusive/accurate terminology, cleaner structure, and correct component proper name.
```release-note
Updates the default GOS to `otherGuest64` from invalid `other-64`.
```
Closes: #1263
vSphere Web Services API: [Enum - VirtualMachineGuestOsIdentifier](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere …

Update default GOS to `otherGuest64` from `other-64`

---

website/docs/r/compute_cluster_vm_affinity_rule.html.markdown
website/docs/r/compute_cluster_vm_anti_affinity_rule.html.markdown

- Updates the existing example for both `compute_cluster_anti_affinity_rule` and `compute_cluster_affinity_rule` (and removes legacy interpolation) and updates content.
- Adds an additional example for more usage context for both `compute_cluster_anti_affinity_rule` and `compute_cluster_affinity_rule`.
```release-note
Update examples for both `compute_cluster_anti_affinity_rule` and `compute_cluster_affinity_rule`.
```
Closes:  #1393

Update examples for affinity/anti-affinity rule resources

---

website/docs/r/virtual_machine.html.markdown

Updates `virtual_machine.html.markdown` for the resource:
- Updated for content accuracy.
- Updated all examples to be more readable and complete.
- Included continuity between examples.
- Addressed concerns mentioned in:
- #1424
- #1425
- #1414
- #1356
- Added some clarify based on issues: (re: missing `scsi_type`)
- #1435
- #1406
```release-note
Update `vsphere_virtual_machine` resource documenation.
```
- Closes #1424
- Closes #1425
- Closes #1356
- Closes #1538
- Closes #1414

Update `virtual_machine.html.markdown` for the resource.

---

website/docs/r/custom_attribute.html.markdown

- Updates the example in the `vsphere_custom_attribute` resource docs to use the `tomap` function.
- Minor structure updates to the `vsphere_custom_attribute` resource docs.
- Updated vSphere documentation links from 6.5 to 7.0.
```release-note
Updates the example in the `vsphere_custom_attribute` resource docs to use the `tomap` function.
```
Resolves #1480

Update `vsphere_custom_attribute` resource docs

---

website/docs/d/storage_policy.html.markdown
website/docs/r/vm_storage_policy.html.markdown

Updates the storage policy documentation for both the resource and data source, which includes a more complete example usage for the resource that compliments the data source.
```release-note
Updates for the documentation for both the storage policy resource and data source.
```
Closes: #978

Update storage policy documentation

---

website/docs/d/distributed_virtual_switch.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown

- Clarifies the support for LBT - `loadbalance_loadbased`
- Corrects the name and acronym of the vSphere object (_vSphere Distributed Switch (VDS)_) in the resource and data source documentation.
- Additional updates to the resource and data source documentation for accuracy and quality improvements.
```release-note
Update docs for `vsphere_distributed_virtual_switch`
```
Resolves #981 - a `documentation` issue.
LBT / Load-based Teaming / Route based on physical NIC load.
```hcl
resource "vsphere_distributed_virtual_switch" "dvs" {
name           = "terraform-test-dvs"
datacenter_id  = data.vsphere_datacenter.datacenter.id
version        = "7.0.2"
teaming_policy = …
```

Update docs for `vsphere_distributed_virtual_switch`

---

vsphere/distributed_virtual_switch_helper.go
vsphere/distributed_virtual_switch_structure.go

Adds support for:
- vSphere 6.7 (`6.6.0`)
- vSphere 7.0 Update 3 (`7.0.3`)
Have run unit tests for added `6.6.0` and `7.0.3`, regression tests for existing versions, and negative tests for non-compliant dvs versions.
```release-note
Adds support for dvs versions `6.6.0` and `7.0.3`.
```
Resolves #1291

Add support for dvs versions `6.6.0` and `7.0.3`

---

website/docs/d/content_library_item.html.markdown

- Updates the `name` argument description for accuracy.
- Updates the documentation with the required `type` argument. 
- Updates the example usage to depict each `type`.
- Minor formatting and context updates for accuracy.
```release-note
- Updates the `content_library_item` data source documentation with the required `type` argument. 
- Updates the `content_library_item` data source documentation example usage to depict each `type`.
```
- Closes #1340 -  `name` argument description error.
- Closes #1245 - documentation gap.

Update `content_library_item` data source docs 

---

vendor/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go
website/docs/d/dynamic.html.markdown
website/docs/d/resource_pool.html.markdown
website/docs/index.html.markdown
website/docs/r/compute_cluster.html.markdown
website/docs/r/datastore_cluster.html.markdown
website/docs/r/distributed_port_group.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown
website/docs/r/dpm_host_override.html.markdown
website/docs/r/drs_vm_override.html.markdown
website/docs/r/host_port_group.html.markdown
website/docs/r/host_virtual_switch.html.markdown
website/docs/r/resource_pool.html.markdown
website/docs/r/storage_drs_vm_override.html.markdown
website/docs/r/tag.html.markdown
website/docs/r/tag_category.html.markdown
website/docs/r/vapp_entity.html.markdown
website/docs/r/virtual_disk.html.markdown
website/docs/r/virtual_machine.html.markdown
website/docs/r/virtual_machine_snapshot.html.markdown
website/docs/r/vsphere_entity_permissions.html.markdown

Per the VMware [Product Lifecycle Matrix](https://lifecycle.vmware.com), both vSphere 6.5 and 6.7 are slated for End of General Support on 2022-10-15. 
This pull request updates links across the documentation to the latest release supported by the provider, vSphere 7.0 ahead of this date. 
> The README.md will **still note** that vSphere 6.5 and later are supported.
- Updates all documentation links from vSphere 6.5 to 7.0.
- Updates all links from code.vmware.com to developer.vmware.com.
- Updates all vdc-download.vmware.com links from vSphere 6.5 to 7.0.
```release-note
Updates documentation links to vSphere 7.0 documentation
```

Update documentation links to vSphere 7.0 documentation

---

vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go

Adds `RequiredWith` to options related to joining a domain in `windows_option`. This will ensure all required options / arguments for joining a domain are provided.
> **Note**: The `vsphere_virtual_machine` resource documentation **already** states as "optional", but "required if setting `join_domain`" Thus, no changes are required to the docs.
Building the provider with the following changes: 
```go
"join_domain": { 
Type:          schema.TypeString, 
Optional:      true, 
ConflictsWith: []string{cWindowsKeyPrefix + "." + "workgroup"}, 
Description:   "The domain that the virtual machine should join.", 
RequiredWith:  []string{cWindowsKeyPrefix + "." + "domain_admin_user", cWindowsKeyPrefix + "." + "domain_admin_password"},
}, 
```
The results of the change are, in a plan with the …

Add `RequiredWith` to options require to join a domain

---

vsphere/resource_vsphere_ha_vm_override.go
website/docs/r/ha_vm_override.html.markdown

- Adds `disabled`option to `vsphere_ha_vm_overide` resource.
- Updates `vsphere_ha_vm_overide`resource docs to include `disabled`.
- Updates `vsphere_ha_vm_overide`resource docs to vSphere 7.0 reference.
**Contributor Note:** Performed unit tests which included both positive and negative tests. All passed successfully.
**Example:**
**`variables.tf`**
```hcl
##################################################################################
##################################################################################
variable "vsphere_server" {
type        = string
description = "The fully qualified domain name or IP address of the vCenter Server instance."
}
variable "vsphere_username" {
type        = string
description = "The username to login to the vCenter Server instance."
} …
```

Add `disabled` to `vsphere_ha_vm_override`

---

website/docs/r/distributed_port_group.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown

- Updates the examples to remove legacy Terraform  interpolation.
- Updates the examples for simplicity and context.
- Corrects "DVS" to "VDS" as the correct term.
- Corrects import example for the `vsphere_distributed_port_group` resource docs.
- Adds missing VLAN options to the `vsphere_distributed_port_group` resource docs.
- Ensures markdown is lines are limited to column 80 in length.
`resource/distributed_virtual_switch`: Documentation updates [GH-1504, GH-1568]
`resource/vsphere_distributed_port_group`: Documentation updates [GH-1568]
Closes #1461
Closes #1567
Closes #1565

Update `resource/distributed_virtual_switch` and `vsphere_distributed_port_group` resource docs.

---

vsphere/resource_vsphere_virtual_disk.go
website/docs/r/virtual_disk.html.markdown

- Updates the `vsphere_virtual_disk` resource docs for simplicity and context.
- Updates the `vsphere_virtual_disk` resource docs with a clearer import example.
- Updates the `vsphere_virtual_disk` resource id error msg.
`resources/vsphere_virtual_disk`: Documentation and error message updates. [GH-1569]
Closes #1295

Update `vsphere_virtual_disk` docs and id error msg

---

website/docs/r/virtual_machine.html.markdown

Clarifies that templates that use ISO transport, a CD-ROM backed by a client device must be included and provides and example.
Closes #1292

Update docs example for templates that use ISO transport

---

.github/workflows/stale.yml

- Adds back stale issue and pull request management that was temporarily disabled in #1250 by @aareet.
- Updates to `actions/stale@v4` from `actions/stale@v1.1.0`
- Marked as `stale` if no activity in **180 days**.
- Closed if no activity **30 days** after being marked as stale.
- Exemptions include:
- Issues with `needs-triage`, `acknowledged`, and `in-progress` labels.
- PRs with `needs-review`, `under-review`, `acknowledged`, and `planned` labels.
PR #1250

Add GitHub Action for state issues and pull requests

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

When changing the `datastore_cluster_id` of a `vsphere_virtual_machine` the disks are not migrated to datastores of the new datastore cluster because no storage migration is triggered. This PR fixes this.
No. There used to be acceptance tests for this functionality that have been disabled with #1090 and removed with #1416.
`resource/virtual_machine`: Fix migration of all disks and configuration files when the `datastore_cluster_id` is changed on the resource. GH-1546
Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1454
- This fixes the issue described in my comment on https://github.com/hashicorp/terraform-provider-vsphere/issues/1268#issuecomment-980014586, which is different from #1268 itself.
- I think storage migration broke due to …

Fix disk migration when `datastore_cluster_id` changes

---

website/docs/r/virtual_machine.html.markdown

Updates the `vsphere_virtual_machine` resource documentation to clarify the process to hot add memory > 3GB when a virtual machine has <= 3GB.
Closes  #1352

Update `vsphere_virtual_machine` resource doc for memory hot add >3GB

---

website/docs/r/content_library.html.markdown

- Updates the content of the documentation - `content_library.html.markdown` - for readability, context, and accuracy.
- Updates the content of the documentation - `content_library.html.markdown` - with subscribed library example.
- Updates the examples to use `storage_backing` to use a set as required. 
`resource/content_library`: Documentation updates. [GH-1577]
Closes #1351

Update `resource/content_library` docs

---

website/docs/r/virtual_machine.html.markdown

Updated the documentation for vsphere_virtual_machine resource with the conditions that causes the virtual machine to reboot on update.
```release-note
`resource/vsphere_virtual_machine`:  Updated the documentation with the conditions that causes the virtual machine to reboot on update
```
Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1004

Update `vsphere_virtual_machine` resource docs with reboot conditions

---

vsphere/resource_vsphere_tag.go
vsphere/resource_vsphere_tag_category.go

It appears at some point the error message returned for tag/tag_category not found changed to include `404 Not found`. That string is searched for in a few other resources so I added it as a check to ensure the instance is removed from state on read if not found. I left the old check as well for any backwards compatibility to when that used to be the error message?
```
...
```
```release-note
`resource/tag`: Fix deletion detection in `tag` and `tag_category`.
```
Closes #1548

Check for 404 Not found on tag and tag_category

---

vsphere/virtual_machine_config_structure.go

Sets `annotation` on `r/vsphere_virtual_machine` to computed if not provided.
This will ensure that the annotation is added to state and that, if changed externally, it will also be updated in a state refresh.
`resource/vsphere_virtual_machine`: Sets `annotation` to computed. [GH-1588]
Closes #1459

Set `annotation` on `r/vsphere_virtual_machine` to computed

---

website/docs/r/content_library_item.html.markdown

Update `resource/content_library_item` docs.
- Improves content and clarity.
- Simplifies using generic Ubuntu examples
- Adds examples for `.iso` and `source_uuid`.
- Adds missing `type` argument.
`resource/content_library_item`: Documentation improvements [GH-1586]
Content supersedes #1585. Merge **after** (or in lieu of.)

Update `resource/content_library_item` docs

---

vsphere/resource_vsphere_file.go
website/docs/r/file.html.markdown

- Updates the `r/vsphere_file` docs content and examples.
- Removed the code to remove the temporary directory where the VMDK is uploaded as this is automatically deleted as part of the VMDK move.
**Plan**:
```hcl
}
resource "vsphere_file" "upload" {
datacenter         = "m01-dc01"
datastore          = "local-hdd-01"
source_file        = "/Users/johnsonryan/Downloads/VMware-Appliance-FaH_1.0.5.vmdk"
destination_file   = "/muffin/VMware-Appliance-FaH_1.0.5.vmdk"
create_directories = true
}
```
**Apply:**
```console
% terraform apply -auto-approve  
Terraform used the selected providers to generate …
```

Update `r/vsphere_file` resource and docs

---

vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

- Add `tools_upgrade_policy` argument to the `vsphere_virtual_machine` resource to set the upgrade policy for VMware Tools. One of `manual` or `upgradeAtPowerCycle`. Default: `manual`
- Updates the `vsphere_virtual_machine` resource docs to include the tools_upgrade_policy` argument.
Performed unit tests which included both positive and negative tests. All passed successfully.
Example:
```hcl
terraform {
required_providers {
vsphere = {
source  = "hashicorp/vsphere"
version = "x.y.z"
}
}
required_version = ">= x.y.z"
}
vsphere_server       = "m01-vc01.rainpole.io"
user                 = "administrator@vsphere.local"
password             = "VMware1!"
allow_unverified_ssl = true
}
name = "m01-dc01"
}
data "vsphere_network" …
```

Add `tools_upgrade_policy` argument to the `vsphere_virtual_machine` resource

---

vsphere/resource_vsphere_virtual_machine.go
website/docs/r/virtual_machine.html.markdown

Added a computed parameter (power_state) for checking the power state of VM and to show the difference in case VM is not in running state.
Related to https://github.com/hashicorp/terraform-provider-vsphere/issues/916
When VM is not running and we run terraform plan, it will show the following diff:
This is tested with Terraform 0.13.3 version.
```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
local_file.meta-data[0]: Refreshing state... [id=221754ffcbea5c01e45fcf0cc40be37aeaa33fda]
vsphere_virtual_machine.example-vm[0]: Refreshing state... [id=564d7840-81a1-72c1-463b-0cc137eed6ea]
--------------------------------------------------------------- …
```

Add check for `vsphere_virtual_machine` power state

---

CHANGELOG.md
vsphere/resource_vsphere_compute_cluster.go

Reverts change from #1432 as it was an accidental breaking change from a configuration perspective, it also caused the provider to panic since the type assertions were not updated correctly. We have re-opened #1205 and will address it for `v3.0.0` of the provider.

Revert type change of vsan_disk_group

---

vsphere/resource_vsphere_host.go
website/docs/r/host.html.markdown

- Adds support for `custom_attributes` to the`vsphere_host` resource.
- Moves `resourceVsphereHostCreate` before `resourceVsphereHostRead`
- Updates the `vsphere_host` resource docs to include `custom_attributes` and minor corrections.
`resource/vsphere_host: Added support for custom attributes. (GH-xxxx)`
Closes: #1618 
**Plan**
`main.tf`
```hcl
}
name = "m01-dc01"
}
data "vsphere_custom_attribute" "attribute" {
depends_on = [
vsphere_custom_attribute.attribute
]
name = "foo"
}
resource "vsphere_custom_attribute" "attribute" {
name                = "foo" …
```

feat: Add support for custom attributes on `r/vsphere_host`

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go

Updates the `DiskCloneValidateOperation` and `DiskImportOperation` functions in `virtual_machine_disk_subresource` to add support for SATA and IDE controllers and disks (alongside existing SCSI.)
`resource/virtual_machine`: Fixes ability to clone and import virtual machine resources with SATA and IDE controllers. (GH-1629)
Closes #1189 
Closes #1355
**Import**:
`main.tf`
```hcl
}
name = var.vsphere_datacenter
}
data "vsphere_network" "network" {
name          = var.vsphere_network
datacenter_id = data.vsphere_datacenter.datacenter.id
}
data …
```

fix: Update `DiskCloneValidateOperation` and `DiskImportOperation`

---

vsphere/distributed_virtual_switch_structure.go
vsphere/util.go
website/docs/r/distributed_virtual_switch.html.markdown

It would appear newer versions of vCenter responds back with traffic classes
even if those classes aren't accounted in the version of govmomi the provider has.
Need to upgrade govmomi to support new `nvmetcp` class that was causing a crash.
```release-note
`resource/dvs`: Prevent setting unsupported traffic classes.
```

fix: Prevent unsupported traffic classes to be set and cause crash

---

scripts/packet/devrc.tpl
scripts/packet/main.tf.phase3
vsphere/resource_vsphere_distributed_port_group_test.go
vsphere/resource_vsphere_storage_drs_vm_override_test.go
vsphere/resource_vsphere_tag_test.go
vsphere/resource_vsphere_virtual_machine_test.go

Makes tests in environments without DHCP (don't wait for VMs to receive IP address). Also switch to https://github.com/luischanu/TinyVM as the test VM since it comes with OpenVM Tools and a few other goodies.
The status of the tests are:
```
- skipped [29]
- failed  [70]
- passed  [263]
```
The next priority is figuring out what needs to be passed to the VMFS Datastore resource tests as whatever was captured in the setup config doesn't seem to port across deployments.

Fix tests to pass even without DHCP

---

scripts/packet/devrc.tpl
scripts/packet/main.tf.phase2
scripts/packet/main.tf.phase3
scripts/packet/versions.tf

The VMFS datastore tests weren't broken but was previously hardcoded, all of them pass with the right values set.

Generate VMFS disk IDs for tests

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/resource_vsphere_virtual_machine.go

Added a `PciPassthroughPostCloneOperation()` implementation on the subresource and added to the function to the `resourceVSphereVirtualMachinePostDeployChanges`. #1137
```console
❯ terraform apply -auto-approve
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
+ resource "vsphere_virtual_machine" "vm" {
+ annotation                              = (known after apply)
+ boot_retry_delay                        = 10000
+ change_version                          = (known after apply)
+ cpu_limit                               = -1
+ cpu_share_count                         = (known after apply)
+ cpu_share_level                         = "normal"
+ …
```

fix: Add and apply `PciPassthroughPostCloneOperation()` to subresource

---

website/docs/r/virtual_machine.html.markdown

N/A (documentation only)
```release-note
docs: Add tools_upgrade_policy to list of params that trigger a reboot
```
- https://github.com/hashicorp/terraform-provider-vsphere/pull/1506#issuecomment-1049039822
- https://github.com/hashicorp/terraform-provider-vsphere/pull/1522

docs: Add tools_upgrade_policy to list of params that trigger a reboot

---

vsphere/data_source_vsphere_virtual_machine.go
vsphere/data_source_vsphere_virtual_machine_test.go
website/docs/d/virtual_machine.html.markdown

Support lookup by UUID on the VM datasource.
```
➜ make testacc TESTARGS='-run=TestAccDataSourceVSphereVirtualMachine_' GOFLAGS="-count=1"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereVirtualMachine_ -timeout 240m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
=== RUN   TestAccDataSourceVSphereVirtualMachine_basic
--- PASS: TestAccDataSourceVSphereVirtualMachine_basic (32.52s)
=== RUN   TestAccDataSourceVSphereVirtualMachine_noDatacenterAndAbsolutePath
--- PASS: TestAccDataSourceVSphereVirtualMachine_noDatacenterAndAbsolutePath (30.32s)
=== RUN   TestAccDataSourceVSphereVirtualMachine_uuid
--- PASS: …
```

feat: Support looking up VM by UUID

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_resource_pool.go
vsphere/resource_vsphere_resource_pool_test.go
website/docs/r/compute_cluster.html.markdown
website/docs/r/resource_pool.html.markdown

- Added support for scalable shares on `r/vsphere_compute_cluster` and `r/vsphere_resource_pool` for vSphere 7.0 and higher.
- Updated the `r/vsphere_compute_cluster` and `r/vsphere_resource_pool` docs for the enhancement, including additional cleanup on the `r/vsphere_compute_cluster` docs.
`resource/compute_cluster`: Adds support for scalable shares.(GH-1634)
`resource/resource_pool`: Adds support for scalable shares.(GH-1634)
Closes #1622
`main.tf` for Cluster
```hcl
}
name = var.vsphere_datacenter
}
resource "vsphere_compute_cluster" "this" {
name …
```

feat: Add support for scalable shares

---

website/docs/index.html.markdown

There is a typo on the word `direcotry` on the documentation. This PR just fix it to `directory`.
```release-note
NONE
```
None

 fix(docs): correct typo 

---

vsphere/data_source_vsphere_compute_cluster_host_group.go
vsphere/data_source_vsphere_compute_cluster_host_group_test.go
vsphere/provider.go
vsphere/resource_vsphere_compute_cluster_host_group.go
website/docs/d/compute_cluster_host_group.html.markdown

- Adds a datasource for `vsphere_compute_cluster_host_group`.
- Corrects the description for the `name` attribute in `r/vsphere_compute_cluster_host_group`.
`datasource/compute_cluster_host_group`: New data source can be used to read general attributes of a host group. (GH-xxx)
Closes #1449
`main.tf` Example
```hcl
}
name = var.vsphere_datacenter
}
data "vsphere_compute_cluster" "cluster" {
name          = var.vsphere_cluster
datacenter_id = data.vsphere_datacenter.datacenter.id
}
data "vsphere_compute_cluster_host_group" "host_group1" {
name …
```

feat: Add `d/vsphere_compute_cluster_host_group`

---

website/docs/r/host_port_group.html.markdown

- Updates `r/host_port_group` documentation with more information regarding the `id` unique to Terraform.
- Updates the content of the `r/host_port_group` documentation for clearer examples and removal of legacy interpolation.
`resource/host_port_group`: Documentation updates. (GH-1671)
Closes #554

docs: update `r/host_port_group` docs

---

vsphere/internal/helper/contentlibrary/content_library_helper.go

This fixes local iso uploading in content library item.
```release-note
Fix content library item local iso upload
```
Resolves https://github.com/hashicorp/terraform-provider-vsphere/issues/1664

fix: Local iso upload in content library item

---

website/docs/r/host.html.markdown

This is some documentation updates to the resource `vsphere_host`:
- Add in the Example Usages section using the data source `vsphere_host_thumbprint` to get the Host Thumbprint
- Add a link to the data source `vsphere_host_thumbprint` in the `thumbprint` Argument Reference
- Fix spelling of the word disconnected
I feel adding additional help on getting the thumbprint is important. SSL certs are not often trusted in vSphere, especially at the stage a host is being added to a vCenter. At this point is it not managed by the vSphere Certificate Manager.
Additionally the VMware recommended method of handling certificates is Hybrid mode where the Host certificates are not automatically renewed with a signed certificate.
IMPROVEMENTS:
`resource/vsphere_host`: Documentation updates. (#1675]
[Add …

docs: update `r/vsphere_host` docs

---

website/docs/d/compute_cluster_host_group.html.markdown
website/docs/d/ovf_vm_template.html.markdown
website/docs/index.html.markdown

- fix typos on docs index for the term "_privilege_".
- move new data source docs under a subcategory.

docs: update docs index

---

vsphere/resource_vsphere_host_virtual_switch.go
vsphere/resource_vsphere_host_virtual_switch_test.go
website/docs/r/host_virtual_switch.html.markdown

Allow `standby_nics` on `r/vsphere_host_virtual_switch` to be an optional attribute so the `standby_nics = []` does not need to be defined when no standby NICs are required/available.
`resource/host_virtual_switch`: Allow `standby_nics` on `r/vsphere_host_virtual_switch` to be an optional attribute so the `standby_nics = []` does not need to be defined when no standby NICs are required/available.
Closes: #1690 
Current Method:
```hcl
terraform {
required_providers {
vsphere = {
source  = "local/hashicorp/vsphere"
version = ">= 2.3.0"
}
}
required_version = ">= 1.2.5"
}
vsphere_server       = "m01-vc01.rainpole.io"
user                 = "administrator@vsphere.local"
password             = "VMware1!"
allow_unverified_ssl = true
}
data "vsphere_datacenter" "datacenter" …
```

enhance: Allow `standby_nics` as optional attribute

---

vsphere/helper_test.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/resource_vsphere_virtual_machine.go

Sometimes reconfiguration tasks take a long time. And if they last more than 5 minutes, then the tasks fail. Because the limit is set as a constant as seen below.
https://github.com/hashicorp/terraform-provider-vsphere/blob/30f37d268d790f7ced3cf6b2d80bfaf693327251/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L827-L840
This pull request adds a timeout setting for `r/virtual_machine` reconfiguration tasks.
`resource/virtual_machine`: Virtual machine reconfiguration tasks will use the provider `api_timeout` setting. (GH-1645)
Closes #1646
Closes #1662

feat: Set timeout for `v/virtual_machine` reconfigure task

---

go.mod
go.sum
vsphere/config.go
vsphere/helper_test.go
vsphere/internal/helper/vsanclient/vsan_client_helper.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/tags_helper.go
website/docs/r/compute_cluster.html.markdown

_Copying original PR description from #1683_
_Please see original PR comments for full context of conversation_
This feature is to support configuring the compression and deduplication for vSAN. In this change, we added two new parameters `vsan_dedup_enabled` and `vsan_compression_enabled` to support the toggling of data efficiency configuration for the specified vSAN datastore. The `vmware/govmomi` version is also updated `0.28.0` to support the latest VMODL connection to vSphere/vSAN.
**Testing Details:**
We did end to end test from 6 standalone hosts based on the vSphere 7.0. A vSAN cluster could be created with deduplication and compression enabled by running .tf file which contains the following settings.
```hcl
resource "vsphere_compute_cluster" "cluster" {
name = "clustername" …
```

feat: Add support vSAN space efficiency

---

.github/workflows/codeql-analysis.yml

Updates CodeQL action:
- Removes the deprecated `git checkout HEAD^2` step along with checkout `fetch-depth` causing the WARNING.
- Removes default comments.
- Formats YAML.
Resolves #1720

fix: update CodeQL action to removes the deprecated step

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
website/docs/d/virtual_machine.html.markdown

With VMware PVRDMA — the paravirtual RDMA device that takes advantage of any RoCE-capable hardware on an ESXi host — ESXi can support running workloads with high performance while still maintaining the flexibility offered by virtualization, including operational flexibility, better resilience, higher availability, and lifecycle management capabilities. This high performance is possible because PVRDMA allows for direct memory transfers (DMA) between guest memory to
the RoCE-capable hardware without CPU intervention. Using the RDMA protocol enables the potential for memory-to-memory zero-copy transfers between guests on two different hosts.
`resource/virtual_machine` : Add support for the PVRDMA `vmxnet3vrdma` network interface adapter type. …

feat: Add support for paravirtual RDMA network interface adapter type

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go
website/docs/r/compute_cluster.html.markdown

This change enables the configuration for the vSAN performance service via the .tf file. The three parameters supported are to enable/disable vSAN performance service, the support for verbose mode, and network diagnostics mode. In this change, we will also support the enablement for vSAN performance by default with vSAN performance which aligns with the behavior of the vSAN enablement UI.
The related documentation and API command line are also updated in this change.
```
$make testacc TESTARGS='-run=TestAccResourceVSphereComputeCluster_vsanPerfEnabled'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVSphereComputeCluster_vsanPerfEnabled -timeout 240m
? …
```

feat: Add support for vSAN performance service configuration

---

vsphere/resource_vsphere_datastore_cluster.go

Fixes error parsing string as enum type for `sdrs_advanced_options` on `r/datastore_cluster`.
Triage details and fix validation could be found in the linked issue.
`resource/datastore_cluster`: Fixes error parsing string as enum type for `sdrs_advanced_options` [(GH-1749](https://github.com/hashicorp/terraform-provider-vsphere/pull/1749))
Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1448

fix: `sdrs_advanced_options` on `r/datastore_cluster`

---

vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go
website/docs/r/compute_cluster.html.markdown

This change adds the feature to support the vSAN unmap feature. In this code change, the vsan_unmap_enabled field is introduced, which maps to the vSAN enable state. By enabling the feature, vSAN can recognize the Trim/Unmap command from GuestOS and reclaim the storage space that is mapped to a deleted vSAN object. The introduction for the unmap feature is recorded here: https://core.vmware.com/resource/vsan-space-efficiency-technologies.
```
$ make testacc TESTARGS="-run=TestAccResourceVSphereComputeCluster_vsanUnmapEnabledwithVsanEnabled"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVSphereComputeCluster_vsanUnmapEnabledwithVsanEnabled -timeout 240m
? …
```

feat: add support for vSAN unmap

---

vsphere/data_source_vsphere_dynamic.go
vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

Addresses the `misspell` linter errors observed in `golangci-lint`.
`.golangci.yml`
```yaml
issues:
max-per-linter: 0
max-same-issues: 0
linters:
disable-all: true
enable:
- misspell
run:
timeout: 10m
go: 1.18
```
```console
✦ ❯ golangci-lint run
```

fix: address `misspell` linter errors observed in `golangci-lint`

---

vsphere/internal/helper/contentlibrary/content_library_helper.go

Addresses `gostaticanalysis/nilerr` error in `content_library_helper.go`'s `ItemFromName` function.
`.golangci.yml`
```yaml
issues:
max-per-linter: 0
max-same-issues: 0
linters:
disable-all: true
enable:
- nilerr
run:
timeout: 10m
go: 1.18
```
```console
✦ ❯ golangci-lint run
```

fix: address `gostaticanalysis/nilerr` error in `content_library_helper.go`

---

vsphere/config_test.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/resource_vsphere_file_test.go

`io/ioutil` is deprecated as of Go v1.16. This provider uses v1.18.
This pull request:
- Converts from `io/ioutil` to the use of the `io` package and updates then `ioutil.ReadAll...` to `io.ReadAll...`.
- Converts from `io/ioutil` to the use of the `os` package and updates `ioutil.TempDir...` to `os.MkdirTemp...`.
- Convert  from `io/ioutil` to the use of the `os` package and updates `ioutil.WriteFile..` to `os.WriteFilel...`.
The following messages would be observed by `golangci-lint`:
```console
vsphere/internal/helper/ovfdeploy/ovf_helper.go:10:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for …
```

fix: address `io/ioutil` depreciation

---

vsphere/config.go
vsphere/data_source_vsphere_datacenter.go
vsphere/data_source_vsphere_host.go
vsphere/helper_test.go
vsphere/internal/helper/customattribute/custom_attributes_helper.go
vsphere/internal/helper/structure/structure_helper.go
vsphere/tags_helper.go

Addresses the `gofmt` errors observed in `golangci-lint`.
`.golangci.yml`
```yaml
issues:
max-per-linter: 0
max-same-issues: 0
linters:
disable-all: true
enable:
- gofmt
run:
timeout: 10m
go: 1.18
```
```console
✦ ❯ golangci-lint run
```

fix: address `gofmt` errors observed in `golangci-lint`

---

docs/INSTALL.md

- Updates URLs to `https://releases.hashicorp.com/terraform-provider-vsphere/${RELEASE}/...` versus `https://github.com/hashicorp/terraform-provider-vsphere/releases/download/v${RELEASE}...`.
- Minor formatting updates.
Closes #1754

docs: update `INSTALL.md`

---

vsphere/distributed_virtual_switch_helper.go
vsphere/distributed_virtual_switch_structure.go

Adds support for vSphere distributed switch 8.0.0, default in vSphere 8.0.
```markdown
* `resource/distributed_virtual_switch`: Adds support for vSphere distributed switch version `8.0.0` in vSphere 8.0.
```

feat: add support for distributed switch v8.0.0

---

website/docs/d/ovf_vm_template.html.markdown
website/docs/r/virtual_machine.html.markdown

Updates the documentation to include information for `enable_hidden_properties` which allows vApp properties with`ovf:userConfigurable=false` to be set.
```markdown
IMPROVEMENTS:
`datasource/vsphere_ovf_vm_template`: Documentation updates to include the `enable_hidden_properties` option for vApp properties. (https://github.com/terraform-providers/terraform-provider-vsphere/issues/1792)
`resource/vsphere_virtual_machine`: Documentation updates to include the `enable_hidden_properties` option for vApp properties. (https://github.com/terraform-providers/terraform-provider-vsphere/issues/1792)
```
Closes #1782

docs: update for `enable_hidden_properties`

---

docs/INSTALL.md
docs/PULL_REQUESTS.md
vsphere/data_source_vsphere_host.go
website/docs/d/folder.html.markdown

Simple fixes on documentation plus a little bit of [reformatting](https://github.com/hashicorp/terraform-provider-vsphere/compare/main...Attacktive:terraform-provider-vsphere:main#diff-8b4bac5499caa6b488a8fa5cc57d0ef5da86e4843cd97fddeca129e2c6e03244R16-R18) which `gofmt` complained about.
```
$ make testacc TESTARGS='-run=TestAccDataSourceVSphereHost'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereHost -timeout 240m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
=== RUN   TestAccDataSourceVSphereHost_basic
data_source_vsphere_host_test.go:63: set TF_VAR_VSPHERE_DATACENTER to run vsphere_host acceptance tests
--- SKIP: …
```

docs: fix grammatical errors

---

vsphere/config.go

Reverts the update in #1416 back to SHA1.
Reverts a linting update from #1416 back to SHA1. SHA1 is used by `vmware/govmomi` for the session file. This will allow session reuse from `govc`.
Closes #1807

fix: revert sha1 linting update

---

.github/workflows/pull-request.yml

The changes on my fork were merged upstream and I have already deleted my fork (sorry about that).
```
...
```
```release-note
...
```

.github/workflows: Switch pr-size-labeler action to upstream

---

.github/workflows/release.yml
.github/workflows/unit_tests.yaml

Reference: https://github.com/actions/setup-go/releases/tag/v3.1.0
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/releases/tag/v2.2.0
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/blob/7e53d9adb57f05cb16c227ef0bfd030060fae82e/.github/workflows/hashicorp.yml#L26-L29
In hashicorp/ghaction-terraform-provider-release, its passed through via the `setup-go-version-file` input.
```
...
```
```release-note
...
```

.github/workflows: Use actions/setup-go go-version-file input

---

website/docs/r/virtual_machine.html.markdown

Fixes broken links in the documentation caused by [this commit](https://github.com/hashicorp/terraform-provider-vsphere/commit/d23dfb57cc5724d1367e3f5d5898427b9b5efe3d).
```
...
```
```release-note
Fix broken links in /docs/resources/virtual_machine.
```

docs: fix broken links

---

website/docs/r/virtual_machine.html.markdown

Replace `remote_ovf_url` with `local_ovf_path `for deployment example using a local OVF in `r/vsphere_virtual_machine` documentation.
```
...
```
```release-note
...
```

docs: vm ovf local deploy example usage

---

vsphere/data_source_vsphere_role_test.go
vsphere/resource_vsphere_role.go
vsphere/resource_vsphere_role_test.go
website/docs/r/vsphere_role.html.markdown

Adds support for import of `r/vsphere_role`. 
Not: vSphere system roles are blocked from import as these can not be modified or deleted; however, each can be returned in `d/vsphere_role`.
```
$ make testacc TESTARGS="-run=TestAccResourceVsphereRole"
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVsphereRole -timeout 240m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
=== RUN   TestAccResourceVsphereRole_createRole
--- PASS: TestAccResourceVsphereRole_createRole (12.47s)
=== RUN   TestAccResourceVsphereRole_addPrivilege
--- PASS: TestAccResourceVsphereRole_addPrivilege (7.54s)
=== RUN   TestAccResourceVsphereRole_removePrivilege
--- PASS: …
```

feat: add support for import of `r/vsphere_role`

---

vsphere/nas_datastore_helper.go

Fix a bug in nasDatastoreMountProcessor.diff() method which was the root cause of https://github.com/hashicorp/terraform-provider-vsphere/issues/1589
Fix `r/vsphere_nas_datastore` not mounted to additional hosts as day-two.
The nasDatastoreMountProcessor.diff() method was not correctly calculating the difference between the old and the new datastore hosts and as a result of this the nasDatastoreMountProcessor.processMountOperations()was not mounting the datastore the new hosts.
Testing done:
Added additional ESXi hosts to the "host_system_ids" of NFS datastore and verified that terraform apply correctly mounted the datastore to the new hosts.
Closes #1589 
```shell
% make testacc TESTARGS="-run='TestAccResourceVSphereNasDatastore'"
==> Checking that code …
```

fix: `r/vsphere_nas_datastore` not mounted to additional hosts as day-two

---

vsphere/resource_vsphere_vm_storage_policy.go

Modify the resourceVMStoragePolicyDelete method to check the response of pbmClient.DeleteProfile() API call for errors and re-throw them. As a result of this if a policy is in use and cannot be deleted, the destroy operation will fail and the policy will remain in the state.
Testing done:
1. Created a policy using terraform
2. Assigned the policy to a VM using the vSphere UI 
3. Tried to delete the policy using terraform and verified that the destroy operation failed with resource in use error:
> Plan: 0 to add, 0 to change, 1 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> vsphere_vm_storage_policy.test-policy-delete2: Destroying... …

fix: `r/vsphere_vm_storage_policy` delete method check for use

---

acctests/README.md
acctests/equinix/devrc.tpl
acctests/equinix/main.tf
acctests/equinix/vcsa_deploy.json
acctests/equinix/versions.tf
acctests/vsphere/deploy-nested-esxi.tf
acctests/vsphere/devrc.tpl
acctests/vsphere/for-acceptance-tests.tf
acctests/vsphere/main.tf
acctests/vsphere/nested-esxi-template.tf
acctests/vsphere/output.tf
acctests/vsphere/versions.tf
vsphere/data_source_vsphere_content_library_item_test.go
vsphere/data_source_vsphere_content_library_test.go
vsphere/data_source_vsphere_host_thumbprint_test.go
vsphere/data_source_vsphere_resource_pool_test.go
vsphere/internal/helper/testhelper/testing.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
vsphere/resource_vsphere_host_port_group_test.go
vsphere/resource_vsphere_host_virtual_switch_test.go
vsphere/resource_vsphere_nas_datastore_test.go
vsphere/resource_vsphere_storage_drs_vm_override_test.go
vsphere/resource_vsphere_vapp_container_test.go
vsphere/resource_vsphere_virtual_machine_test.go

The provider will be undergoing a period of technical debt paydown. The primary goal is to have portable and scalable acceptance testing such that community contribution is orders of magnitude easier. This PR is a step in that direction, we want to rely on as little physical infrastructure as possible, with that in mind the test suite will move towards using nested ESXis (which ideally will make no difference to the test cases). The end goal being a full CI pipeline that can run nightly, against different permutations of ESXi/vSphere version combinations, and that can validate PRs autonomously and report back results.
Not much other than an Equinix based config that does not rely on a second physical ESXi host, rather nested ESXi VMs are deployed. The tests in general don't rely too much …

chore: Begin overhauling provider acceptance test setup

---

vsphere/internal/helper/vsanclient/vsan_client_helper.go

Fix: Configure vSAN dedup and compression failed with context deadline exceeded error in 5 min
Some complex vSAN service configurations in 8.0 usually takes quite long time, much more than 5 min, however vSAN reconfigure uses the default provider timeout, we need remove this restriction.
Resolution: change to use a non-nil, empty context, since there're no timeout settings in vSAN tasks.
**Testing Details**
```
~ resource "vsphere_compute_cluster" "cluster" {
id                                                    = "domain-c22"
name                                                  = "cluster-333"
tags                                                  = []
~ vsan_compression_enabled                              = false -> true
~ …
```

fix: remove vsan reconfigure timeout

---

vsphere/data_source_vsphere_virtual_machine.go
vsphere/data_source_vsphere_virtual_machine_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_config_structure.go

`data/vsphere_virtual_machine` Add `moid` attribute to support result from `data/vsphere_dynamic`
```
...
```
```release-note
- `data/vsphere_virtual_machine` Add `moid` attribute to support result from `data/vsphere_dynamic`
```
Closes #1867

feat: Add `moid` attribute in `vsphere_virtual_machine` data source

---

website/docs/r/host.html.markdown

Updates the argument reference for `cluster` to correctly note that it conflicts with `cluster_managed`.
Ref: #1850

docs: update `r/vsphere_host`

---

acctests/README.md
acctests/vsphere/for-acceptance-tests.tf
acctests/vsphere/nested-esxi-template.tf
vsphere/resource_vsphere_vnic_test.go

Fix VNIC tests to work with new nested ESXi model. This is so I can review/add tests to #1855 
```
$ make testacc TESTARGS='-run=TestAccResourceVSphereVNic_'
=== RUN   TestAccResourceVSphereVNic_dvs_default
--- PASS: TestAccResourceVSphereVNic_dvs_default (196.88s)
=== RUN   TestAccResourceVSphereVNic_dvs_vmotion
--- PASS: TestAccResourceVSphereVNic_dvs_vmotion (196.36s)
=== RUN   TestAccResourceVSphereVNic_hvs_default
--- PASS: TestAccResourceVSphereVNic_hvs_default (33.19s)
=== RUN   TestAccResourceVSphereVNic_hvs_vmotion
--- PASS: TestAccResourceVSphereVNic_hvs_vmotion (32.19s)
```
```release-note
r/vsphere_vnic: Fix vnic tests GH-1887
```

fix: vnic tests

---

vsphere/resource_vsphere_file.go
vsphere/resource_vsphere_file_test.go

- Updates `resource_vsphere_file.createDirectory` method to check whether the provided file path has any parent folder(s). If there are no folders to be created we return early without invoking `FileManager.MakeDirectory`. This fixes the “_slice bounds out of range_” runtime error which was crashing the provider.
- Fixes the `resource_vsphere_file_test` acceptance tests as they were failing due to incorrect test vmdk files.
- Adds a new TestAccResourceVSphereFile_uploadWithCreateDirectories test to cover the `r/vsphere_file.create_directories` configuration argument.
Testing done:
Performed terraform apply using the following configuration:
```hcl
resource "vsphere_file" "iso" {
datacenter       = data.vsphere_datacenter.datacenter.name
datastore        = …
```

fix: `r/vsphere_file` provider crash

---

.github/workflows/issue_greeting.yml
.github/workflows/milestone-closed.yml
.github/workflows/stale.yml

Pin remaining GitHub Actions to a commit hash.
Code Scanning:
- https://github.com/hashicorp/terraform-provider-vsphere/security/code-scanning/43
- https://github.com/hashicorp/terraform-provider-vsphere/security/code-scanning/38
- https://github.com/hashicorp/terraform-provider-vsphere/security/code-scanning/34

chore(gh): pin actions to commit hash

---

vsphere/resource_vsphere_compute_cluster.go

Add version check before handling vSAN HCI Mesh, since this feature is supported in 70U1 or later.
Test Result:
End-to-end test on vSphere 7.0 with only vSAN enabled. Configuration won't be failed anymore.
```
$ terraform apply
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
vsphere_compute_cluster.cluster: Refreshing state... [id=domain-c45]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
+ create
+ resource "vsphere_compute_cluster" "cluster" {
+ datacenter_id                                         = "datacenter-3"
+ dpm_automation_level …
```

fix: add version check for vsan hci mesh

---

vsphere/config.go

Reverts hashicorp/terraform-provider-vsphere#1955
Well +1 for CI. Unfortunately this change seems to do something very mutative to the client? It seems to cause many "diffs" in testing across several resources. Perhaps forcing certain backend values that are falling out of sync with Terraform?
Ex:
```
=== RUN   TestAccDataSourceVSphereComputeCluster_absolutePathNoDatacenter
data_source_vsphere_compute_cluster_test.go:42: Step 1/1 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
<= read (data resources)
<= data "vsphere_compute_cluster" "compute_cluster_data" {
+ id …
```

Revert "fix: set vSAN client with the current version of the service en…"

---

.github/workflows/acceptance-tests.yaml

The pretty test printing does not provide summary data or comparison data to previous runs. Store the testlog as an artifact for further processing.

chore: Store CI log

---

.github/workflows/acceptance-tests.yaml

Also switch to go install method for formatter, need to get the official action added to our trusted database.

chore: CI fix upload action sha

---

.github/workflows/acceptance-tests.yaml

little check will exit 1 if "panic:" is found in the logfile. The CI will likely need a little manual cleanup if an acceptance test panics.

chore(ci): check for panic in logfile

---

.github/workflows/acceptance-tests.yaml
scripts/compare-testlogs.js

The previous artifact downloader action didn't support downloads across workflows. Using a popular and HCP approved alternative that does. Added exit code to comparison scripts to flag regressions in CI.

Restore regression check

---

.github/workflows/acceptance-tests.yaml

The GH action that downloads artifacts only downloads successful workflow artifacts by default. Setting to empty string allegedly removes that restriction.

chore(ci): ignore workflow status in log download

---

vsphere/internal/helper/computeresource/compute_resource_helper.go
vsphere/internal/helper/envbrowse/environment_browser_helper.go
vsphere/internal/helper/resourcepool/resource_pool_helper.go
vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
vsphere/resource_vsphere_virtual_machine.go

Bugfix for [issue 1939] (https://github.com/hashicorp/terraform-provider-vsphere/issues/1939) 
Cloning and configuring VMs with newer guest operating systems (Windows 2022 in this case) was failing in some cases due to the backend using the ESXi default hardware version instead of the template or VM hardware version being cloned from or configured. This was causing the guest OS to not be recognised as supported.
Changed the backend pass the hardware version when retrieving the OS family.
```
no regressions
```
```release-note
`r/virtual_machine`: Fix "Error: cannot find OS family for guest ID ... " when cloning and/or configuring a VM/Template …
```

Issue 1939

---

vsphere/resource_vsphere_virtual_machine.go

Bugfix for https://github.com/hashicorp/terraform-provider-vsphere/issues/1809
Split the storage controller change and the harddisk edit operations into separate API calls. The previous behaviour was to generate 2 edit operations for the harddisk object which leadto an undefined API behavior.
```
no regresions
```
```release-note
`r/virtual_machine`: Fix "Invalid operation for device '0'" when reconfiguring a VM ([#1809](https://github.com/hashicorp/terraform-provider-vsphere/issues/1809))
```

Bugfix addressing issue-1809.

---

CHANGELOG.md
website/docs/r/vnic.html.markdown

- Updated the example to show `services` instead of `enabled_services`.
- Updated minor markdown errors.
- Updated `CHANGELOG.md`.
```markdown
IMPROVEMENTS:
* `vsphere_nic`: Documentation updates to resource.
```
Closes #1976

docs: update `r/vsphere_nic` docs

---

vsphere/resource_vsphere_virtual_disk.go

Fixes #1824
Issue addressed - when r/vsphere_virtual_disk.type is set as "lazy" as documented here:
https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_disk#type i.e. Thick Provisioned Lazy Zeroed it is sent and received as "preallocated". The value is mapped when sent but not when received which causes disk recreaion when terraform apply is executed for the second time without changing the HCL config.
Fix applied - when virtual disk type is read from the backend the value is transformed to "lazy" if "preallocated" is received.
Testing done:
With HCL:
```
resource "vsphere_virtual_disk" "virtual_disk_test" {
count              = 1
datacenter         = data.vsphere_datacenter.datacenter.name
datastore          = data.vsphere_datastore.datastore.name …
```

fix: r/vsphere_virtual_disk with lazy forces replacement

---

website/docs/r/virtual_machine.html.markdown

Updated `resource/virtual_machine` docs for:
- `sync_time_with_host`
- `sync_time_with_host_periodically`
Additional reference: https://kb.vmware.com/s/article/1189
> VMware Tools performs two types of time corrections:
> 
> **One-off time sync:** Guest system clock is synchronized to host time upon specific VM life-cycle events that can cause guest** clock to become incorrect, such as resuming from vMotion or a snapshot. This capability is recommended for use and turned **_ON_** by default.
> 
> **Periodic time sync:** Guest system clock is periodically (every 60 seconds) synchronized to track host time. It is recommended that guests use a native time synchronization service – such as NTPD or Chrony in Linux based operating systems, and W32Time for Microsoft Windows. If that's not …

docs: update `resource/virtual_machine`

---

vsphere/internal/helper/testhelper/testing.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go
website/docs/r/compute_cluster.html.markdown

Patch some fix on vSAN fault domains and stretched cluster:
1. Add several environment variables to skip stretched cluster acc test, since current CI setup doesn't support it.
addressed https://github.com/hashicorp/terraform-provider-vsphere/pull/1885#pullrequestreview-1721947476
2. Add example usage of stretched cluster in document.
3. Separate vSAN fault domains and stretched cluster by adding ConflictWith, fault domain configure and flatten will only be triggered when stretched cluster non-exist.
```
=== RUN   TestAccResourceVSphereComputeCluster_faultDomain
--- PASS: TestAccResourceVSphereComputeCluster_faultDomain (220.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	223.415s
=== RUN …
```

fix: separate vsan fault domains and stretched cluster

---

vsphere/resource_vsphere_virtual_machine_test.go

- Changed the resource name in the e2e config which was not applied after addressing gues OS customization resurce review comments
- Verified other VM related tests after Nightly Acceptance tests was restored. Rerun failing tests relted to clone and customization. 
```
TestAccResourceVSphereVirtualMachine_cloneCustomizeForceNewWithDatastore /opt/homebrew/opt/go/libexec/bin/go tool test2json -t /Users/vasila/Library/Application Support/JetBrains/IntelliJIdea2023.2/plugins/go-plugin/lib/dlv/macarm/dlv --listen=127.0.0.1:53135 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /Users/vasila/Library/Caches/JetBrains/IntelliJIdea2023.2/tmp/GoLand/___2terraform_provider_vsphere.test -- -test.v -test.paniconexit0 -test.run …
```

fix: guest os customization related vm e2e test

---

docs/FAQ.md

VMware was acquired by Broadcom, Inc. on November 23, 2023.
Update `FAQ.md` to represent Broadcom collaborators.
**Note**: There are no changes required for the product names.

docs: update `FAQ.md`

---

vsphere/data_source_vsphere_virtual_machine_test.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/virtual_machine_config_structure.go

The ` memory_reservation_locked_to_max` property was missing from `vsphere_virtual_macine` schema (both data and resource). The property of the VM was automatically set to `false` if `memory` and `memory_reservation` properties have different values. 
With this commit the property can be set to true explicitly and it will be applied only if `memory` and `memory_reservation properties` have same values. If the `memory_reservation_locked_to_max` is not explicitly set to `true` the original behaviour is preserved.
```
API server listening at: 127.0.0.1:60172
=== RUN   TestAccDataSourceVSphereVirtualMachine_basic
--- PASS: TestAccDataSourceVSphereVirtualMachine_basic (71.99s)
PASS
Debugger finished with the exit code 0
=== RUN …
```

fix: add `memory_reservation_locked_to_max` property to `r/vsphere_virtual_macine` schema for sr-iov

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

After the introduction of the SR-IOV feature network adapters due to inconsistent check for changes in the `physical_function` attribute have been recreated after clone since the check always returned `true`. The result is that instead of updating existing NICs the relocate tack started after clone was always deleting the existing NICs and creating new ones. This was causing the new VM to be disconnected from network
Changed the check for changes in `physical_function` attribute to treat nil and empty string equaly so missing `physical_function` attribute in the device compared to empty string from the schema won't be cosnidered as changed.
Testing done: cloned VM from template with 2 nics and verified that there is network connectivity. Also verified the output from lspci command on the …

fix: scsi ids changing on machines built with v2.6.x

---

vsphere/virtual_machine_config_structure.go
website/docs/r/virtual_machine.html.markdown

- Changed the default value for `sync_time_with_host` in `r/vsphere_virtual_machine` to `true` to align with default value provided by the UI.
- Updated documentation
Testing Done:
1. Created VM before changes - s`yncTimeWithHostAllowed` was `false`
2. After the changes without explicit configuration `syncTimeWithHostAllowed` was equal to `true`
```markdown
`r/virtual_machine`: Changed the default value for `sync_time_with_host` in `r/vsphere_virtual_machine` to `true` to align with default value provided by the UI.
```
Closes #1443

fix: set `sync_time_with_host` to default to `true`

---

vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_test.go

- Added the VM folder in the search for VMs criteria in deploy from OVF scenario.
- Added an e2e test. Verified that when the VM folder is not strictly specified the OVF deploy is passing. The query is in the default VM folder.
```console
API server listening at: 127.0.0.1:65413
=== RUN   TestAccResourceVSphereVirtualMachine_deployOvfFromUrlMultipleVmsSameName
--- PASS: TestAccResourceVSphereVirtualMachine_deployOvfFromUrlMultipleVmsSameName (162.90s)
PASS
Debugger finished with the exit code 0
```
```marrkdown
`r/virtual_machine`: Added the virtual machine folder in the search for virtual machine criteria when deploying from an OVF/OVA. scenario. Allows virtaul machines with same names in different virtual machine …
```

fix: add vm folder when querying for vm

---

vsphere/resource_vsphere_virtual_disk.go
website/docs/r/virtual_disk.html.markdown

Fix: Import of `r/vsphere_virtual_disk` imports the wrong `vmdk_path`.
Output from local testing:
```console
$rm terraform.tfstate
$terraform import vsphere_virtual_disk.vmdk '{"virtual_disk_path": "/DataCenter/[vsanDatastore]namespace_test/secondary.vmdk", "create_directories": "true"}'
...
vsphere_virtual_disk.vmdk: Importing from ID "{\"virtual_disk_path\": \"/DataCenter/[vsanDatastore]namespace_test/secondary.vmdk\", \"create_directories\": \"true\"}"...
2022-09-26T19:23:44.709-0700 [INFO]  provider.terraform-provider-vsphere: 2022/09/26 19:23:44 [INFO] Set create_directories during import: true: timestamp=2022-09-26T19:23:44.709-0700   <----newly added log info, field is successfully set during import
2022-09-26T19:23:45.164-0700 [INFO]  provider.terraform-provider-vsphere: …
```

fix: import of `r/vsphere_virtual_disk` imports the wrong `vmdk_path`

---

vsphere/data_source_vsphere_host_vgpu_profile.go
vsphere/provider.go
website/docs/d/host_vgpu_profile.html.markdown

Add a new data source to the provider to query and return available vGPU profiles for a host.
No acceptance tests added.
Output from provider testing:
ESXi host with A100 GPU - no vGPU profile name filter
```
Changes to Outputs:
+ all_host_vgpu_profiles = {
+ host_id       = "host-1021"
+ id            = "fdcccc4252c0516e9d54a1ee6e851ba9f336c64502d6e80c5a684072f6e02bdc"
+ name          = null
+ vgpu_profiles = [
+ {
+ disk_snapshot_supported   = true
+ memory_snapshot_supported = true
+ migrate_supported         = true
+ suspend_supported         = true
+ vgpu                      = "grid_a100d-4c"
},
+ {
+ disk_snapshot_supported   = true
+ memory_snapshot_supported = true
+ migrate_supported         = true
+ suspend_supported         = true
+ vgpu                      = "grid_a100d-8c" …
```

feat: add data source vgpu profiles

---

vsphere/data_source_vsphere_datastore.go
vsphere/data_source_vsphere_datastore_stats.go
vsphere/data_source_vsphere_datastore_stats_test.go
vsphere/data_source_vsphere_datastore_test.go
vsphere/provider.go
website/docs/d/datastore.html.markdown
website/docs/d/datastore_stats.html .markdown

There is currently no straightforward way to choose a datastore based on usage when creating a VM. This way more criteria can be added to choosing a datastore for a VM. For example, select a datastore if the total capacity is greater than a value or free space is greater than a value. I intend to also add a sorting of all datastores as part of this PR.
Add total capacity and free space for datastore. This way more criteria can be added to datastore selection
No, will be added after first feedback.
Yes
```
$ make testacc TESTARGS="-run=TestAccDataSourceVSphereDatastoreStats_basic"                    
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v …
```

feat: add disk stats for datastore

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

This change fixes 2 deficiencies in the support for passthrough network adapters on virtual machines.
The support for SR-IOV adapters was added with https://github.com/hashicorp/terraform-provider-vsphere/pull/2059 which was simply a port of an old change that never made it in https://github.com/hashicorp/terraform-provider-vsphere/pull/1417
The issues introduced by these changes are:
1. In-place repacement of NICs is not supported if the source or destination type is "sriov". The reason provided for this is that "it was too fiddly".
2. The current implementation for SRIOV NICs cannot work with hardware version 20 and onwards, released with vSphere 8
Both problems have the same root cause. A very long time a go someone made the assumption that virtual network adapters are placed on the …

fix: support for sr-iov passthrough virtual machine network adapters

---

website/docs/r/virtual_machine.html.markdown

Updates the r/virtual_machine docs to include `sata_controller_count` and `scsi_controller_count`.
```release-note
`resource/virtual_machine`: Documentation update to include `sata_controller_count` and `scsi_controller_count` (GH-2147)
```
Closes #2146

docs: Update r/virtual_machine docs

---

vsphere/virtual_machine_guest_structure.go

Fixed bug, when network interfaces, created by docker, with the same deviceConfigId caused unexpected output.
For more information and steps to reproduce please refer the issue.
```
...
```
```release-note
...
```
Closes #2066

fix: select guest ips using MacAddress

---

vsphere/virtual_machine_config_structure.go

I'm removing the default values for `ept_rvi_mode` and `hv_mode` from the virtual machine configuration.
These properties are overwritten during the "read" phase and cause in uplace updates on the VM even if the configuration hasn't changed.
We should allow the vCenter to control the defaults instead of setting them ourselves
Ran `TestAccResourceVSphereVirtualMachine_basic`
Manually tested by applying the same confguration twice
```release-note
NONE
```
https://github.com/hashicorp/terraform-provider-vsphere/issues/1902

bugfix: Remove default values for ept_rvi_mode and hv_mode

---

.github/workflows/codeql-analysis.yml

- Workaround for Go 1.21 compatibility.
- Remove when GitHub Action runners Support Go 1.21+.

chore(ci): codeql-analysis with go1.21+

---

website/docs/d/guest_os_customization.html.markdown
website/docs/r/guest_os_customization.html.markdown

Corrected resource and data source links intended for `virtual_machine#virtual-machine-customizations` instead of `virtual-machine-customizations` on self.
Closes #2102

docs: guest customizations anchor link

---

website/docs/d/folder.html.markdown
website/docs/r/folder.html.markdown

Updates the `vsphere_folder` documentation.
- Clarifies as storage folder vs datastore folder.
- Removes unneeded interpolation.
Closes: #2020

docs: update `vsphere_folder`

---

vsphere/config.go

In general, vSphere is maving from SHA1 to SHA256-based TLS certificate thumbprints. This change allows the use of a SHA256 thumbprint when connecting to vCenter Server.
Support for SHA256 was added to `vmware/govmomi` v0.36.1.
Closes #2152
https://github.com/vmware/govmomi/commit/279963476f88c9853c9c867909e892b7296fa14b
https://github.com/vmware/govmomi/releases/tag/v0.36.1
https://github.com/hashicorp/terraform-provider-vsphere/pull/1808#issuecomment-1993057186

chore: update to sha256 for session file

---

vsphere/resource_vsphere_virtual_machine.go

Allows specifying a `datastore_cluster_id` for `vsphere_virtual_machine` when cloning from `vsphere_content_library_item`.
Closes #2055
https://kb.vmware.com/s/article/91103

fix: allow `datastore_cluster` for content library clones

---

CHANGELOG.md
vsphere/virtual_machine_config_structure.go

Reverts hashicorp/terraform-provider-vsphere#2172
We need to look for a way to fix ept_rvi_mode and hv_mode without causing disruption to running VMs
Related issue - https://github.com/hashicorp/terraform-provider-vsphere/issues/2193

Revert "bugfix: Remove default values for ept_rvi_mode and hv_mode"

---

.github/workflows/acceptance-tests.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/issue-opened.yml
.github/workflows/issue_greeting.yml
.github/workflows/milestone-closed.yml
.github/workflows/release.yml

Update transitive GitHub actions to trusted versions that use node 20.
Waiting on update for:

Use node20 in GH actions

---

website/docs/d/ovf_vm_template.html.markdown

This is supposed to use `ovfLocal` instead of `ovfRemote`.
- [N] Have you added an acceptance test for the functionality being added?
- [N] Have you run the acceptance tests on this branch?
```release-note
NONE
```

docs: use correct vm template's firmware in local OVF example

---

website/docs/index.html.markdown
website/docs/r/virtual_machine.html.markdown

- Adds additional informatation regarding the provider's `api_timeout` configuration option and includes a reference in `r/virtual_machine`.
- Corrects some old links. (more to come.)
Closes #2195

docs: update `api_timeout`

---

website/docs/d/ovf_vm_template.html.markdown
website/docs/r/virtual_machine.html.markdown

Updates the documentation for `d/ovf_vm_template` and `r/virtual_machine` to use a Ubuntu Server cloud image since the nested ESXi images are no longer available for direct download.
[Ubuntu Cloud Images](https://cloud-images.ubuntu.com/)

docs: update ova/ovf examples

---

vsphere/internal/helper/guestoscustomizations/customizations_helper.go
vsphere/internal/helper/viapi/vim_helper.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_test.go
vsphere/resource_vsphere_datastore_cluster.go
vsphere/resource_vsphere_resource_pool.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/virtual_machine_config_structure.go

Adds `// Minimum Supported Version: x.y.z` where there is a version restriction.
This is preparation for removing checks and to support only 7.0 and higher per the product lifecycle.

chore: version tracking

---

vsphere/resource_vsphere_virtual_machine.go

Updates `searchPath` to use `path` instead of `filepath` since this is a vSphere inventory path (e.g., `\Datacenter\vm\<vm_name>`), not a directory path.
```go
searchPath := ovfHelper.Name
if ovfHelper.Folder != nil && len(ovfHelper.Folder.InventoryPath) > 0 {
searchPath = path.Join(ovfHelper.Folder.InventoryPath, searchPath)
}
```
- Terraform v1.8.5
- VMware vSphere 8.0.2
🟢 **PASS**: Test on Windows 11 Pro, 22H2
```powershell
PS C:\Users\Owner\Desktop> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, …
```

fix: update searchPath

---

vsphere/resource_vsphere_file.go

Updates `r/file` to ensure that incoming file names with special characters (+, specifically) retain their original name when uploaded so that the plan is consistent.
```console
➜ terraform apply -auto-approve          
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_datastore.datastore: Reading...
data.vsphere_datastore.datastore: Read complete after 0s [id=datastore-18076]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
+ resource "vsphere_file" "iso" {
+ create_directories = true
+ datacenter         = "m01-dc01"
+ datastore          = "local-ssd-01"
+ …
```

fix: file names with special chars

---

vsphere/data_source_vsphere_virtual_machine_test.go
vsphere/resource_vsphere_virtual_machine_test.go
website/docs/d/guest_os_customization.html.markdown
website/docs/r/compute_cluster_vm_dependency_rule.html.markdown
website/docs/r/compute_cluster_vm_group.html.markdown
website/docs/r/compute_cluster_vm_host_rule.html.markdown
website/docs/r/datastore_cluster_vm_anti_affinity_rule.html.markdown
website/docs/r/drs_vm_override.html.markdown
website/docs/r/guest_os_customization.html.markdown
website/docs/r/ha_vm_override.html.markdown
website/docs/r/storage_drs_vm_override.html.markdown
website/docs/r/virtual_machine.html.markdown

- Adds examples for the use of guest customization specifications.
- Replaces default `guest_id` in examples with a more generic option.
Closes #2129

docs: customization spec examples

---

website/docs/r/compute_cluster_host_group.html.markdown
website/docs/r/compute_cluster_vm_dependency_rule.html.markdown
website/docs/r/compute_cluster_vm_group.html.markdown
website/docs/r/compute_cluster_vm_host_rule.html.markdown
website/docs/r/datastore_cluster.html.markdown
website/docs/r/datastore_cluster_vm_anti_affinity_rule.html.markdown
website/docs/r/dpm_host_override.html.markdown
website/docs/r/drs_vm_override.html.markdown
website/docs/r/ha_vm_override.html.markdown
website/docs/r/host_virtual_switch.html.markdown
website/docs/r/nas_datastore.html.markdown
website/docs/r/storage_drs_vm_override.html.markdown
website/docs/r/vapp_container.html.markdown
website/docs/r/vapp_entity.html.markdown

Removes deprecated interpolation syntax where it is no longer required.
**Example**
From:
```hcl
data "vsphere_host" "hosts" {
count         = "${length(var.hosts)}"
name          = "${var.hosts[count.index]}"
datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```
To:
```hcl
data "vsphere_host" "hosts" {
count         = length(var.hosts)
name          = var.hosts[count.index]
datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

docs: remove interpolation syntax

---

website/docs/d/compute_cluster_host_group.html.markdown
website/docs/d/content_library.html.markdown
website/docs/d/guest_os_customization.html.markdown
website/docs/d/host_vgpu_profile.html.markdown
website/docs/r/distributed_port_group.html.markdown
website/docs/r/distributed_virtual_switch.html.markdown
website/docs/r/folder.html.markdown
website/docs/r/vnic.html.markdown

Updated examples to use the correct syntax, formatting, and alignment with other examples in the docs.

docs: examples cleanup

---

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/resource_vsphere_virtual_machine.go

Usually when we reconfigure VMs we set negative integers as keys for new devices. vCenter assigns actual keys after the reconfiguration task completes which we then read and reassign to our resource.
This was not the case with PCI passthrough devices. No key was being assigned which meant that every such device got a zero as its key (the default integer value). This is fine if you're adding a single device but if you try with more than one the API fails.
The fix is simple - we simply need to assign a unique negative integer as the device key just like we do for other device types.
I had to manually test this one since it requires dedicated devices on the underlying hardware.
There is an important disclaimer to be made here - _adding PCI passthrough devices during VM creation does not …

fix: reconfigure vm with multiple pci passthrough devices

---

vsphere/resource_vsphere_virtual_disk.go
vsphere/resource_vsphere_virtual_disk_test.go
website/docs/r/virtual_disk.html.markdown

Increasing the size of a disk will no longer recreate it but modify it in-place.
Reductions in size are **not supported** by vCenter and will not be allowed.
The rest of the properties for `r/virtual_disk` are still marked with `ForceNew` and will continue to recreate the disk when changed.
Added a new test case for this scenario.
`r/virtual_disk`: Allow resizing of virtual disks
Closes #851

feat: allow resizing of virtual disks

---

CHANGELOG.md
vsphere/resource_vsphere_host.go
vsphere/resource_vsphere_host_test.go
website/docs/r/host.html.markdown

Added support for ntpd for services on `r/vsphere_host`. This allows for ntpd service settings and policy to be added to a host resource.
- `resource/host` - Added support for ntpd for services on `r/vsphere_host`. This allows for ntpd service settings and policy to be added to a host resource and future expansion of additional services.
Closes #1131

feat: add support for ntpd service on `r/vsphere_host`

---

CHANGELOG.md
vsphere/resource_vsphere_resource_pool.go

Removes the default setting for `scale_descendants_shares` to allows for inheritance from the parent resource pool.
```console
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereResourcePool_basic$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	1.069s
```
`resource/resource_pool` - Removes the default setting for `scale_descendants_shares` to allows for inheritance from the parent resource pool.
Closes #1763

fix: `r/resouce_pool` scaleable shares

---

CHANGELOG.md
website/docs/r/compute_cluster.html.markdown
website/docs/r/host.html.markdown
website/docs/r/virtual_machine.html.markdown

- Updates to clarify the import of `vsphere_hosts` resources.
- Updates to clarify the import of `vsphere_compute_cluster` resources.
- Updates to clarify the `vm` path in the import of `virtual_machine` resources.
* `resource/vsphere_host`: Updates to clarify the import of `vsphere_hosts` resources.
* `resource/vsphere_compute_cluster`: Updates to clarify the import of `vsphere_compute_cluster` resources.
* `resource/vsphere_virtual_machine`: Updates to clarify the `vm` path in the import of `virtual_machine` resources.
Closes #1555 
Closes #2253

docs: updated import `hosts`, `clusters`, and `virtual_machine`

---

CHANGELOG.md
vsphere/resource_vsphere_compute_cluster_vm_group.go
website/docs/r/compute_cluster_vm_group.html.markdown

Updates `r/sphere_compute_cluster_vm_group` to allow for additional virtual machines to be adding or removed from a VM Group.
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereComputeClusterVMGroup_basic$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	(cached)
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereComputeClusterVMGroup_update$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	(cached)
...
```
`r/sphere_compute_cluster_vm_group`: Updates to allow for additional virtual machines to be adding or removed from a VM Group.
Closes #1878

fix: add vm to existing vm group

---

CHANGELOG.md
vsphere/resource_vsphere_tag.go

Added validation to `vsphere_tag` to ensure `category_id` is a valid format.
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereTag_basic$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	(cached)
```
`resource\vsphere_tag`: Adds a format validation for `catagory_id`.
Closes #1680

feat: add validation for `category_id` in `r/vsphere_tag`

---

CHANGELOG.md
vsphere/resource_vsphere_tag_category.go

There was a bug that resulted in the tag being replaced when changing cardinality from Single to Multiple, I have remove the `ForceNew`.
```console
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereTagCategory_basic$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	(cached)
```
`r/vsphere_tag_category`: Updates resource not to `ForceNew` for cardinality. This will allow the `tag_category` to updated.
Closes #1959

fix: `r/vsphere_tag_category` cardinality

---

CHANGELOG.md
website/docs/r/resource_pool.html.markdown

Updated `resource/vsphere_resource_pool` documentation to show the steps for creating resource pool on standalone ESXi hosts
`resource/vsphere_resource_pool`: Updates to include steps to create resource pool on standalone ESXi hosts.
Closes #1846

docs: updated `resource_pool` for standalone hosts

---

CHANGELOG.md
vsphere/data_source_vsphere_host_thumbprint.go
vsphere/resource_vsphere_host.go
website/docs/d/host_thumbprint.html.markdown
website/docs/r/host.html.markdown

Adds validation of the ESXI host thumbprint before adding the host to a cluster or vCenter Server.
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_rootFolder$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.900s
```
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_connection$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.907s
```
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereHost_maintenance$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.950s
``` …

fix: `r/vsphere_host` thumbprint error

---

CHANGELOG.md
website/docs/r/host.html.markdown
website/docs/r/resource_pool.html.markdown
website/docs/r/virtual_machine.html.markdown

`resource/vsphere_virtual_machine`: Updates to fix examples of `disk0` to reflect that during import the disk get set back to default like `Hard Disk 1`.
Closes #2199

docs: `r/vsphere_virtual_machine` updated disks info

---

website/docs/r/virtual_machine.html.markdown

```release-note
Fix typo in disk arguments section of `vsphere_virtual_machine` resource docs.
```

Fix typo in virtual_machine.html.markdown

---

vsphere/data_source_vsphere_datastore_cluster.go
vsphere/data_source_vsphere_datastore_cluster_test.go
website/docs/d/datastore_cluster.html.markdown

Currently the datastore cluster object only returns the id of the cluster. There is need to access the children of the cluster ( like supported in the gui under the tab datastores). With this PR we will enable the filtering of datastores based on the cluster object
```shell
$ make testacc TESTARGS="-run=TestAccDataSourceVSphereDatastoreCluster_getDatastores"                                                                    
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereDatastoreCluster_getDatastores -timeout 360m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/admini …
```

feat: add datastore information under datastore cluster

---

vsphere/data_source_vsphere_datastore_stats.go
vsphere/data_source_vsphere_datastore_stats_test.go

With the previous introduction of `d/datastore_stats` only local datastores were included in the output. Now, all datastores are fetched, even those under clusters, by accessing every storage pod object and retrieving all datastores that are set as childs to it.
```
$ make testacc TESTARGS="-run=TestAccDataSourceVSphereDatastoreStats_basic"                                                
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereDatastoreStats_basic -timeout 360m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/administrationroles    [no test files]
? …
```

feat: add in-cluster datastores in `d/datastore_stats`

---

vsphere/data_source_vsphere_datacenter.go
vsphere/data_source_vsphere_datacenter_test.go
website/docs/d/datacenter.html.markdown

* Add a list of virtual machine names under the specified datacenter
There is a need to have a list of vm names in a datacenter. An example of it could be a number used as suffx for new vms, that depends on the names of the existing. In the GUI there is a tab with VMs in the datacenter view. So in the datasource datacenter a new attribute is added with `virtual_machines`.
```
$ make testacc TESTARGS="-run=TestAccDataSourceVSphereDatacenter_getVirtualMachines"                                                                                  
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereDatacenter_getVirtualMachines -timeout 360m
? …
```

feat: add `virtual_machines` list in `d/datacenter`

---

CHANGELOG.md
vsphere/data_source_vsphere_network.go
vsphere/internal/helper/network/network_helper.go
website/docs/d/network.html.markdown

Added the feature to allow for port group to be found if there are two port groups with the same name but one is standard virtual port group vs distributed virtual port group.
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccDataSourceVSphereNetwork_hostPortgroups$ github.com/hashicorp/terraform-provider-vsphere/vsphere
```
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.847s
```
...
```
```release-note
...
```
Closes #1143
Closes #1410

feat: d/vsphere_network add support for network_type

---

CHANGELOG.md
vsphere/data_source_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine.go
website/docs/d/virtual_machine.html.markdown
website/docs/r/virtual_machine.html.markdown

Added Support for vTPM on creation and clone of virtual machine.
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereVirtualMachine_basic$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	1.076s
```
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereVirtualMachine_hardwareVersionBare$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	0.981s
```
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestAccResourceVSphereVirtualMachine_addDevices$ github.com/hashicorp/terraform-provider-vsphere/vsphere
ok …
```

feat: add support for vtpm

---

README.md
website/docs/index.html.markdown

Removes specified VMware vSphere component links, which are subject to change by Broadcom.
Also removes reference to the prior "free ESXi license". Refer to [KB 2107518](https://knowledge.broadcom.com/external/article?legacyId=2107518).

docs: update landing docs

---

CHANGELOG.md
vsphere/distributed_virtual_switch_helper.go
vsphere/distributed_virtual_switch_structure.go

Adds 8.0.3 to the allowed `dvsVersions` to support vSphere 8.0 U3.

fix: add 8.0.3 to dvsVersions

---

vsphere/resource_vsphere_supervisor.go
website/docs/r/supervisor.html.markdown

Adds support for ntp_main and ntp_workers to the vsphere supervisor, 
the supervisor would not be able to create clusters without it.
They were already supported by govmomi so it was a simple change.
```
me@mymachine terraform-provider-vsphere % make testacc TESTARGS='-run=TestAccResourceVSphereSupervisor_basic' 
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVSphereSupervisor_basic -timeout 360m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/administrationroles	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/clustercomputeresource	[no …
```

feat: add support for ntp servers to r/vsphere_supervisor

---

go.mod
go.sum
vsphere/config.go

Updates the session file formatter string to `"%064x"` from `"%040x"` to match what will be in the next release of `vmware/govmomi`.
Ref: https://github.com/vmware/govmomi/pull/3683

chore: update session file format

---

CHANGELOG.md
website/docs/index.html.markdown

Release v2.11.1.
IMPROVEMENTS:
- `resource/vsphere_supervisor`: - Added support for `main_ntp` and `worker_ntp`. [(#2326](https://github.com/hashicorp/terraform-provider-vsphere/pull/23261))
-  Updates the session file formatter string to `"%064x"` from `"%040x"` to match `vmware/govc` v0.48.0 and later. [(#2329](https://github.com/hashicorp/terraform-provider-vsphere/pull/2329))
CHORE:
- `provider`: Updated `vmware/govmomi` to v0.48.0. ([#2325](https://github.com/terraform-providers/terraform-provider-vsphere/pull/2325), [#2329](https://github.com/terraform-providers/terraform-provider-vsphere/pull/2329))

chore(release): v2.11.1

---

go.mod
go.sum

The default values for `Session.config.KeepAliveInterval` and `Session.config.ConnectionWriteTimeou`t of 30s and 10s create the possibility for timed out writes that most aren't handling in their readers.
Ref: OSV reported vulnerability GHSA-29qp-crvh-w22m in github.com/hashicorp/yamux@v0.1.1

chore(deps): bump github.com/hashicorp/yamux from v0.1.1 to v0.1.2

---

vsphere/internal/helper/provider/provider_helper.go
vsphere/resource_vsphere_vmfs_datastore.go

Fixes #2249: Deleting datastores would fail before they were actually deleted, with an error like "Error: could not delete datastore: timeout while waiting for state to become 'retryDeleteCompleted' (timeout: 30s)"
Apologies for not creating an acceptance test but this was my first fix using Go, without knowing Go.
```
...
```
```release-note
...
```

fix: delete datastore

---

vsphere/internal/helper/customattribute/custom_attributes_helper.go

`GetDiffProcessorIfAttributesDefined` function is missing a `HasChange` check which is causing the provider to always update custom attributes regardless if there is a diff or not.
This may cause problems in some cases, such as when you want to restrict the permissions the terraform account has on vsphere. If the permissions are locked down you'll end up getting a permission denied error.
In our case we were not setting the `custom_attributes` parameter at all but the provider still tried to update the remote object which was causing the error:
```
[ERROR] vertex vsphere_virtual_machine.vm[0]" error: error setting attributes for object ID "vm-181897": ServerFaultCode: Permission to perform this operation was denied.
```
Release note for …

fix: `r/vsphere_virtual_machine` skip updating attributes if no diff

---

vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go
vsphere/internal/helper/network/network_helper.go
website/docs/d/network.html.markdown

When nsxt and vsphere configurations are applied in one go, we need a way to wait for nsxt network to be realized on VC, otherwise network data source will fail.
This change adds two parameters to network data source - `retry_timeout` and `retry_interval`. If `retry_timeout` is unset, there would be no change to the data source behavior. Otherwise data source will retry according to the specified parameters. Retry will only occur for `NotFound` error.
```
$ make testacc TESTARGS='-run=TestAccDataSourceVSphereNetwork_'
=== RUN   TestAccDataSourceVSphereNetwork_dvsPortgroup
--- PASS: TestAccDataSourceVSphereNetwork_dvsPortgroup (106.63s)
=== RUN   TestAccDataSourceVSphereNetwork_withTimeout
--- PASS: TestAccDataSourceVSphereNetwork_withTimeout (103.90s)
``` …

feat: support retry in `d/vsphere_network`

---

vsphere/host_network_policy_structure.go

N/A
```release-note
Fixed null reference panic when importing host port group resource
```
Closes #2355

fix: null checks for host network policies

---

.github/workflows/docs.yml
GNUmakefile
scripts/docscheck.sh

- Removes legacy `terraform-website` context from makefile.
- Updates options to check the documentation structure in the makefile.
- Adds options to check and fix the hcl formatting in the makefile.
- Adds workflow to check the structure and hcl formatting.
```shell
terraform-provider-vsphere on  chore(gh)/add-docs-workflow [✘!?] via 🐹 v1.24.2 
➜ make docs-check
==> Checking structure...
==> Done.
terraform-provider-vsphere on  chore(gh)/add-docs-workflow [✘!?] via 🐹 v1.24.2 took 2.9s 
➜ make docs-hcl-lint
GO111MODULE=on go install -mod=mod github.com/katbyte/terrafmt
go: finding module for package github.com/katbyte/terrafmt
==> Checking HCL formatting...
terraform-provider-vsphere on  chore(gh)/add-docs-workflow [✘!?] via 🐹 v1.24.2 
➜ make docs-hcl-fix 
GO111MODULE=on go install …
```

chore(gh): add docs workflow

---

.github/workflows/stale.yml

chore(gh): update stale workflow

---

vsphere/host_virtual_switch_structure.go

vCenter can occasionally rearrange the adapters on a host switch bond bridge structure. So far we've identified that this may occur after exiting maintenance mode.
The actual order of these adapters is not important, the significant ordering of active and standby nics is tracked on a separate policy structure on the switch configuration.
The vSphere UI also ignores ordering changes for this property and applies descending alphanumerical sorting.
I'm adding a diff supress function on the property that ignores ordering changes
N/A
I tested my changes by running existing tests and modifying the environment from outside terraform to trigger changes on the switch bond bridge
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob …

feat: add `DiffSuppressFunc` for `network_adapters` on r`/host_virtual_switch`

---

.golangci.yml
main.go
vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_guest_os_customization.go
vsphere/resource_vsphere_offline_software_depot.go
vsphere/resource_vsphere_virtual_machine_class.go

Fix file format.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/file-format]
vsphere/resource_vsphere_compute_cluster.go:1240:1: File is not properly formatted (gofmt)
for k, _ := range old {
^
main.go:7:1: File is not properly formatted (goimports)
"flag"
^
vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go:8:1: File is not properly formatted (goimports)
"github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/guestoscustomizations"
^
vsphere/resource_vsphere_guest_os_customization.go:7:1: File is not properly formatted (goimports)
"context"
^
vsphere/resource_vsphere_offline_software_depot.go:8:1: File is not properly formatted (goimports)
"errors"
^
vsphere/resource_vsphere_virtual_machine_class.go:7:1: File is not …
```

fix: file format

---

.golangci.yml
vsphere/data_source_vsphere_network.go
vsphere/internal/helper/network/network_helper.go

Refactors exported type name `network.NetworkNotFoundError` to `network.NotFoundError` to remove name stutter.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/exported-type-name-stutter]
vsphere/internal/helper/network/network_helper.go:27:6: exported: type name will be used as network.NetworkNotFoundError by other packages, and that stutters; consider calling this NotFoundError (revive)
type NetworkNotFoundError struct {
^
1 issues:
* revive: 1
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/exported-type-name-stutter]
0 issues.
```

fix: exported type name stutter

---

.golangci.yml
vsphere/resource_vsphere_compute_cluster.go

Fixes error string ending with punctuation.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/error-string-punctuation]
vsphere/resource_vsphere_compute_cluster.go:1864:26: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
return nil, fmt.Errorf("failed to get witness_node when removing witness!")
^
1 issues:
* revive: 1
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/error-string-punctuation]
0 issues.
```

fix: error string punctuation

---

.golangci.yml
vsphere/internal/helper/ovfdeploy/ovf_helper.go

Fixes unnecessary conversion.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/unnecessary-conversion]
vsphere/internal/helper/ovfdeploy/ovf_helper.go:192:28: unnecessary conversion (unconvert)
absoluteFilePath = string(filePath[0 : strings.LastIndex(filePath, string(os.PathSeparator))+1])
^
vsphere/internal/helper/ovfdeploy/ovf_helper.go:215:28: unnecessary conversion (unconvert)
absoluteFilePath = string(filePath[0 : strings.LastIndex(filePath, "/")+1])
^
2 issues:
* unconvert: 2
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/unnecessary-conversion]
0 issues.
```

fix: unnecessary conversion

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/virtual_machine_config_structure.go

Replaced explicit boolean comparisons like `if condition == true` with the simpler and more idiomatic Go form `if condition`. This improves code readability and adheres to standard Go conventions.

refactor: simplify boolean comparisons in conditions

---

.golangci.yml
vsphere/resource_vsphere_virtual_machine_class_test.go

Fixes unnecessary use of `fmt.Sprint`.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/staticcheck-S1039]
vsphere/resource_vsphere_virtual_machine_class_test.go:42:9: S1039: unnecessary use of fmt.Sprintf (staticcheck)
return fmt.Sprintf(`
^
vsphere/resource_vsphere_virtual_machine_class_test.go:53:9: S1039: unnecessary use of fmt.Sprintf (staticcheck)
return fmt.Sprintf(`
2 issues:
* staticcheck: 2
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/staticcheck-S1039]
0 issues.
```

fix: staticcheck S1039

---

vsphere/internal/helper/contentlibrary/content_library_helper.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go

This pull request introduces changes to improve file path handling by ensuring all file paths are sanitized using `filepath.Clean`. This helps prevent potential issues with malformed or unsafe paths.
Improvements to file path handling:
* `vsphere/internal/helper/contentlibrary/content_library_helper.go`:
- Added `filepath.Clean` to sanitize the input file path in the `openLocalFile` function.
* `vsphere/internal/helper/ovfdeploy/ovf_helper.go`:
- Added `filepath.Clean` to sanitize file paths in the following functions:
- `uploadDisksFromLocal` for cleaning the `vmdkFilePath`.
- `GetOvfDescriptor` for cleaning `filePath` when reading the OVF descriptor from a local file. [[1]](diffhunk://#diff-26b5fa249e72aa266e3b5c47124d3ea8bb5e2aa26cc61869e378b4b6dc5b63adR273) …

refactor: clean file paths

---

vsphere/internal/helper/contentlibrary/content_library_helper.go

Improves error handling and resource management in the `uploadOvaDisksFromURL` function. The changes enhance the clarity of error messages and ensure proper cleanup of HTTP response resources.
Error handling improvements:
* Enhanced error messages to include more context, such as the URL and specific errors encountered during the HTTP GET request and OVA data processing.
Resource management:
* Added a `defer resp.Body.Close()` statement to ensure the HTTP response body is properly closed, preventing potential resource leaks.

refactor: http get request handling

---

vsphere/resource_vsphere_virtual_machine_test.go

Replaced tagless `switch` statements (where each case contains a full boolean comparison) with `switch` statements that evaluate an expression.
This pattern is more idiomatic and often more readable when comparing a single variable against multiple constant values, as it avoids repeating the variable name in each case.

refactor: use switch expression over tagless switch

---

vsphere/internal/helper/guestoscustomizations/customizations_helper.go

Replaced the if-else if chain checking `specItem.Info.Type` with a switch statement.
Using `switch` on the type variable is more idiomatic Go and often improves readability when dispatching logic based on the value of a single variable, especially when more cases might be added later.

refactor: use switch statement for os customization type

---

vsphere/host_data_store_system_helper.go

Refactored loops in `availableScsiDisk` and `diskSpecForCreate` to correctly obtain pointers to slice elements.
Previously, the code was taking the address of the loop iteration variable (e.g., `&d`), which is unsafe as the variable is reused. The loops now access the element directly from the slice by index (e.g., `&disks[i]`) before taking the address, ensuring the pointer references the correct underlying data.

fix: avoid taking address of loop variables

---

vsphere/data_source_vsphere_host_base_images.go

This pull request refactors the `dataSourceVSphereHostBaseImagesRead` function in `vsphere/data_source_vsphere_host_base_images.go` to improve readability and error handling. The changes primarily involve restructuring the code to eliminate the use of an inline `if-else` statement and ensure a cleaner flow.
* Replaced the inline `if-else` statement with separate variable assignment and error handling for the `ListBaseImages` method. This improves code clarity and separates concerns for better readability.
* Removed an unnecessary closing brace at the end of the function, simplifying the code structure.

refactor: host base images drop else and outdent

---

vsphere/resource_vsphere_offline_software_depot.go
vsphere/resource_vsphere_offline_software_depot_test.go

Refactors error handling to simplify the code and improve readability.
The changes involve removing unnecessary else blocks following error returns and restructuring the code for better clarity.
* Refactored error-handling in `resourceVsphereOfflineSoftwareDepotCreate`, `resourceVsphereOfflineSoftwareDepotRead`, and `resourceVsphereOfflineSoftwareDepotDelete` functions to use a linear structure instead of nested `if-else` blocks, improving readability. (`vsphere/resource_vsphere_offline_software_depot.go`: [[1]](diffhunk://#diff-82e43dd65758c12fe69acba711cc17ca00a38de664e60e71dbd0f65bbb170a51L71-R85) [[2]](diffhunk://#diff-82e43dd65758c12fe69acba711cc17ca00a38de664e60e71dbd0f65bbb170a51L86-L99) [[3]](diffhunk://#diff-82e43dd65758c12fe69acba711cc17ca00a38de664e60e71dbd0f65bbb170a51L109-R119 …

refactor: software depot drop else and outdent

---

vsphere/host_virtual_switch_structure.go

Adds nil pointer checks in the host virtual swtich structure to prevent a runtime panic when the function is called with a nil result.
Closes #2308

fix: add nil checks to host-vswitch

---

vsphere/config.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/internal/helper/viapi/vim_helper.go
vsphere/resource_vsphere_datacenter.go
vsphere/resource_vsphere_file.go

Refactored multiple instances where methods or fields were accessed through an intermediate field (e.g., `obj.Common.Reference()`). These have been simplified to use direct access where applicable.

refactor: simplify access to methods/fields via direct calls

---

vsphere/resource_vsphere_resource_pool.go

Adds `reconcileScaleDescendantsShares` to reconcile the scale descendants shares setting for a resource pool.

fix: reconcile scale descendants shares 

---

vsphere/resource_vsphere_virtual_machine.go

Fixes a nil pointer dereference in `resourceVSphereVirtualMachineRead `when both `ParentVApp` and `ResourcePool` are `nil`. The now safely checks for `nil` before accessing `.Value`, and explicitly sets `vmContainer` to an empty string if neither is present.
Closes #2304
Ref: #2304, #2305

fix: prevent panic when both `ParentVApp` and `ResourcePool` are nil

---

.golangci.yml
vsphere/data_source_vsphere_datacenter.go
vsphere/distributed_virtual_switch_helper.go

Fixes error not checked identified by `golangci-lint`.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/error-not-checked]
vsphere/data_source_vsphere_datacenter.go:53:20: Error return value of `view.Destroy` is not checked (errcheck)
defer view.Destroy(ctx)
^
vsphere/distributed_virtual_switch_helper.go:176:11: Error return value of `task.Wait` is not checked (errcheck)
task.Wait(tctx)
^
2 issues:
* errcheck: 2
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/error-not-checked]
0 issues.
```

fix: error not checked

---

docs/resources/file.md
vsphere/resource_vsphere_file.go
vsphere/resource_vsphere_file_test.go

- Refactors the `deleteFile` function, reducing the code duplication in the task execution and waiting logic.
- Adds comments for file resource functions, including test functions.
- Moves supporting functions below the CRUD functions.
- Adds description to the file resource schema.
- Update the file resource documentation.
**Note**: Revisit this resource with a transition to `terraform-plugin-log` and potentionally move supporting functions to a helper.

refactor: file resource

---

.github/workflows/milestone-closed.yml

- Update workflow permissions.
- Update URL.
Output:

chore(gh): update milestone closed workflow

---

.golangci.yml
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_virtual_machine.go

Fix ineffectual assignment.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/ineffectual-assignment]
vsphere/resource_vsphere_compute_cluster.go:1762:5: ineffectual assignment to hostIds (ineffassign)
hostIds = append(hostIds.([]string), vsanHost.HostSystem.Value)
^
vsphere/resource_vsphere_virtual_machine.go:1657:2: ineffectual assignment to devices (ineffassign)
devices, delta, err = virtualdevice.NormalizeBus(devices, d)
^
2 issues:
* ineffassign: 2
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[fix/ineffectual-assignment]
0 issues.
```

fix: ineffectual assignment

---

go.mod
vsphere/data_source_vsphere_license.go
vsphere/internal/helper/license/license_helper.go
vsphere/resource_vsphere_license.go
vsphere/resource_vsphere_license_test.go

> [!IMPORTANT]
> **TESTED AND READY** 
Refactors `r/license` and `d/license`.
Introduces the use of `hashicorp/terraform-plugin-log` for logging.
And ensures that the license key is not leaked in logs by masking the key in the following form: 
```shell
License operation: Reading license data source: key_length=29 masked_key="XXXX*********************XXXX" tf_rpc=ReadDataSource @module=provider tf_data_source_type=vsphere_license tf_provider_addr=provider tf_req_id=06693533-cf1d-86bd-d167-dcd9189f212a @caller=F:/GitHub/terraform-provider-vsphere/vsphere/internal/helper/license/license_helper.go:36 timestamp="2025-05-01T20:58:11.962+0100"
```

refactor: license resource and data source

---

vsphere/data_source_vsphere_dynamic.go
vsphere/data_source_vsphere_dynamic_test.go
vsphere/data_source_vsphere_role_test.go
vsphere/internal/helper/guestoscustomizations/customizations_helper.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/provider.go
vsphere/resource_vsphere_compute_cluster.go
vsphere/resource_vsphere_compute_cluster_vm_group.go
vsphere/resource_vsphere_distributed_virtual_switch_pvlan_mapping_test.go
vsphere/resource_vsphere_offline_software_depot.go
vsphere/resource_vsphere_role.go
vsphere/resource_vsphere_role_test.go
vsphere/resource_vsphere_supervisor.go
vsphere/resource_vsphere_supervisor_test.go
vsphere/resource_vsphere_vapp_container_test.go
vsphere/resource_vsphere_virtual_machine.go
vsphere/resource_vsphere_virtual_machine_class.go
vsphere/resource_vsphere_virtual_machine_class_test.go
vsphere/resource_vsphere_virtual_machine_test.go
vsphere/resource_vsphere_vm_storage_policy.go
vsphere/resource_vsphere_vnic.go

Rename variables based on idiomatic principles, per `revive` and `golangci-lint`.
```shell
~/Downloads/terraform-provider-vsphere git:[fix/revive-var-naming]
0 issues.
```

fix: revive var-naming

---

CHANGELOG.md
docs/data-sources/ovf_vm_template.md
docs/resources/virtual_machine.md

Clarifies the `disk_provisioning` argument options.
[Reference](https://github.com/vmware/govmomi/blob/d2fecb683891ca1ffeaea8fd18912c3b87938977/vim25/types/enum.go#L9323-L9367).
Updating to:
```markdown
* `disk_provisioning` - (Optional) The disk provisioning type.
If set, all the disks included in the OVF/OVA will have the same specified policy.
One of `thin`, `thick`, `eagerZeroedThick`, or `sameAsSource`.
* `thin`: Each disk is allocated and zeroed on demand as the space is used.
* `thick`: Each disk is allocated at creation time and the space is zeroed on demand as the space is used.
* `eagerZeroedThick`: Each disk is allocated and zeroed at creation time.
* `sameAsSource`: Each disk will have the same disk type as the source.
```
Output:
Resolves #2479

docs: clarify `disk_provisioning` options

---

docs/data-sources/resource_pool.md
vsphere/data_source_vsphere_resource_pool.go
vsphere/data_source_vsphere_resource_pool_test.go
vsphere/internal/helper/resourcepool/resource_pool_helper.go

> [!NOTE]
> **TESTED AND READY** 
Enhances the functionality of the `d/resource_pool` by introducing support for finding child resource pools using `parent_resource_pool_id`. It also includes updates to the documentation, new helper methods, and additional test cases to validate the changes.
* Added a new optional argument, `parent_resource_pool_id`, to specify the parent resource pool's ID when searching for a child resource pool. The `name` argument must now be a simple name (not a path) when used with this new parameter. (`vsphere/data_source_vsphere_resource_pool.go`, [vsphere/data_source_vsphere_resource_pool.goR7-R96](diffhunk://#diff-fba432a0d0c3dde38a9688fc432f35ce6b1caef4a4a021d54f9e88afe0642e69R7-R96))
* Updated the `dataSourceVSphereResourcePoolRead` function to handle the new …

feat: add `parent_resource_pool_id` to `d/resource_pool`

---

.golangci.yml
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go

Resolves `golangci-lint` identified issues for S1040: type assertion to the same type.
Before:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1040 via 🐹 v1.24.3 took 7.4s 
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go:771:10: S1040: type assertion to the same type: ctlrs[0] already has type types.BaseVirtualSCSIController (staticcheck)
last := ctlrs[0].(types.BaseVirtualSCSIController).GetVirtualSCSIController().SharedBus
^
vsphere/internal/virtualdevice/virtual_machine_device_subresource.go:773:21: S1040: type assertion to the same type: ctlr already has type types.BaseVirtualSCSIController (staticcheck)
if ctlr == nil || ctlr.(types.BaseVirtualSCSIController).GetVirtualSCSIController().SharedBus != last {
^
2 issues:
* …
```

fix: staticcheck S1040

---

.golangci.yml
vsphere/resource_vsphere_virtual_machine.go

Resolves `golangci-lint` identified issues for S1017: `replace this if statement with an unconditional strings.TrimSuffix`.
Before:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1017 via 🐹 v1.24.3 took 14.3s 
vsphere/resource_vsphere_virtual_machine.go:1091:5: S1017: should replace this if statement with an unconditional strings.TrimSuffix (staticcheck)
if strings.HasSuffix(k, ".#") {
^
1 issues:
```
After:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1017 via 🐹 v1.24.3 took 14.3s 
0 issues.
```
Output:

fix: staticcheck S1017

---

.golangci.yml
vsphere/internal/helper/structure/structure_helper.go

Resolves `golangci-lint` identified issues for QF1005: `could expand call to math.Pow `.
Ref: [QF1005](https://staticcheck.dev/docs/checks#QF1005)
Before:
```shell
terraform-provider-vsphere on  fix/staticcheck-QF1005 [$] via 🐹 v1.24.3  
vsphere/internal/helper/structure/structure_helper.go:274:45: QF1005: could expand call to math.Pow (staticcheck)
return int(math.Ceil(float64(n.(int64)) / math.Pow(1024, 3)))
^
vsphere/internal/helper/structure/structure_helper.go:286:24: QF1005: could expand call to math.Pow (staticcheck)
return int64(v * int(math.Pow(1024, 3)))
^
vsphere/internal/helper/structure/structure_helper.go:288:26: QF1005: could expand call to math.Pow (staticcheck)
return int64(v * int32(math.Pow(1024, 3)))
^ …
```

fix: staticcheck QF1005

---

.golangci.yml
vsphere/internal/helper/contentlibrary/content_library_helper.go
vsphere/resource_vsphere_content_library_item_test.go

Replace direct `http.Get()` calls with `http.Client` and explicit `http.NewRequest` to address G107 warnings (Potential HTTP request made with variable URL).
Before:
```shell
terraform-provider-vsphere on  fix/gosec-G107 [$!] via 🐹 v1.24.3 took 3.9s 
vsphere/internal/helper/contentlibrary/content_library_helper.go:373:15: G107: Potential HTTP request made with variable url (gosec)
resp, err := http.Get(ovfFilePath)
^
vsphere/resource_vsphere_content_library_item_test.go:147:15: G107: Potential HTTP request made with variable url (gosec)
resp, err := http.Get(url)
^
2 issues:
* gosec: 2
```
After:
```shell
terraform-provider-vsphere on  fix/gosec-G107 [$] via 🐹 v1.24.3 took 2.3s 
0 issues.
```
Output:
```shell
Running tool: /usr/local/bin/go test …
```

fix: address G107 gosec warnings in HTTP requests

---

.golangci.yml
vsphere/data_source_vsphere_host_thumbprint.go
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/resource_vsphere_host.go

- Enforce TLS 1.2 or higher.
- Ignored the use of `InsecureSkipVerify` as this is for the non-default `allow_unverified_ssl` provider configuration option.
> [!IMPORTANT]
>
> VMware vSphere 7.0:
> - TLS 1.2 is enabled by default.
> - TLS 1.0 and TLS 1.1 are disabled by default. 
> - You can use the TLS Configurator utility to enable older versions of the protocol temporarily. You can then disable the older less secure versions after all connections use TLS 1.2.  
>
> VMware vSphere 8.0:
> - TLS 1.2 is enabled by default.
> - Cannot be downgraded to support TLS 1.0 or 1.1.
```shell
PS F:\Code\test\host> terraform plan
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/vsphere in …
```

fix: gosec g402

---

vsphere/distributed_virtual_port_setting_structure.go
vsphere/host_network_policy_structure.go
vsphere/internal/helper/structure/structure_helper.go

Refactors the use of the deprecated `GetOkExists`.
```shell
PS F:\Code\test\host> terraform apply --auto-approve  
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/vsphere in C:\Users\Administrator\go\bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_distributed_virtual_switch.vds: Reading...
data.vsphere_distributed_virtual_switch.vds: Read complete after 0s [id=50 1f 6c 23 08 f6 4b 4d-1e 16 86 da 3b 52 42 36]
Terraform used …
```

refactor: use of deprecated `GetOkExists`

---

docs/resources/datastore_cluster.md
tests/run_tests.sh
vsphere/data_source_vsphere_compute_cluster_host_group_test.go
vsphere/data_source_vsphere_compute_cluster_test.go
vsphere/data_source_vsphere_datacenter_test.go
vsphere/data_source_vsphere_datastore_cluster_test.go
vsphere/data_source_vsphere_datastore_stats_test.go
vsphere/data_source_vsphere_distributed_virtual_switch_test.go
vsphere/data_source_vsphere_dynamic_test.go
vsphere/data_source_vsphere_guest_os_customization_test.go
vsphere/data_source_vsphere_host_test.go
vsphere/data_source_vsphere_host_thumbprint_test.go
vsphere/data_source_vsphere_network_test.go
vsphere/data_source_vsphere_resource_pool_test.go
vsphere/data_source_vsphere_role_test.go
vsphere/data_source_vsphere_tag_test.go
vsphere/data_source_vsphere_vapp_container_test.go
vsphere/data_source_vsphere_virtual_machine_test.go
vsphere/data_source_vsphere_vmfs_disks_test.go
vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
vsphere/resource_vsphere_datastore_cluster.go
vsphere/resource_vsphere_resource_pool.go

Rework data source tests so that they work on the default testbed and mark as enabled
<details>
✅ TestAccDataSourceVSphereComputeClusterHostGroup_basic (56.36s)
✅ TestAccDataSourceVSphereComputeCluster_absolutePathNoDatacenter (1m11.89s)
✅ TestAccDataSourceVSphereComputeCluster_basic (50.31s)
✅ TestAccDataSourceVSphereContentLibrary_basic (59.16s)
✅ TestAccDataSourceVSphereCustomAttribute_basic (45.3s)
✅ TestAccDataSourceVSphereDatacenter_basic (44.35s)
✅ TestAccDataSourceVSphereDatacenter_defaultDatacenter (44.65s)
✅ TestAccDataSourceVSphereDatacenter_getVirtualMachines (44.42s)
✅ TestAccDataSourceVSphereDatastoreCluster_absolutePathNoDatacenter (54.81s)
✅ TestAccDataSourceVSphereDatastoreCluster_basic …

refactor: stabilize and enable data source tests

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

This pull request simplifies the `ValidateDiff` method in the `NetworkInterfaceSubresource` by removing redundant bandwidth restriction logic for non-SR-IOV network interfaces. The most important changes include deleting the `restrictResourceAllocationSettings` method and its associated calls, which were no longer necessary.
Simplification of `ValidateDiff` method:
* Removed the call to `restrictResourceAllocationSettings` for non-SR-IOV network interfaces. This eliminates unnecessary checks for bandwidth-related settings when the adapter type is not SR-IOV. (`vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go`, [vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.goL1197-L1202](diffhunk://#diff-e8de2d20cbf49f2db545eafc50b5230673e692740 …

chore: remove network interface resource allocation gate

---

vsphere/host_network_policy_structure.go
vsphere/resource_vsphere_compute_cluster_host_group_test.go
vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go
vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go
vsphere/resource_vsphere_compute_cluster_vm_group_test.go
vsphere/resource_vsphere_custom_attribute_test.go
vsphere/resource_vsphere_datacenter_test.go
vsphere/resource_vsphere_datastore_cluster_test.go
vsphere/resource_vsphere_distributed_port_group_test.go
vsphere/resource_vsphere_distributed_virtual_switch_pvlan_mapping_test.go
vsphere/resource_vsphere_distributed_virtual_switch_test.go
vsphere/resource_vsphere_dpm_host_override_test.go
vsphere/resource_vsphere_drs_vm_override_test.go
vsphere/resource_vsphere_entity_permissions_test.go
vsphere/resource_vsphere_file_test.go
vsphere/resource_vsphere_folder_test.go
vsphere/resource_vsphere_guest_os_customization_test.go
vsphere/resource_vsphere_ha_vm_override_test.go
vsphere/resource_vsphere_host_port_group_test.go
vsphere/resource_vsphere_host_test.go
vsphere/resource_vsphere_host_virtual_switch.go
vsphere/resource_vsphere_resource_pool_test.go
vsphere/resource_vsphere_role_test.go
vsphere/resource_vsphere_tag_category_test.go
vsphere/resource_vsphere_vapp_container_test.go
vsphere/resource_vsphere_vapp_entity_test.go
vsphere/resource_vsphere_virtual_disk_test.go
vsphere/resource_vsphere_virtual_machine_test.go

Enabling more acceptance tests. The total number of stable tests is now 129 which accounts for around 1/3 of all tests.
<details>
✅ TestAccDataSourceVSphereComputeClusterHostGroup_basic (59.11s)
✅ TestAccDataSourceVSphereComputeCluster_absolutePathNoDatacenter (1m13.09s)
✅ TestAccDataSourceVSphereComputeCluster_basic (50.54s)
✅ TestAccDataSourceVSphereContentLibrary_basic (1m0.36s)
✅ TestAccDataSourceVSphereCustomAttribute_basic (45.63s)
✅ TestAccDataSourceVSphereDatacenter_basic (46.76s)
✅ TestAccDataSourceVSphereDatacenter_defaultDatacenter (45.35s)
✅ TestAccDataSourceVSphereDatacenter_getVirtualMachines (44.91s)
✅ TestAccDataSourceVSphereDatastoreCluster_absolutePathNoDatacenter (1m3.5s)
✅ …

refactor: enable more acceptance tests

---

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
vsphere/resource_vsphere_virtual_machine_test.go

Allow for the creation of VMs using existing 2gb sparse disks.
Added an acceptance test with instructions how to prepare the testing environment.
The test is disabled by default.
```
✅ TestAccResourceVSphereVirtualMachine_addDevices (1m56.92s)
✅ TestAccResourceVSphereVirtualMachine_basic (1m26.03s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionBare (1m18.51s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionClone (2m1.26s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionUpgrade (2m5.53s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitNumbers (1m27.91s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitsToRegularSingleController (2m20.41s)
✅ TestAccResourceVSphereVirtualMachine_ignoreValidationOnComputedValue (42.62s)
✅ …
```

feat: attach sparse `.vmdk` when creating `r/virtual_machine`

---

.github/workflows/golangci-lint.yml
vsphere/internal/helper/storagepod/storage_pod_helper.go

Using a fixed version of `golangci-lint` instead of `latest`.
The last version that the lint status was verified with was 2.1.6 and I'm using that as the new setting.
This should prevent new issues from appearing as the linter evolves and we can update its version along with any affected code manually.
Output:

chore: set golangci-lint version to v2.1.6

---

docs/resources/virtual_machine.md

Fixes a broken documentation link in `docs/resources/virtual_machine.md`.
Old URL "/docs/providers/vsphere/d/resource_pool#specifying-the-root-resource-pool-for-a-standalone-host"
returned **404** because it referenced the Markdown path and missed the correct anchor slug.
New URL  "/docs/providers/vsphere/d/resource_pool.html#specifying-the-root-resource-pool-for-a-standalone-esxi-host" points to the rendered HTML page and correct section.
Output:
docs: fixed broken link to “Specifying the Root Resource Pool” section in virtual_machine resource docs.

docs(virtual_machine): fix broken link to “Specifying the Root Resource Pool”

---

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go

Changes to static MAC addresses should be applied as long as `use_static_mac` is set to true, instead of only when its value changes
<details>
<summary>Automated test run results</summary>
```
Pending
```
</details>
Fixes https://github.com/vmware/terraform-provider-vsphere/issues/2549
```
- `r/virtual_machine` - Fix MAC address reconfiguration . (#2549)
```

fix: update static mac when reconfiguring vm

---

vsphere/internal/helper/storagepod/storage_pod_helper.go
vsphere/resource_vsphere_virtual_machine.go

Starting with `v2.14.0` it is not possible to clone a virtual machine on a cluster which has storage DRS turned on if the configuration for the new machine does not include at least one additional hard disk.
This problem was introduced by me with https://github.com/vmware/terraform-provider-vsphere/pull/2550
The fix is to not attempt to apply SDRS recommendations if no new disks are being added.
Deleted unused code in `storage_pod_helper.go`
Verified that I can clone a virtual machine on a storage DRS-enabled cluster
1. Without adding any new disks
2. With multiple additional disks
<details>
<summary>Automated test run results</summary>
```
✅ TestAccResourceVSphereVirtualMachine_addDevices (21.29s)
✅ …
```

fix: server fault when cloning VM on DRS-enabled cluster

---

docs/resources/virtual_machine.md
vsphere/internal/helper/ovfdeploy/ovf_helper.go
vsphere/resource_vsphere_virtual_machine_test.go

Output:
✅ TestAccResourceVSphereVirtualMachine_addDevices (20.09s)
✅ TestAccResourceVSphereVirtualMachine_basic (58.93s)
✅ TestAccResourceVSphereVirtualMachine_deployOvaFromUrl (26.52s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionBare (7.57s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionClone (52.54s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionUpgrade (22.17s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitNumbers (13.53s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitsToRegularSingleController (27.55s)
✅ TestAccResourceVSphereVirtualMachine_ignoreValidationOnComputedValue (1.91s)
✅ TestAccResourceVSphereVirtualMachine_moveToFolder (14.34s)
✅ TestAccResourceVSphereVirtualMachine_multiDevice …

feat: support deploying OVA without specifying host_system_id

---

docs/data-sources/network.md
vsphere/data_source_vsphere_network.go
vsphere/data_source_vsphere_network_test.go
vsphere/internal/helper/network/network_helper.go
vsphere/internal/helper/testhelper/testing.go

Network datasource has a capability to find a network which belongs to NSX default project.
But VPC subnets can be nested under different project, and as network names are not unique, it is required to use the project id as part of the network identification.
Output:
```
=== RUN   TestAccDataSourceVSphereNetwork_dvsPortgroup
--- PASS: TestAccDataSourceVSphereNetwork_dvsPortgroup (147.31s)
=== RUN   TestAccDataSourceVSphereNetwork_withTimeout
--- PASS: TestAccDataSourceVSphereNetwork_withTimeout (147.16s)
=== RUN   TestAccDataSourceVSphereNetwork_absolutePathNoDatacenter
--- PASS: TestAccDataSourceVSphereNetwork_absolutePathNoDatacenter (138.68s)
=== RUN   TestAccDataSourceVSphereNetwork_hostPortgroups
--- PASS: TestAccDataSourceVSphereNetwork_hostPortgroups (129.20s)
=== RUN …
```

Add support for project VPCs in network data source
