vmware/terraform-provider-vsphere

vsphere/provider.go, vsphere/resource_vsphere_datacenter.go, vsphere/resource_vsphere_datacenter_test.go, website/docs/r/datacenter.html.markdown, website/vsphere.erb
Add a new resource ```vsphere_datacenter```, used as the primary container for many objects, including all the current resources for this provider.
Tested on vSphere 6.5.
=> Enhancement: New resource datacenter

vendor/github.com/vmware/govmomi/event/history_collector.go, vendor/github.com/vmware/govmomi/event/manager.go, vendor/github.com/vmware/govmomi/event/processor.go, vendor/github.com/vmware/govmomi/event/sort.go, vendor/github.com/vmware/govmomi/view/container_view.go, vendor/github.com/vmware/govmomi/view/list_view.go, vendor/github.com/vmware/govmomi/view/manager.go, vendor/vendor.json
This is required for proper handling of VM customization events, to
ensure that we are waiting for customization when we need it.
=> vendor: add govmomi/event@v0.15.0

vendor/github.com/hashicorp/terraform/config/append.go, vendor/github.com/hashicorp/terraform/config/config.go, vendor/github.com/hashicorp/terraform/config/interpolate_funcs.go, vendor/github.com/hashicorp/terraform/config/merge.go, vendor/github.com/hashicorp/terraform/helper/resource/testing.go, vendor/github.com/hashicorp/terraform/helper/resource/testing_import_state.go, vendor/github.com/hashicorp/terraform/terraform/diff.go, vendor/github.com/hashicorp/terraform/terraform/eval_apply.go, vendor/github.com/hashicorp/terraform/terraform/resource.go, vendor/github.com/hashicorp/terraform/terraform/resource_address.go, vendor/github.com/hashicorp/terraform/terraform/version.go, vendor/vendor.json
So that we can use the new `ImportStateIdFunc` helper.
=> vendor: Update TF to v0.10.5

vsphere/resource_vsphere_virtual_machine.go
The current gateway discovery code makes an assumption that any device
tracked by VMware tools that is not virtual hardware on the instance
will be ordered after any devices that are (even though the device key
is properly being used as the source of truth when discovering
interfaces). It does this by using the device index in a specific
gateway entry as the literal index entry for the corresponding device in
the list of devices that have actually been counted for saving in
Terraform state. This will either point to the incorrect device or a
flat out out-of-bounds value, respectively causing incorrect diffs or
crashes.
This fixes the situation by searching for the actual device key in the
guest network information discovered by VMware tools - at the index
specified by the gateway entry, …
=> r/virutal_machine: Fix gateway discovery behavior

website/docs/d/tag.html.markdown
Was missing a curly, guess I didn't run it through `terraform fmt`. :P
=> docs: Fix vsphere_tag data source example syntax

CHANGELOG.md
thanks for releasing distributed vswitch support!
really needed that for a project we're doing.
=> fix typo in the changelog

vsphere/host_virtual_switch_structure.go, vsphere/resource_vsphere_host_virtual_switch.go, vsphere/resource_vsphere_host_virtual_switch_test.go
This is basically done in vSphere by supplying no bridge to the config
spec - in our configuration, we were passing the bridge with zero nics,
which is an invalid configuration.
This change just nils out the bridge after expansion if there are no
NICs. We have also added some diff-time validation to make sure that any
NIC specified in the active or standby list is a NIC configured on the
bridge to avoid errors at apply time.
Fixes #210.
=> r/host_virtual_switch: Support a switch with no NICs

website/docs/d/resource_pool.html.markdown
Just add a little language so that it's easier to notice.
=> d/resource_pool: Make standalone ESXi section a bit clearer

vendor/github.com/hashicorp/terraform/config/config.go, vendor/github.com/hashicorp/terraform/config/configschema/nestingmode_string.go, vendor/github.com/hashicorp/terraform/config/interpolate_funcs.go, vendor/github.com/hashicorp/terraform/config/module/storage.go, vendor/github.com/hashicorp/terraform/config/module/tree.go, vendor/github.com/hashicorp/terraform/config/resource_mode_string.go, vendor/github.com/hashicorp/terraform/helper/resource/testing.go, vendor/github.com/hashicorp/terraform/helper/resource/testing_config.go, vendor/github.com/hashicorp/terraform/helper/schema/getsource_string.go, vendor/github.com/hashicorp/terraform/helper/schema/valuetype_string.go, vendor/github.com/hashicorp/terraform/registry/client.go, vendor/github.com/hashicorp/terraform/registry/regsrc/friendly_host.go, vendor/github.com/hashicorp/terraform/registry/regsrc/module.go, vendor/github.com/hashicorp/terraform/terraform/context.go, vendor/github.com/hashicorp/terraform/terraform/eval_output.go, vendor/github.com/hashicorp/terraform/terraform/features.go, vendor/github.com/hashicorp/terraform/terraform/graphtype_string.go, vendor/github.com/hashicorp/terraform/terraform/instancetype_string.go, vendor/github.com/hashicorp/terraform/terraform/resource_provider_mock.go, vendor/github.com/hashicorp/terraform/terraform/transform_provider.go, vendor/github.com/hashicorp/terraform/terraform/walkoperation_string.go, vendor/github.com/hashicorp/terraform/tfdiags/severity_string.go, vendor/github.com/hashicorp/terraform/version/version.go, vendor/vendor.json, vsphere/resource_vsphere_virtual_machine_snapshot_test.go, vsphere/resource_vsphere_virtual_machine_test.go
Looks like the test for #305 was incorrectly written but passed anyway,
this was due to hashicorp/terraform#16895, which was merged today.
Unfortunately looks like there were significant updates to core to break
just vendoring this package (particular with TF contexts), so I've just
updated everything.
=> vendor: Update to github.com/hashicorp/terraform/...@8511930

vendor/github.com/hashicorp/terraform/helper/pathorcontents/read.go, vendor/github.com/terraform-providers/terraform-provider-template/LICENSE, vendor/github.com/terraform-providers/terraform-provider-template/template/datasource_cloudinit_config.go, vendor/github.com/terraform-providers/terraform-provider-template/template/datasource_template_file.go, vendor/github.com/terraform-providers/terraform-provider-template/template/provider.go, vendor/github.com/terraform-providers/terraform-provider-template/template/resource_template_dir.go, vendor/vendor.json, vsphere/provider_test.go, vsphere/resource_vsphere_virtual_machine_test.go
This fixes some failing tests for the vApp ISO transport by supplying
the user data necessary for static network configuration on the Ubuntu
OVA.
We use the template provider for this so it has been vendored and added
to the test provider list as well.
=> tests: Fix vApp ISO tests

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go, vsphere/resource_vsphere_virtual_machine_test.go
The current disk sub-resource code only skips adding a backing when a
`datastore_id` is absent. This is only true when using SDRS on VM
creation.  On update, since a datastore has been populated in state from
a refresh call, `datastore_id` will be populated, producing the backing in
the `VirtualMachineConfigSpec`. In SDRS this is actually how you specify
that you don't want SDRS to recommend a datastore to place the disk in,
but rather want the disk to go into a specific datastore. This is not
what we want.
The tests included with this PR are mainly for sanity checking for
SDRS-enabled VMs with multiple disks, and ensuring that update
operations work correctly. To actually test for the presence of a nil
backing in the above described scenario, one needs to use …
=> r/virtual_machine: Backings should never be added to disks w/SDRS

vsphere/resource_vsphere_virtual_machine.go
Not all VM post-clone operations were being rolled back correctly.
Several config-building operations (namely surrounding device management
and property gathering) were not being sent through the rollback
handler, hence were at risk for causing an irrecoverable state on error.
In addition, the ID was being set too early.
This fixes this by ensuring that *all* operations that produce errors
that happen from the moment a VM clone is finished, to right before VM
customization, are all sent through the rollback handler.
ID setting has been moved as well to right before customization is done.
This is the earliest place where the VM can be reasonably preserved and
Terraform will not immedately fail upon refresh.
=> r/virtual_machine: Roll back all VM post-clone config operations

website/docs/r/virtual_machine.html.markdown
I was reading through the docs and noticed this.
=> Minor grammar correction

vsphere/helper_test.go, vsphere/provider.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/resource_vsphere_ha_vm_override.go, vsphere/resource_vsphere_ha_vm_override_test.go, website/docs/r/compute_cluster.html.markdown, website/docs/r/ha_vm_override.html.markdown, website/vsphere.erb
The second override out of three. The host override resource will be following!
=> New resource: vsphere_ha_vm_override

vsphere/helper_test.go, vsphere/provider.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/resource_vsphere_dpm_host_override.go, vsphere/resource_vsphere_dpm_host_override_test.go, vsphere/resource_vsphere_ha_vm_override.go, vsphere/resource_vsphere_ha_vm_override_test.go, website/docs/r/compute_cluster.html.markdown, website/docs/r/dpm_host_override.html.markdown, website/docs/r/ha_vm_override.html.markdown, website/vsphere.erb
This contains the code, tests, and docs for the `vsphere_dpm_host` override resource, which allows one to override settings for a host within a `vsphere_comptue_cluster` resource.
=> r/dpm_host_override: New resource

vsphere/resource_vsphere_resource_pool.go
Read resource pools after creation to fill in all the computed values.
=> r/resource_pool Read after create

vsphere/data_source_vsphere_virtual_machine.go
Prevent #558 (which is not a bug)
=> vsphere_virtual_machine: Add a test to catch empty UUID

vsphere/resource_vsphere_virtual_machine_test.go
Add cpu_reservation for for high latency cpu test to meet minimum
requirements for sched.cpu.min.
=> /r/virtual_machine: Add cpu_reservation

vsphere/data_source_vsphere_virtual_machine.go, vsphere/helper_test.go, vsphere/internal/virtualdevice/virtual_machine_device_subresource.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_test.go, website/docs/d/virtual_machine.html.markdown, website/docs/r/virtual_machine.html.markdown
Adds feature requested in #542
=> r/virtual_machine: Support SCSI bus sharing

vsphere/resource_vsphere_virtual_machine.go
=> r/virtual_machine: Only relocate if host_system_id is set

.travis.yml, vsphere/distributed_virtual_switch_structure.go, vsphere/resource_vsphere_compute_cluster_vm_dependency_rule.go, vsphere/resource_vsphere_compute_cluster_vm_host_rule.go, vsphere/resource_vsphere_resource_pool.go
Run gofmt on existing files to be 1.11 format compatible.
=> Make format 1.11 compatible

vsphere/resource_vsphere_virtual_machine.go
=> r/virtual_machine: Update clone timeout does not ForceNew

vsphere/resource_vsphere_folder_test.go, vsphere/tags_helper.go
=> Find tag changes when first tag is changed

vsphere/virtual_machine_config_structure.go
=> r/virtual_machine: Fix virtual machine config structure schema

vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go, vsphere/resource_vsphere_virtual_machine_test.go
Allow cloning of powered on virtual machines.
Addressed #746
=> r/virtual_machine: Allow cloning of powered on VMs

vsphere/config.go, vsphere/provider.go, website/docs/index.html.markdown
Adds a VIM session keep alive that defaults to 10 minutes.
Fixes #641
=> r/virtual_machine: Add VIM session keep alive

vsphere/resource_vsphere_tag.go, vsphere/resource_vsphere_tag_category.go
Remove tags and tag_categories when they have been deleted
Addresses #698
=> r/tag: Remove deleted tags

vsphere/resource_vsphere_host.go, vsphere/resource_vsphere_host_test.go
- Create cluster while testing instead of expecting one to be there
already.
- Moved the licence checks into their own functions. Also fixed a
logic bug that occurs when users don't pass a license attribute,
and added the relevant test.
- Add argument validation and tests also fix bug by adding missing
return statement.
=>     [vsphere_host] Minor fixes

.github/workflows/issues.yml
When a new issue is added, add into our project for triage.
=> Add Github action for new issues

website/docs/index.html.markdown
Variables on vSphere provider page
=> Fixed variable interpolation as per v0.12

website/docs/r/vapp_entity.html.markdown
=> fix typos and incorrect ref to id and not moid (managed) in the vsphere_vapp_entity docs

.circleci/config.yml, go.mod, go.sum
- Split tests in five separate jobs for now
- Update go.mod with indirect dependencies.
=> Housekeeping

vsphere/data_source_vsphere_virtual_machine.go
This PR adds a `guest_ip_addresses` attribute to the `data.vsphere_virtual_machine` datasource. It is intended to be used when a Terraform configuration needs to know the IP addresses of existing VMs in vSphere, e.g. a HashiCorp Vault cluster that needs its Consul agents to join an existing Consul server cluster.
In the case of VMs with multiple NICs, it becomes especially useful when combined with #819, which sorts the IP addresses by network device ID for each VM.
Fixes #901
=> Set guest IP addresses on data.vsphere_virtual_machine if available

vsphere/resource_vsphere_vapp_container_test.go
Instead pull values from env variables, like we do in other places
=> [vapp] Remove hardcoded values from test code

vsphere/internal/helper/provider/provider_helper.go, vsphere/internal/helper/spbm/spbm_helper.go, vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Set the storage_policy_id based off the VM uuid rather than the template.
=> Base storage_policy_id off vm

.circleci/config.yml
Move tests that break on the lab further down to minimise need for
manual testing.
=> [circleci] reorder tests

vsphere/host_port_group_structure.go, vsphere/resource_vsphere_host_port_group.go, vsphere/resource_vsphere_virtual_machine_test.go
* Fix tfproviderlint error by converting a Set to a List
* calculatePorts needs to return a slice not a set
* replace template_file in the test code with local
string interpolation
=> Pre release cleanup

vsphere/resource_vsphere_virtual_machine_test.go
Added a 2nd disk to each controller to test the logic
=> Add 2nd disk to each controller

vsphere/resource_vsphere_file.go
Create two new functions:
- `createDirectory` - create directory on target datacenter and datastore
- `fileUpload` - upload file
Fix golinting issues
Change variable names explicit destination (dst) vs. source (src) to make it more clear.
Modified copyFile to use DatastoreFileManager that supports the proper `Copy` of VMDK files.
Added branch for the upload VMDK case:
- Creates a temporary file location for the VMDK to be uploaded
- Upload with uploadFile
- Use DatastoreFileManager to `Move` the VMDK that will properly move the disk
Modified upload case to use uploadFile
=> Update resource vsphere file to support vmdk files

vsphere/resource_vsphere_virtual_machine_test.go
Additional changes to scsi tests.
=> SCSI controller tests

vendor/github.com/vmware/govmomi/ovf/cim.go, vendor/github.com/vmware/govmomi/ovf/doc.go, vendor/github.com/vmware/govmomi/ovf/env.go, vendor/github.com/vmware/govmomi/ovf/env_test.go, vendor/github.com/vmware/govmomi/ovf/envelope.go, vendor/github.com/vmware/govmomi/ovf/manager.go, vendor/github.com/vmware/govmomi/ovf/ovf.go, vendor/github.com/vmware/govmomi/ovf/ovf_test.go, vsphere/internal/helper/ovfdeploy/ovf_helper.go, vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_test.go, vsphere/virtual_machine_config_structure.go, website/docs/r/virtual_machine.html.markdown
This pull request allows  users to deploy OVF templates as VM from both from local system and remote URL into vcenter..
yes
yes, only for deployfromOvf test function
https://gist.github.com/sumitAgrawal007/78674a435b7dd779f94f957b722b7b1d
Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation?
https://github.com/terraform-providers/terraform-provider-vsphere/issues/961
https://github.com/terraform-providers/terraform-provider-vsphere/issues/1043
https://github.com/terraform-providers/terraform-provider-vsphere/issues/74
=> Deploy OVF from remote Url and local system

README.md
Adds a handy release badge and license badge to the readme.
=> Add release badge and license badge

website/docs/r/virtual_machine.html.markdown
Fixing two bugs in OVF deployment documentation.
=> fixing OVF deploy documentation bugs

.hashibot.hcl
Adds some automation to comment on issues when they are released in the provider.
=> Add release comments

vsphere/data_source_vsphere_host_pci_device.go, vsphere/internal/helper/computeresource/compute_resource_helper.go, vsphere/internal/helper/envbrowse/environment_browser_helper.go, vsphere/internal/virtualdevice/virtual_machine_device_subresource.go, vsphere/provider.go, vsphere/resource_vsphere_virtual_machine.go, website/docs/d/host_pci_device.html.markdown, website/docs/r/virtual_machine.html.markdown
Acceptance tests are the the acceptance test PR.
=> Add PCI passthrough device support

vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
=> Skip PCI passthrough apply operations if there are no changes

vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Disks when uploaded from OVF are to be deleted on destroy.
Adding a logic to make keep_on_remove=false for OVF/OVA
https://github.com/hashicorp/terraform-provider-vsphere/issues/1089
=> Delete disks on tf destroy if deployed from OVF/OVA

vsphere/data_source_vsphere_virtual_machine.go, vsphere/internal/virtualdevice/virtual_machine_device_subresource.go, vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_migrate_test.go, website/docs/r/virtual_machine.html.markdown
=> Support for SATA and IDE disks

vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go, vsphere/internal/helper/structure/structure_helper.go, vsphere/internal/helper/vsansystem/vsansystem_helper.go, vsphere/resource_vsphere_compute_cluster.go, website/docs/r/compute_cluster.html.markdown
Adding basic vSAN support. Currently more advanced features are not supported in govmomi, but work is being done to add more vSAN features.
Acceptance tests are being added in acctest branch.
=> r/compute_cluster: Add vSAN support

README.md, vsphere/data_source_vsphere_role.go, vsphere/data_source_vsphere_role_test.go, vsphere/helper_test.go, vsphere/internal/administrationroles/vsphere_permission_subresource.go, vsphere/internal/helper/utils/entityIdToManagedObjectId.go, vsphere/provider.go, vsphere/resource_vsphere_entity_permissions.go, vsphere/resource_vsphere_entity_permissions_test.go, vsphere/resource_vsphere_role.go, vsphere/resource_vsphere_role_test.go, website/docs/d/vsphere_role.html.markdown, website/docs/r/vsphere_entity_permissions.html.markdown, website/docs/r/vsphere_role.html.markdown, website/vsphere.erb
Added Resource and DataSource to create and manage vsphere Roles.
Added Resource to create and manage vsphere permissions.
Acceptance test logs: https://gist.github.com/sumitAgrawal007/c536fd77ae856af4424cd0bf3a86fb9d
https://github.com/hashicorp/terraform-provider-vsphere/issues/1102
=> Add roles and permission resources 

README.md
=> Add hall of fame to README.md

vsphere/resource_vsphere_folder_migrate.go, vsphere/resource_vsphere_virtual_machine_migrate.go
=> Fix non inclusive language

vsphere/resource_vsphere_virtual_machine.go
=> Avoid nil condition for guestID

vsphere/distributed_virtual_switch_helper.go
```
...
```
```release-note
Allow creation of vsphere 7 dvs
```
=> Support vsphere 7 for dvs

CHANGELOG.md, README.md, vsphere/virtual_machine_config_structure.go
Pre-release tidy up
- Update README.md
- Update Changelog
=> changelog v1.26.0

vsphere/config.go
#1300  contains most of the background for the issue this PR is resolving.
REST API session is not kept alive. I enabled the rest keepalive functionality from govmomi and tested this patched version in our environment and saw that it sends keepalives and successfully keeps the session open while Terraform is running. This fixed the issue I was having with low bandwidth causing template clones to fail when the provider checks the tags for the cloned VM using the Rest API. This probably also could affect Content Library resources as those looks to use the REST API as well.
Here is gist with pre/post patch logs for rest session:
https://gist.github.com/happly/2ebb3cd0cb0058ae8b0f9c498e263961
I will have to give this a shot tomorrow and edit with the results. …
=> Manual start of REST keepalive w/ cached session

vsphere/virtual_machine_config_structure.go
```
...
```
```release-note
...
```
=> Only set vvtd/vbs if vsphere version is newer than 6.5

vsphere/data_source_vsphere_virtual_machine.go, vsphere/internal/helper/viapi/vim_helper.go, vsphere/internal/helper/viapi/vim_helper_test.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/virtual_machine_config_structure.go
=> do not access vvtd and vbs fields unless on we are running on vsphere > 6.5

.github/ISSUE_TEMPLATE/bug-report.md
- Updates `bug-report.md` to include the vSphere version.
- Minor updates to markdown comments.
=> Update bug-report.md to include vSphere version

_about/FAQ.md
Update FAQ.md with current team plus additional clarification
=> Update FAQ.md with current team + adds

CHANGELOG.md, vsphere/internal/helper/virtualmachine/virtual_machine_helper.go, vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_test.go, vsphere/virtual_machine_guest_structure.go, website/docs/d/virtual_machine.html.markdown
Update the brand and product/component names if incorrectly used.
- Updates `VMWare` to the proper form of `VMware`
- Updates `VMware tools` to the proper form of `VMware Tools`
=> Update the brand and product/component names

.github/issue_greeting_template.md, .github/workflows/issue_greeting.yml, docs/ISSUES.md
Adds a GitHub Action for an issue greeting to the issue author with information and links to the issue lifecycle and the contributing guidelines.
```markdown
Hello, {{ .author }}! 🖐
Thank you for submitting an issue for this provider. The issue will now enter into the issue lifecycle.
If you want to contribute to this project, please review the contributing guidelines and information on submitting pull requests.
```
**Note**: A similar action is used in `vmware/govmomi`, too.
=> Add GitHub Action for issue greeting

docs/FAQ.md
@tenthirtyam If you would like your title or the the callout to collaborators from VMware sentence tweaked just let us know.
=> Add Ryan Johnson as collaborator

vsphere/resource_vsphere_host.go, website/docs/r/host.html.markdown
I am first-time contributer and I appreciate some first feedback. The changes are confirmed to be running fine for read/update/create operations.
```console
```
`resource/virtual_host` : Added support add tags to hosts. (GH-1499]
Closes  #1452
=> Add support for attaching tags to ESXi hosts

website/docs/r/virtual_machine.html.markdown
\### Description
Updates `r/vsphere_virtual_machine` to correct some errors in the nested ESXi example.
=> Update `r/vsphere_virtual_machine` docs

.github/workflows/release.yml, .gitignore, .goreleaser.yml, terraform-registry-manifest.json
This is the new GH action based release workflow. There is currently a small bug around the protocol version manifest we recently discovered. Once the fix is determined I'll PR it over.
=> Move to GH action based release

.circleci/config.yml, .github/issue_greeting_template.md, .github/pull_request_template.md, .github/workflows/codeql-analysis.yml, CHANGELOG.md, scripts/config_builder.sh
=> Update `master` references to `main`

website/docs/r/resource_pool.html.markdown
- Updates the `r/vsphere_resource_pool` docs for context.
- Removes interpolation syntax in the examples.
- Adds example for targeting a virtual machine resource to the default resource pool of a cluster.
- Adds example for creating parent and child resource pool.
`resource/vsphere_resource_pool`: Documentation updates. (GH-1620)
Closes #1249 via documentation improvements.
=> docs: Update `r/vsphere_resource_pool` docs

vsphere/resource_vsphere_virtual_machine.go
Adds conditional to avoid a provider panic when a vGPU is added as a PCI device outside of Terraform to a virtual machine. 
- Esisting viirtual machine resource
- Shutdown virtual machine
- Add NVIDIA vGPU
- Power on virtual machine
- Run `terraform apply` with DEBUG logging.
```console
❯ TF_LOG=DEBUG TF_LOG_PATH=debug.txt terraform apply -auto-approve
vsphere_virtual_machine.vm: Refreshing state... [id=420c9aa5-4402-fd89-ff97-748c986b3c77]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
Debug Log Message:
```log
2022-03-18T18:15:49.176-0400 [INFO] …
```
=> fix: Only consider `VirtualPCIPassthroughDeviceBackingInfo` devices

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
These are the necessary components that `terraform-provider-vsphere` needs to onboard to Releases API.
=> chore: Add necessary bits to onboard project to the Releases API

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
Reverts hashicorp/terraform-provider-vsphere#1640
=> Revert "chore: Add necessary bits to onboard project to the Releases API"

website/docs/d/compute_cluster.html.markdown, website/docs/d/content_library.html.markdown, website/docs/d/content_library_item.html.markdown, website/docs/d/custom_attribute.html.markdown, website/docs/d/datacenter.html.markdown, website/docs/d/datastore.html.markdown, website/docs/d/datastore_cluster.html.markdown, website/docs/d/distributed_virtual_switch.html.markdown, website/docs/d/dynamic.html.markdown, website/docs/d/folder.html.markdown, website/docs/d/host.html.markdown, website/docs/d/host_pci_device.html.markdown, website/docs/d/host_thumbprint.html.markdown, website/docs/d/license.html.markdown, website/docs/d/network.html.markdown, website/docs/d/ovf_vm_template.html.markdown, website/docs/d/resource_pool.html.markdown, website/docs/d/storage_policy.html.markdown, website/docs/d/tag.html.markdown, website/docs/d/tag_category.html.markdown, website/docs/d/vapp_container.html.markdown, website/docs/d/vmfs_disks.html.markdown, website/docs/d/vsphere_role.html.markdown
Updates the data source docs to:
- Remove legacy interpolation on data sources.
- Update, simplify, and/or expand examples.
- Update terminology and context as needed.
=> docs: Update data source docs

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
These are the necessary components that `terraform-provider-vsphere` needs to onboard to Releases API. 
edit: rel-eng will merge this PR when the time is ready.
=> [DO NOT MERGE] RelAPI Onboarding 

website/docs/index.html.markdown
Updates the documentation index to include:
- Clearer context on provider coverage.
- Updated abridged example.
- Updates on specific privileges needed for storage policies and swapfile placement.
Closes: #1212
Closes: #1216
=> docs: update docs index

website/docs/index.html.markdown
Update Line 195 from privledge to privilege
n/a
n/a
n/a
n/a
=> Update Line 195 from privledge to privilege

scripts/docscheck.sh
In the v2.2.0 release, we moved all data source documentation into subcategories. This change updates the `./scripts/docscheck.sh` script to check each resource and data source documentation item for a subcategory to help avoid any misses when accepting new documentation.
=> fix: Update `docscheck.sh` to check data source docs

.github/ISSUE_TEMPLATE/bug.yml
- Update placeholder versions
- Update "_Resources_" to "_Resources and Data Sources_"
- Set the following additional ids as required: 
- `configuration`
- `debug`
- `steps-to-reproduce`
**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
=> repo: Update bug report template

website/docs/r/compute_cluster_vm_anti_affinity_rule.html.markdown
Add the workaround for the problem described on #1362
=> Update vsphere_compute_cluster_vm_anti_affinity_rule docs

go.mod, go.sum, vsphere/resource_vsphere_virtual_machine.go
Update govmomi to latest release
No regressions
```release-note
provider: Update govmomi v0.29.0
```
Closes #1657
=> chore: Update `vmware/govmomi` v0.29.0

README.md
Update README.md with context for "VMware vSphere".
=> docs: Update README.md with context for "VMware vSphere"

README.md
Update README.md with context for "VMware vSphere".
=> Update `README.md` with context for "VMware vSphere"

.github/issue_greeting_template.md
Updates the greeting template to remove extra spaces.
=> chore: update greeting template

website/docs/index.html.markdown
=> docs: correct typos on docs index

vsphere/resource_vsphere_compute_cluster.go
When we are enabling vSAN and the vSAN-related features, like dedupe/compression or vSAN performance service, there could be a race condition that these vSAN features cannot be properly enabled. On the vSphere task dashboard, we will see the task failed with the error message "The operation is not supported on the object".
The root cause of the above issue is that we can see the enabling vSAN operation and the enable vSAN feature operation are in two API calls to the backend, and they are not properly synchronized to avoid the race condition that when the vSAN features are being enabled, vSAN is already in a stable state of enabled.
This change fixes the above issue by setting up the proper API call sequence in the vSAN and HA enable/disable workflow to ensure that the enable state can be …
=> fix: race condition configuring vSAN and vSAN services

vsphere/resource_vsphere_compute_cluster.go
```
(all pass)
```
```release-note
`resource/compute_cluster`: Fix panic. [GH-1835]
```
=> Robustly check nil for all vsan data

.github/workflows/acceptance-tests.yaml, scripts/compare-testlogs.js
small JS script to check log against previous dates log (this won't work until after the first day a log is uploaded with the date in the name).
=> chore: CI add small script to find potential regressions from previous day

vsphere/internal/helper/computeresource/compute_resource_helper.go, vsphere/internal/helper/envbrowse/environment_browser_helper.go, vsphere/internal/helper/resourcepool/resource_pool_helper.go, vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go, vsphere/resource_vsphere_virtual_machine.go
Reverts hashicorp/terraform-provider-vsphere#1966 See comment I posted on the PR
=> Revert "Fix for https://github.com/hashicorp/terraform-provider-vsphere/issue…"

.github/workflows/acceptance-tests.yaml
- Official GH download-artifact action does not support downloads between workflow runs, disable it for now.
- ! causes parsing issues in YAML, use if statement instead.
=> Fix acceptance tests workflow

.github/workflows/acceptance-tests.yaml, scripts/compare-testlogs.js, scripts/summarize-testlog.js
Small script to summarize sums of pass/skip/fail. Will error if pass count is 0. Tweak regression check to flag new failures that passed in previous log (subtle difference).
=> chore(ci): summarize test output

acctests/README.md, docs/CONTRIBUTING.md
Updates to contributing and acctests documentation.
=> chore(docs): Update contributing documentation

acctests/README.md
Small update to acceptance tests docs.
=> chore(docs): Acceptance tests update

vsphere/resource_vsphere_compute_cluster.go
Nightly pipeline failed at explicitFailoverHost acc test after we adding faultDomain acc test
link: https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/6923837372/job/18832252040
RC: fault domain attribute on each host was not force removed during cluster destroy, causing plan was not empty in next acc test.
issue was reproed locally and fix was validated as followings.
```
=== RUN   TestAccResourceVSphereComputeCluster_faultDomain
--- PASS: TestAccResourceVSphereComputeCluster_faultDomain (276.80s)
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere 277.917s
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/viapi   (cached) [no tests to run]
testing: …
```
=> fix: explicitFailoverHost acc test failed after faultDomain acc test

.github/workflows/pull-request.yml
Update the steps for the labels to resolve workflow failure.
https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/7497463294
=> fix(ci): pull request labels

CHANGELOG.md
Updates `CHANGELOG.md` for v2.7.0 release.
=> chore(release): v2.7.0

.github/workflows/acceptance-tests.yaml, .github/workflows/release.yml
Reverts `actions/upload-artifact` from v4.0.0 to v3.1.3.
=> chore(ci): revert `actions/upload-artifact`

.github/workflows/codeql-analysis.yml
Correct YAML syntax in `.github/workflows/codeql-analysis.yml`.
THis should resolve the GHA issues for CodeQL.
=> chore(ci): codeql-analysis with go1.21+

vsphere/data_source_vsphere_guest_os_customization.go, vsphere/internal/helper/guestoscustomizations/customizations_helper.go, vsphere/resource_vsphere_guest_os_customization.go, vsphere/resource_vsphere_virtual_machine.go, website/docs/r/virtual_machine.html.markdown
allow to put VMs into specific OU. closes #2180
```release-note
Add support for domain_OU windows customization
```
* https://github.com/hashicorp/terraform-provider-vsphere/issues/2180
* https://github.com/hashicorp/terraform-provider-vsphere/issues/996
* https://github.com/hashicorp/terraform-provider-vsphere/issues/2130
=> feat: add `domain_ou` support for windows customization

CHANGELOG.md
Updates `CHANGELOG.md` for v2.8.0 release.
=> chore(release): v2.8.0

vsphere/internal/helper/guestoscustomizations/customizations_helper.go, website/docs/r/virtual_machine.html.markdown
Updates `r/virtual_machine` to denote support and limitations.
Closes #2206
Closes #2209
=> docs: update `domain_ou`

website/docs/r/content_library.html.markdown, website/docs/r/host_port_group.html.markdown, website/docs/r/supervisor.html.markdown
Addressed some spelling errors while reviewing markdown.
=> docs: spelling corrections

CHANGELOG.md
Updates `CHANGELOG.md` for v2.8.2 release.
=> chore: release v2.8.2

vsphere/internal/helper/guestoscustomizations/customizations_helper.go, vsphere/resource_vsphere_virtual_machine_test.go
It appears that `customizations_helper.go` intentionally skips the gateway settings for every adapter after the first one.
This leads to a bug where cloning a VM with multiple adapters ends up with potentially incorrect network settings.
My fix is to simply delete the code which explicitly omits the settings for subsequent adapters during GOS customization.
I have added a new testcase that can be used to validate this fix.
The test is intentionally marked with `t.Skip()` so that it does get included in the CI runs.
This is so because it requires a Sysprepped Windows VM template.
I tested this fix by running the new test, logging into the VM and confirming that the gateway is applied to both adapters.
`resource/virtual_machine`: Allow `ipv4_gateway` to be set on more than one network …
=> fix: allow gosc to set default gateway on more than one network adapter

CHANGELOG.md
Updates `CHANGELOG.md` for v2.8.3 release.
=> chore: release v2.8.3

CHANGELOG.md
Updates `CHANGELOG.md` for v2.9.0 release.
=> chore: release v2.9.0

CHANGELOG.md, website/docs/r/virtual_machine.html.markdown
Updates to clarify the assignment of `network_interface`.
* `resource/vsphere_virtual_machine`: Updates to clarify assignment of `network_interface`.
Closes #2101
=> docs: update `network_interface`

CHANGELOG.md
Updates `CHANGELOG.md` for v2.10.0 release.
=> chore: release v2.10.0

acctests/equinix/README.md, acctests/vsphere/README.md
Some extra context on tests for future maintainers
=> Extra notes on automated testing

website/docs/r/compute_cluster_vm_host_rule.html.markdown, website/docs/r/drs_vm_override.html.markdown, website/docs/r/host_virtual_switch.html.markdown, website/docs/r/virtual_machine.html.markdown
I added some missing double quotes in website document.
=> FIX: website doc typos

CHANGELOG.md, README.md, website/docs/d/resource_pool.html.markdown, website/docs/index.html.markdown, website/docs/r/compute_cluster.html.markdown, website/docs/r/custom_attribute.html.markdown, website/docs/r/datastore_cluster.html.markdown, website/docs/r/distributed_port_group.html.markdown, website/docs/r/distributed_virtual_switch.html.markdown, website/docs/r/dpm_host_override.html.markdown, website/docs/r/drs_vm_override.html.markdown, website/docs/r/ha_vm_override.html.markdown, website/docs/r/host_port_group.html.markdown, website/docs/r/host_virtual_switch.html.markdown, website/docs/r/resource_pool.html.markdown, website/docs/r/storage_drs_vm_override.html.markdown, website/docs/r/tag.html.markdown, website/docs/r/tag_category.html.markdown, website/docs/r/vapp_container.html.markdown, website/docs/r/vapp_entity.html.markdown, website/docs/r/virtual_disk.html.markdown, website/docs/r/virtual_machine.html.markdown, website/docs/r/virtual_machine_snapshot.html.markdown
Updates VMware product documentation links.
Closes #2312
=> docs: update docs urls

CHANGELOG.md
Updates `CHANGELOG.md` for v2.11.0 release.
=> chore(release): v2.11.0

docs/resources/compute_cluster_host_group.md, docs/resources/compute_cluster_vm_host_rule.md, docs/resources/custom_attribute.md, docs/resources/datastore_cluster.md, docs/resources/license.md, docs/resources/nas_datastore.md, docs/resources/vmfs_datastore.md, scripts/docscheck.sh
- Updates `docscheck.sh` for updated path.
- Removes additional interpolation instances from examples.
=> docs: update `docscheck.sh`

CHANGELOG.md
=> chore(release): v2.12.0

.github/workflows/lock.yml
=> chore(gh): update lock workflow

docs/data-sources/license.md, docs/resources/license.md
Updates the license documentation.
=> docs: update license documentation

vsphere/resource_vsphere_compute_cluster.go
Refactors error handling to simplify the code and improve readability. 
The changes primarily involve removing unnecessary `else` blocks following error returns and restructuring the code for better clarity.
`resourceVSphereComputeClusterApplyHostImage`:
- Removed redundant `else` blocks after error checks and returns. This includes restructuring the logic for `CreateSoftwareDraft`, `UpdateSoftwareDraftComponents`, `CommitSoftwareDraft`, and `WaitForCompletion` calls. [[1]](diffhunk://#diff-9ee4a4868164e61d7c4f44e2e6dc3a2e4a35ff0b2a0e557c4458d1166e5ab5f6L1170-R1174) [[2]](diffhunk://#diff-9ee4a4868164e61d7c4f44e2e6dc3a2e4a35ff0b2a0e557c4458d1166e5ab5f6L1187-R1205)
`resourceVsphereComputeClusterEnableSoftwareManagement`:
- Simplified the return statement by removing an unnecessary `else` …
=> refactor: compute cluster drop else and outdent

.golangci.yml, vsphere/data_source_vsphere_datastore_stats.go, vsphere/distributed_virtual_port_setting_structure.go, vsphere/helper_test.go, vsphere/internal/helper/viapi/vim_helper.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/virtual_machine_config_structure.go
Fix redefinition of the built-in functions.
=> fix: redefinition of the built-in function

CHANGELOG.md
Update for `CHANGELOG.md`.
- Match layout of of other `github.com/vmware/` providers.
- 100 character markdown wrap.
- Simplify resource and data source references.
- Simplify issue links.
=> chore: update release history

docs/data-sources/folder.md, docs/resources/folder.md
Updates the documenatation for both `r/folder` and `d/folder`.
Closes #2458
=> docs: update folder documentation

.github/workflows/test.yml
- Renames `unit_tests.yml` to `test.yml`.
- Updates workflow to retrieve the go version from `go.mod`.
=> chore(gh): update tests workflow

CODEOWNERS
Post-transfer update of `CODEOWNERS`.
=> chore(xfer): update codeowners

CODE_OF_CONDUCT.md, docs/CODE_OF_CONDUCT.md
Post-transfer update of `CODE-OF-CONDUCT.md`.
=> chore(xfer): update code-of-conduct

.github/labeler-issue-triage.yml, .github/labeler-issues.yml, .github/workflows/issue-opened.yml
Post-transfer update issue labels workflow
=> chore(xfer): update issue labels workflow

.github/labeler-pull-requests.yml, .github/workflows/pull-requests.yml
Post-transfer update pull request labels workflow
=> chore(xfer): update pull request labels workflow

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/enhancement.yml
Post-transfer update of issue templates.
=> chore(xfer): update issue templates

.github/pull_request_template.md
Post-transfer update of pull request template.
=> chore(xfer): update pull request template

NOTICE
Post-transfer addition of `NOTICE`.
=> chore(xfer): add notice

terraform-registry-manifest.json
Post-transfer update for registry manifest to match layout of of other `github.com/vmware/` providers.
=> chore(xfer): update registry manifest

LICENSE
Post-transfer update of `LICENSE`.
=> chore(xfer): update license

.github/workflows/pull-requests.yml
Update workflow permissions.
Output:
=> chore(gh): update pull request workflow

.github/workflows/remove-issue-label.yml
Update workflow permissions.
Output:
=> chore(gh): update issue workflow

.github/workflows/issue-comment-created.yml
Update workflow permissions.
Output:
=> chore(gh): update comment workflow

.golangci.yml
Remove resolves exclusions.
Output:
=> chore: update `.golangci.yml`

.golangci.yml, vsphere/config.go, vsphere/internal/helper/contentlibrary/content_library_helper.go, vsphere/internal/helper/customattribute/custom_attributes_helper.go, vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go, vsphere/internal/virtualdevice/virtual_machine_device_subresource.go, vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go, vsphere/resource_vsphere_virtual_disk.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_snapshot.go, vsphere/resource_vsphere_vmfs_datastore.go, vsphere/tags_helper.go
- Resolves `golangci-lint` identified issues for ST1005:  error strings should not end with punctuation or newline.
- Removes `golangci-lint` exclusions in `.golangci.yml` for those items already resolved.
Output:
Ref: #2472
=> chore: fix staticcheck ST1005

CHANGELOG.md
=> chore(release): v2.13.0

.golangci.yml, vsphere/resource_vsphere_offline_software_depot_test.go
Resolves `golangci-lint` identified issues for S1005: unnecessary assignment to the blank identifier.
Before:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1005 via 🐹 v1.24.3 
vsphere/resource_vsphere_offline_software_depot_test.go:43:3: S1005: unnecessary assignment to the blank identifier (staticcheck)
location, _ := tVars.resourceAttributes["location"]
^
1 issues:
```
After:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1005 via 🐹 v1.24.3 
0 issues.
```
Output:
=> fix: staticcheck S1005

.golangci.yml, vsphere/resource_vsphere_compute_cluster.go
Resolves `golangci-lint` identified issues for S1009: `should omit nil check; len() for nil slices is defined as zero`.
Before:
```shell
terraform-provider-vsphere on  chore/fix-staticcheck-S1009 [!] via 🐹 v1.24.3 
vsphere/resource_vsphere_compute_cluster.go:1522:5: S1009: should omit nil check; len() for nil slices is defined as zero (staticcheck)
if spec.VsanHostConfigSpec == nil || len(spec.VsanHostConfigSpec) == 0 {
^
1 issues:
```
After:
```shell
terraform-provider-vsphere on  fix/staticcheck-S1009 via 🐹 v1.24.3 
0 issues.
```
Output:
=> fix: staticcheck S1009

.golangci.yml, vsphere/data_source_vsphere_host_vgpu_profile.go
Resolves `golangci-lint` identified issues for QF1012: Use fmt.Fprintf(...) instead of Write([]byte(fmt.Sprintf(...)))
Before:
```shell
terraform-provider-vsphere on  fix/staticcheck-QF1012 via 🐹 v1.24.3 
vsphere/data_source_vsphere_host_vgpu_profile.go:87:15: QF1012: Use fmt.Fprintf(...) instead of Write([]byte(fmt.Sprintf(...))) (staticcheck)
if _, err := idsum.Write([]byte(fmt.Sprintf("%#v", d.Get("host_id").(string)))); err != nil {
^
1 issues:
```
After:
```shell
terraform-provider-vsphere on  fix/staticcheck-QF1012 via 🐹 v1.24.3 
0 issues.
```
Output:
=> fix: staticcheck QF1012

.golangci.yml, vsphere/resource_vsphere_file.go
Resolves `golangci-lint` identified issues for QF1008: `could remove embedded field "Client" from selector`.
```shell
terraform-provider-vsphere on  fix/staticcheck-QF1008 via 🐹 v1.24.3 
vsphere/resource_vsphere_file.go:461:15: QF1008: could remove embedded field "Client" from selector (staticcheck)
err = client.Client.UploadFile(context.TODO(), source, dsurl, &p)
^
1 issues:
```   
```shell
terraform-provider-vsphere on  fix/staticcheck-QF1008 via 🐹 v1.24.3 
0 issues.
```
Output:
=> fix: staticcheck QF1008

.golangci.yml, vsphere/data_source_vsphere_datastore.go, vsphere/data_source_vsphere_datastore_stats.go, vsphere/data_source_vsphere_virtual_machine.go, vsphere/helper_test.go, vsphere/internal/helper/guestoscustomizations/customizations_helper.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/resource_vsphere_distributed_virtual_switch_pvlan_mapping.go, vsphere/resource_vsphere_resource_pool.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_migrate.go, vsphere/resource_vsphere_virtual_machine_test.go
Refactored to handle errors returned by `d.Set`.
Output:
=> refactor: `d.Set` is not checked

tests/main.tf, tests/variables.tf
```shell
terraform fmt ./tests
```
Output:
=> chore: format tests

.golangci.yml, vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go, vsphere/resource_vsphere_virtual_machine.go
Resolves `golangci-lint` identified issues for SA4006: `this value of x is never used `.
Output:
=> fix: staticcheck SA4006

.golangci.yml, vsphere/event_helper.go, vsphere/internal/administrationroles/vsphere_permission_subresource.go, vsphere/internal/helper/structure/structure_helper.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/resource_vsphere_content_library_item_test.go, vsphere/resource_vsphere_host.go, vsphere/resource_vsphere_virtual_disk.go, vsphere/resource_vsphere_virtual_machine_test.go, vsphere/resource_vsphere_vnic.go, vsphere/virtual_machine_config_structure.go
Resolves `golangci-lint` identified issues for `revive > unused-parameter`.
Refactoring might be advisable in the future for some of these.
Ref: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
Output:
=> fix: rename unused parameters

.golangci.yml, vsphere/data_source_vsphere_host_thumbprint.go, vsphere/resource_vsphere_host.go
Marked the use of `crypto/sha1` used for host thumbprints with a `//nolint`.
Added `// TODO:` trace noting transition to `crypto/sha256` in next major release.
Output:
=> chore: `gosec` ignore `crypto/sha1`

.golangci.yml, vsphere/resource_vsphere_virtual_machine_test.go
Removes `testAccResourceVSphereVirtualMachineConfigBasicCdromIsoAndClientCdrom` which was added in #1631 but never used.
Before:
```shell
~/Downloads/terraform-provider-vsphere git:[chore/remove-unused-test-function]
vsphere/resource_vsphere_virtual_machine_test.go:4534:6: func testAccResourceVSphereVirtualMachineConfigBasicCdromIsoAndClientCdrom is unused (unused)
func testAccResourceVSphereVirtualMachineConfigBasicCdromIsoAndClientCdrom() string {
^
1 issues:
* unused: 1
```
After:
```shell
~/Downloads/terraform-provider-vsphere git:[chore/remove-unused-test-function]
golangci-lint run --fix
0 issues.
```
Output:
=> chore: remove unused test function

vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go, vsphere/resource_vsphere_virtual_machine.go
**Part 1**: Remove the legacy minimum supported version checks.
> [!NOTE]
> This change **does not** include items within the scope of vSphere clustering.
> These will be follow-up pull-requests that have broader changes.
Output:
Documentation has already been updated previouly to remove the legacy references before v7.
=> chore: remove legacy min versions

vsphere/data_source_vsphere_network.go, vsphere/internal/helper/network/network_helper.go
All references to names in a package will be done using the package name, so one can omit that name from the identifiers.
Output:
=> refactor: exported name starts with package

vsphere/data_source_vsphere_vmfs_disks_test.go, vsphere/helper_test.go, vsphere/resource_vsphere_content_library_item_test.go, vsphere/resource_vsphere_content_library_test.go, vsphere/resource_vsphere_file_test.go, vsphere/resource_vsphere_host_test.go, vsphere/resource_vsphere_license_test.go, vsphere/resource_vsphere_virtual_disk_test.go, vsphere/resource_vsphere_virtual_machine_snapshot_test.go
Updates error message casing to follow idiomatic style.
Output:
=> fix: error message casing

vsphere/event_helper.go, vsphere/internal/helper/storagepod/storage_pod_helper.go, vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
Replaces direct comparison of errors with a call to `errors.Is`.
The preferred way of checking for a specific error is to use the `errors.Is` function from the standard library as this function traverses the chain of the wrapped errors while checking for a specific error.
Output:
=> refactor: direct comparison of errors

vsphere/data_source_vsphere_virtual_machine.go, vsphere/internal/helper/envbrowse/environment_browser_helper.go, vsphere/internal/helper/structure/structure_helper.go, vsphere/internal/helper/virtualdisk/virtual_disk_helper.go, vsphere/resource_vsphere_compute_cluster_host_group_test.go, vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go, vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go, vsphere/resource_vsphere_compute_cluster_vm_group_test.go, vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go, vsphere/resource_vsphere_virtual_machine.go, vsphere/resource_vsphere_virtual_machine_migrate.go, vsphere/resource_vsphere_virtual_machine_migrate_test.go
Removes redundant type conversions that may be omitted.
Output:
=> chore: remove redundant type conversions

vsphere/resource_vsphere_virtual_machine_test.go
Enable more tests for the virtual machine resource
The majority of tests which remain disabled are negative scenarios and ones that require a more complex testbed (OVAs, vMotion, etc.)
<details>
cat gotest.log | grep -E '"Output":"--- (PASS|FAIL)' | gotestfmt
✅ TestAccResourceVSphereVirtualMachine_addDevices (2m2.12s)
✅ TestAccResourceVSphereVirtualMachine_basic (1m37.58s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionBare (1m17.81s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionClone (1m57.42s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionUpgrade (2m2.17s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitNumbers (1m32.05s)
✅ …
=> refactor: enable r/vsphere_virtual_machine tests

vsphere/data_source_vsphere_network.go, vsphere/internal/helper/virtualmachine/virtual_machine_helper.go, vsphere/resource_vsphere_datacenter.go, vsphere/resource_vsphere_datacenter_test.go, vsphere/resource_vsphere_file.go, vsphere/resource_vsphere_file_test.go, vsphere/resource_vsphere_virtual_machine.go
Replaces type assertion on errors with a call to `errors.As`.
The preferred way for checking for a specific error type is to use the `errors.As` function from the standard library as this function traverses the chain of the wrapped errors while checking for a specific error type.
Output:
=> refactor: replace type assertion on errors

vsphere/data_source_vsphere_datacenter.go, vsphere/data_source_vsphere_datastore_cluster.go, vsphere/data_source_vsphere_host_pci_device.go, vsphere/internal/helper/contentlibrary/content_library_helper.go, vsphere/internal/helper/virtualmachine/virtual_machine_helper.go, vsphere/resource_vsphere_compute_cluster.go, vsphere/tags_helper.go
Replaces empty slice declaration with nil slice declaration.
An empty slice can be represented by nil or an empty slice literal. They are functionally equivalent — their len and cap are both zero — but the nil slice is the preferred style.
Output:
=> refactor: use nil slice declaration

vsphere/internal/helper/storagepod/storage_pod_helper.go, vsphere/resource_vsphere_virtual_machine.go
When multiple SDRS placement recomendations are retrieved for a single virtual machine use the one with the highest confidence rating.
Follow SDRS recommendations when adding new disks during cloning.
<details>
<summary>Output: </summary>
✅ TestAccResourceVSphereVirtualMachine_addDevices (19.25s)
✅ TestAccResourceVSphereVirtualMachine_basic (1m21.59s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionBare (6.34s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionClone (52.25s)
✅ TestAccResourceVSphereVirtualMachine_hardwareVersionUpgrade (21.81s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitNumbers (13.89s)
✅ TestAccResourceVSphereVirtualMachine_highDiskUnitsToRegularSingleController (27.75s)
✅ TestAccResourceVSphereVirtualMachine_ignoreValidationOnComputedValue (1.59s)
✅ …
=> fix: `r/virtual_machine` - apply top-rated SDRS placement recommendation

CHANGELOG.md
Adding a changelog entry for v2.14.0
<details>
✅ TestAccDataSourceVSphereComputeClusterHostGroup_basic (3.54s)
✅ TestAccDataSourceVSphereComputeCluster_absolutePathNoDatacenter (11.18s)
✅ TestAccDataSourceVSphereComputeCluster_basic (3.11s)
✅ TestAccDataSourceVSphereContentLibrary_basic (8.17s)
✅ TestAccDataSourceVSphereCustomAttribute_basic (2.33s)
✅ TestAccDataSourceVSphereDatacenter_basic (2.16s)
✅ TestAccDataSourceVSphereDatacenter_defaultDatacenter (2.12s)
✅ TestAccDataSourceVSphereDatacenter_getVirtualMachines (2.39s)
✅ TestAccDataSourceVSphereDatastoreCluster_absolutePathNoDatacenter (3.23s)
✅ TestAccDataSourceVSphereDatastoreCluster_basic (3.41s)
✅ …
=> chore: update changelog for v2.14.0

CHANGELOG.md
<details>
✅ TestAccDataSourceVSphereComputeClusterHostGroup_basic (4.6s)
✅ TestAccDataSourceVSphereComputeCluster_absolutePathNoDatacenter (12.15s)
✅ TestAccDataSourceVSphereComputeCluster_basic (2.58s)
✅ TestAccDataSourceVSphereContentLibrary_basic (9.47s)
✅ TestAccDataSourceVSphereCustomAttribute_basic (2.35s)
✅ TestAccDataSourceVSphereDatacenter_basic (2.27s)
✅ TestAccDataSourceVSphereDatacenter_defaultDatacenter (2.63s)
✅ TestAccDataSourceVSphereDatacenter_getVirtualMachines (2.29s)
✅ TestAccDataSourceVSphereDatastoreCluster_absolutePathNoDatacenter (3.45s)
✅ TestAccDataSourceVSphereDatastoreCluster_basic (3.88s)
✅ TestAccDataSourceVSphereDatastoreCluster_getDatastores (3.55s)
✅ …
=> chore(release): v2.14.1

docs/resources/virtual_disk.md
=> fix: doc typo for virtual_disk

docs/resources/virtual_machine.md, vsphere/virtual_machine_config_structure.go
Updates the handling of the `hardware_version` option for virtual machines to enforce a more precise set of allowed version ranges and improves both validation logic and documentation. The changes ensure only supported hardware versions can be set, and the documentation now clearly reflects these constraints.
* Updated the validation logic for the `hardware_version` field in `virtual_machine_config_structure.go` to allow only versions within the ranges: 4, 7–11, 13–15, and 17–22, replacing the previous continuous range check.
* Added a helper function `generateHardwareVersionDescription` to dynamically generate the description string for allowed hardware version ranges, ensuring consistency between code and documentation.
* Updated the documentation in `docs/resources/virtual_machine.md` …
=> refactor: update hardware versions and validation

CHANGELOG.md
Updating changelog for v2.15.0
Output:
=> chore(release): v2.15.0

.github/workflows/release.yml, scripts/release-notes.sh
Automates the generation and inclusion of release notes in the release workflow by extractin content from the `CHANGELOG.md` for the release tag and then applying these to GoReleaser as part of the release process.
* Added `scripts/release-notes.sh` that extracts the relevant section from `CHANGELOG.md` based on the release tag and generates a `RELEASE_NOTES.md` file. It handles missing changelog or section gracefully by writing a placeholder if needed.
* Updated `.github/workflows/release.yml` to run the release notes generation script before the release step, preview the first 40 lines of the generated notes, and ensure the notes file is present and non-empty.
* Modified the Goreleaser step in `.github/workflows/release.yml` to use the generated `RELEASE_NOTES.md` as the release notes …
=> chore(gh): generate release notes on release

vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
Errors during vMotion are not returned and `terraform apply` provides false positive results.
Output:
https://github.com/vmware/terraform-provider-vsphere/issues/1872
```
- `r/virtual_machine` - Propagate error to user when vMotion fails
```
=> fix: return error when vMotion task fails
